### ISSUE TITLE
Cannot access the WebUI from outside my network (tried proxy as well)

### ISSUE THREAD

**Issue by garret** [haugene/docker-transmission-openvpn#1053]
I know this issue has been described several times, but I'm really failing to comprehend the following situation.

I'm running this container on a rpi3b+ with DietPi (ip `192.168.40.200`) connected to the router (ip `192.168.40.1`) via cable. In particular, this is the command I am using: 
```
docker run --name=transmission-openvpn \
              --cap-add=NET_ADMIN -d \
              -v /mnt/media/transmission/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=MYVPN \
              -e OPENVPN_CONFIG=MYCONFIG \
              -e OPENVPN_USERNAME=MYUSERNAME \
              -e OPENVPN_PASSWORD=MYPASSWORD \
              -e WEBPROXY_ENABLED=true \
              -e TRANSMISSION_WEB_UI=transmission-web-control \
              -e TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false \
              -e TRANSMISSION_DOWNLOAD_QUEUE_SIZE=5 \
              -e TRANSMISSION_ENCRYPTION=1 \
              -e TRANSMISSION_SPEED_LIMIT_UP=25 \
              -e TRANSMISSION_SPEED_LIMIT_UP_ENABLED=false \
              -e LOCAL_NETWORK=192.168.40.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              --dns 8.8.8.8 \
              --dns 8.8.4.4 \
              --restart=unless-stopped \
              -p 9091:9091 \
              haugene/transmission-openvpn:latest-armhf
```
Everything works well from within the LAN: I can access the webUI from another computer on the same LAN (for instance from ip `192.168.40.100`). The vpn inside the container works great. Then I forward the port 9091 on the router, and try accessing it from outside (`http://mypublicip:9091/transmission/web/`) without any luck. I can instead access outside without any problems a Sonarr setup installed on exactly the same device. 

I read some possible workaround was starting up another docker (the proxy as described in the wiki). This is the command I give: 
```
docker run -d \
      --link transmission-openvpn:transmission \
      -p 8080:8080 \
      haugene/transmission-openvpn-proxy
```
But still cannot connect to `http://mypublicip:9091/transmission/web/ `

Do you know why and how to solve? I cannot understand how in the wiki there are so few lines in what to do it and to me it doesn't work.

**Comment by MrTarantula** [comment]
There could be a number of reasons why you can't access the UI. 

First, the router and internet access. Have you tried rebooting it after forwarding the port? Are you sure you have the right public IP? Does your ISP block specific web ports? Try it with `-p 9595:9091` or something similar and forward that port.

Second, the proxy. If you want to use the `transmission-openvpn-proxy` you should be forwarding port 8080 on your router so you hit the proxy.

**Comment by garret** [comment]
> Have you tried rebooting it after forwarding the port? 

Yes, at least 10 times for both the router and the Raspberry Pi. 

> Are you sure you have the right public IP? 

Yes, I used both my public IP and the DuckDns address. On the same Raspberry Pi I have an installation of Sonarr, Radarr, Jackett, Bazarr, Plex and Home Assistant. I can connect to each of these without any issue outside my internal network. 

> Does your ISP block specific web ports? 

No, I am allowed to port forward all the doors I want. 

> Try it with `-p 9595:9091` or something similar and forward that port.

Tried but still cannot reach `http://mypublicip:9595/transmission/web/`

> Second, the proxy. If you want to use the `transmission-openvpn-proxy` you should be forwarding port 8080 on your router so you hit the proxy.

The port 8080 was forwarded on the router for the Raspberry Pi ip. I cannot still access `http://mypublicip:8080/transmission/web/`. Actually, I cannot even access when I'm inside the Raspberry Pi (`curl localhost:8080/transmission/web/` returns nothing found).

**Comment by pkishino** [comment]
check the proxy logs to make sure it connects properly to the transmission docker.
also check that it is listening to 8080 and it is the proyx container and not some other process
the port forward to transmission container won't work I believe if you go directly from router to container as you have not whitelisted the ip you would be accessing from.. I recommend getting the proxy working. otherwise you could setup your own nginx or apache reverse proxy

**Comment by garret** [comment]
@pkishino It actually seems that the proxy container is created but for some reasons I cannot find it in the list of containers by giving the `docker ps` command. So this is why it might not work. Additionally, the container is not found even when checking the logs. 

```
root@DietPi:~# docker run -d \
      --link transmission-openvpn:transmission \
      -p 8080:8080 \
      haugene/transmission-openvpn-proxy
e38d39890c8a8d36c7ad043e4497b8e544f64fa8d47653776cfc9d02f4564de8
root@DietPi:~# docker logs e38d39890c8a8d36c7ad043e4497b8e544f64fa8d47653776cfc9d02f4564de8
standard_init_linux.go:211: exec user process caused "exec format error"
root@DietPi:~# docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
30d23bf098c2        haugene/transmission-openvpn:latest-armhf   "/usr/bin/entry.sh d…"   6 days ago          Up 3 days           0.0.0.0:9091->9091/tcp   transmission-openvpn
root@DietPi:~#
```

**Comment by MrTarantula** [comment]
if it shows with `docker ps -a` you should be able to get the container name (and therefore the logs). Not sure how much I can help with the proxy, though. I run everything through `linuxserver/letsencrypt` reverse proxy, which is just a container-aware reverse proxy that automatically maintains SSL certs.

**Comment by pkishino** [comment]
Yeah, that is very very strange that it does not show up. Try restart docker?

**Comment by haugene** [comment]
Hey @garret.

So, first. The reason why you can't acces `http://public-ip:9091` is that your client IP in that case is not within the LOCAL_NETWORK you've defined. Let's say you're on the move and you currently have an ip of 100.120.160.180. When your request hits the transmission container it will try to respond to that IP and since it is not within LOCAL_NETWORK it will be routed through the VPN connection. Your client might get the response, but it's now from the VPNs IP and that's not where it expects to get it from and it will reject it.

If you knew all the IPs you were going to access it from, outside your network, you could add them to the LOCAL_NETWORK parameter. **BUT** your torrent traffic follows the same rules - so you don't want to open too much.

The reason you can access your Sonarr with the same setup is because the Sonarr container doesn't have VPN, so the response to the client will not be diverted through another interface. That is also the plan with the proxy container. It doesn't have VPN and can therefore respond to you at any IP. The proxy container is also on the local network of the transmission container by default (remember that your docker containers run in a different subnet, typically 172.16.x.y).

If you don't want to open for all IPs (essentially disabling VPN), or open for specific remote IPs, then your only option is the proxy container. And the reason that's not starting is that you're not running the armhf version of it and you're on a Pi. I can't guarantee it will start anyways, but you're one step closer if you run `haugene/transmission-openvpn-proxy:latest-armhf` and forward port 8080 as @pkishino said.

**Comment by garret** [comment]
@haugene You're right! Thank you so much. I'm so happy! 
This was the command I had to give: 

```
docker run -d \
      --link transmission-openvpn:transmission \
      -p 8080:8080 \
      haugene/transmission-openvpn-proxy:latest-armhf
```

I could feel it was a stupid mistake. I hope it can help other newbie people.

**Comment by haugene** [comment]
Glad I could help 👍  Changed the title to include rpi for people looking for similar issues in the future.

**Comment by GuillaumeCisco** [comment]
Thanks a lot for the help.
IT did save me a night of effort.
I event bought a private VPN static IP to test things. Not understanding what's was going on.
Networks with docker etc..., are still a bit obscure to me but thanks to your explanation, I was able to setup my project.

I know this message does not really give value, but it is a big thank you and a confirmation things work when correctly setup.

Thank you again :D
