### ISSUE TITLE
Allow opening a port globally

### ISSUE THREAD

**Issue by bplow** [haugene/docker-transmission-openvpn#1060]
The UFW_EXTRA_PORTS= environment variable limits the ports to the docker network. I would like to hook up another container to the transmission container via --network-container:transmission and allow it to listen on a port, just like transmission does. This can be accomplished by manually execing into the container and running "ufw allow <port>", but a container restart breaks this configuration.

**Comment by mehulboricha** [comment]
May I ask you what are you trying to accomplish here?

**Comment by haugene** [comment]
You're trying to have another container use the vpn from openvpn-container, and expose a port, while haveing UFW enabled. Am I right?

I don't see why that should be a problem. Before I dig deeper. There should be 3 steps here:
- transmission-openvpn container is started and also exposing the extra port for the second container (ie. add `-p 8080:8080` if you want to expose port 8080 from the other container)
- The second container is started with --network=container:<transmission-openvpn-container>
- The transmission-openvpn container has UFW_EXTRA_PORTS=8080

Can you confirm you've done all of this?

**Comment by bplow** [comment]
> You're trying to have another container use the vpn from openvpn-container, and expose a port, while haveing UFW enabled. Am I right?
> 
> I don't see why that should be a problem. Before I dig deeper. There should be 3 steps here:
> 
>     * transmission-openvpn container is started and also exposing the extra port for the second container (ie. add `-p 8080:8080` if you want to expose port 8080 from the other container)
> 
>     * The second container is started with --network=container:
> 
>     * The transmission-openvpn container has UFW_EXTRA_PORTS=8080
> 
> 
> Can you confirm you've done all of this?

I have done all that and I can confirm that this does work by executing "ufw status" from within the container, however what I was asking for is opening the port not just for the docker subnet. When a port is opened via UFW_EXTRA_PORTS, it is only accessible from within the docker network (for instance, I want to route an mtproto proxy server through transmission's vpn tunnel, but in order for it to be connectable, I have to manually ufw allow its port). I take it this isn't a popular demand, and in my own case I have made this work with a clunky crontab script setup, so you can close this issue if you think this option would be excessive.

**Comment by haugene** [comment]
Hmm. It's been a while since there were any changes here, and I don't know that part of the code by heart. But there is a UFW_ALLOW_GW_NET flag that can be set to "true".

Can you try that? I see in the code that it will switch between allowing a GW and a GW_CIDR.

I don't want to dismiss this feature though. There have been several issues posted about re-using the VPN connection for other stuff and I've pointed them to the --network=container: flag of Docker.
Of course, this in combination with UFW is more of a corner case but I think it should be supported.

**Comment by haugene** [comment]
On second though I'm not so sure. Still good if you try it, but I don't think it will be globally available anyways. It might be enough though.

It's [this line and block](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L187) I'm referring to:
```
  if [[ -n "${UFW_EXTRA_PORTS-}"  ]]; then
    for port in ${UFW_EXTRA_PORTS//,/ }; do
      if [[ "${UFW_ALLOW_GW_NET,,}" == "true" ]]; then
        ufwAllowPortLong port GW_CIDR
      else
        ufwAllowPortLong port GW
      fi
    done
  fi
```

Now we do have two functions to open ports, and one of them is global. So there could be another option here. But we have to figure out an intuitive way for this to work and sensible default behaviour. I think your issue would be solved if we used ufwAllowPort instead of ufwAllowPortLong

```
## Open port to any address
function ufwAllowPort {
  typeset -n portNum=${1}
  if [[ "${ENABLE_UFW,,}" == "true" ]] && [[ -n "${portNum-}" ]]; then
    echo "allowing ${portNum} through the firewall"
    ufw allow ${portNum}
  fi
}

## Open port to specific address.
function ufwAllowPortLong {
  typeset -n portNum=${1} sourceAddress=${2}

  if [[ "${ENABLE_UFW,,}" == "true" ]] && [[ -n "${portNum-}" ]] && [[ -n "${sourceAddress-}" ]]; then
    echo "allowing ${sourceAddress} through the firewall to port ${portNum}"
    ufw allow from ${sourceAddress} to any port ${portNum}
  fi
}
```

**Comment by bplow** [comment]
I'm pretty sure I tried just about every combination of options that were on the wiki/in the env file. The only port that gets forwarded properly is transmission's listening port.
