### ISSUE TITLE
Wireguard

### ISSUE THREAD

**Issue by ylor** [haugene/docker-transmission-openvpn#1107]
With Wireguard hitting 1.0 and becoming part of the Linux 5.6+ kernel, I'd like to request Wireguard be added in addition or in place of OpenVPN. Mostly for its decreased overhead on CPU limited hosts.

**Comment by haugene** [comment]
I like it. Just saw the release myself. I've read a couple of blogs about this along the way as it has seemed relevant to this project and you know, just linux computing in general.
I don't have a complete overview on what that would mean for this project though. I can read up, but if you have some knowledge I'm all ears.

The providers have to support it and it's a separate set of configs I guess? Or is there some interoperability here (sounds too good to be true).

**Comment by gpongelli** [comment]
Hi, I'm also using Wireguard.
As you've pointed out, the VPN provider have to support it because the config file is completely different, it's a conf file with just something like this
```
[Interface]
PrivateKey = ....
Address = ....
DNS = ....

[Peer]
PublicKey = ....
PresharedKey = ....
Endpoint = ....
AllowedIPs = ....
PersistentKeepalive = ....
```

**Comment by dsbert** [comment]
PIA supports it but has not provided any guidance on setting it up outside of their official clients. https://www.privateinternetaccess.com/forum/discussion/38293/wireguard-on-linux

**Comment by lxs** [comment]
Indeed, PIA's client has option to use the WireGuard protocol.

Not seen similar update yet for the likes of ExpressVPN client, VPNunlimited client, nor external clients. 

- Blog post by Express VPN team on topic (last updated 12 April **2019**):
https://www.expressvpn.com/blog/expressvpn-wireguard-update/
- Overview from VPNunlimited team https://www.vpnunlimitedapp.com/blog/introducing-wireguard-vpn-protocol/
- Arstechnica's comments on WireGuard's recent release (March 2020):
https://arstechnica.com/gadgets/2020/03/wireguard-vpn-makes-it-to-1-0-0-and-into-the-next-linux-kernel/ 
- List of formal verification of WG https://www.wireguard.com/formal-verification/ - with INRA (FR) publishing their machine-checked proof of the protocol https://hal.inria.fr/hal-02100345

**Comment by webnetwiz** [comment]
Looks like NordVPN is officially supporting WireGuard natively now: [https://nordvpn.com/blog/one-very-strong-reason-to-be-excited-about-nordlynx/](url)

**Comment by pkishino** [comment]
PrivateVPN are doing testing currently

**Comment by UltraSub** [comment]
Mullvad is also supporting and advising Wireguard:
https://mullvad.net/en/help/tag/wireguard/

**Comment by frankyw** [comment]
Torguard also supports Wireguard, and the speed difference is significant. An option to use Wireguard instead on OpenVPN would be awesome.

**Comment by ksurl** [comment]
vpnunlimited also supports wireguard with config file option

**Comment by adamtmitchell** [comment]
FYI VPN.ac also support Wireguard since March last year: https://vpn.ac/knowledgebase/120/WireGuard-Status.html

**Comment by drmartinsweden** [comment]
Windscribe also support WireGuard.

https://windscribe.com/getconfig/wireguard

**Comment by PaulR1978** [comment]
I too would like to see this docker start using wireguard.  I've looked into this, and I found some scripts that will do the connection and get the tokens for wireguard to connect.  I hope these scripts will come in handy, really looking forward to using wireguard in this docker!

[https://gist.github.com/triffid/da48f3c99f1ff334571ae49be80d591b](https://gist.github.com/triffid/da48f3c99f1ff334571ae49be80d591b)

Cheers, and thanks for the great work!

**Comment by mattstrayer** [comment]
That's fantastic work @PaulR1978. @haugene I'd be happy to lend a hand on implementation.

**Comment by varac** [comment]
There are a few wireguard docker containers which might be a good guidance how wireguard could be configured in a docker context, i.e. https://hub.docker.com/r/linuxserver/wireguard

**Comment by haugene** [comment]
Great stuff 👍  Thanks for posting, I think these links will be great during implementation!

I'm really looking forward to implementing this and would love some assistance @mattstrayer.
As for the timeline. I think it will still be postponed a few weeks, but we should get this in during the autumn.

There are two reasons I want to wait just a little. One of them is that I live in the North (Oslo) and we're probably getting the last wave of warm weather these days. So it's a bit selfish, but the rain and cold is coming and then there will be more time for coding then. Unnecessary sacrifice of points with the gf to insist on locking myself in my room in the sun.

But, secondly and more important. We are doing a rewrite of the project structure now. That work has begun on the dev branch and I have another feature branch in the works. The idea is to make the project more modularised so that everything isn't such a "lump" as it is today. The scripts have just grown with new features and now is the time to extract some of the functionality and handle it more generally. At the end of this I also think that the separation between openvpn and transmission will be clearer, so it would be easier to swap the startup from openvpn to wireguard.

Once I have merged the next big feature branch I will create a feature branch for wireguard, and then I'm happy to accept and play with any PRs to see how we can build this. But I think there will be many merge conflicts if we start before that. Anyways, let's aim for having Wireguard a part of the 3.0 release of the image 😄

**Comment by varac** [comment]
Awesome !!! :medal_sports:

**Comment by PaulR1978** [comment]
Hi Guys,

Me again,  Looks like PIA put out scripts as of a couple days ago.  Should really help with implementing wireguard into this Docker.

Scripts are at [https://github.com/pia-foss/manual-connections](https://github.com/pia-foss/manual-connections)

**Comment by mattstrayer** [comment]
That's fantastic news, thanks for sharing @PaulR1978 !

**Comment by varac** [comment]
Might be of interest: https://www.reddit.com/r/selfhosted/comments/iwz9hj/simple_wireguard_docker_network_setup/

**Comment by b055k060644** [comment]
Excuse my ignorance, I'm still not 100% sure how GitHub works. 

So, I need to run Mullvad Wireguard to bypass Virgin Media VPN throttling here in the UK.

So is it as simple as changing the     "-e "OPENVPN_CONFIG= " to a different config name?

If so, where can I find the wire guard config names?

**Comment by ksurl** [comment]
@b055k060644 wireguard is not added yet. this is a feature request discussion

**Comment by HotBlack77** [comment]
Here is another github project for a docker that transmission over wireguard: https://github.com/SebDanielsson/docker-wireguard-transmission

I must admit that I much prefer this project due to all the additional configuration of transmission it allows, but the other project might be good inspiration for how to go about adding wireguard support to this container.

**Comment by neutrongenious** [comment]
VPNUnlimited also supports it. +1 for feature request.

**Comment by ksurl** [comment]
> VPNUnlimited also supports it. +1 for feature request.

already [mentioned](https://github.com/haugene/docker-transmission-openvpn/issues/1107#issuecomment-646942158)

**Comment by ajhorvath20** [comment]
Hello @haugene no rush please take your time but any update on this, is there any beta tag :) Thanks

**Comment by ksurl** [comment]
The focus is on bug fixing right now for the 3.x release. Next up is separating provider configs from the main repo so they can be updated independently.

**Comment by amosshapira** [comment]
For what it's worth, SharkVPN also supports WireGuard as of October 2020: https://surfshark.com/blog/wireguard-protocol-is-now-live-on-surfshark

**Comment by amosshapira** [comment]
> The focus is on bug fixing right now for the 3.x release. Next up is separating provider configs from the main repo so they can be updated independently.

Is the code available somewhere to build from?

**Comment by derekcentrico** [comment]
Apologies for being that guy, but curious if this is in progress?  Started playing w/ wireguard in general recently with NordVPN and wow amazing how much better it is for overhead in general.

**Comment by Turnipisum** [comment]
+1 for wireguard please.

**Comment by haugene** [comment]
It's a fair question @derekcentrico. The progress is not great :see_no_evil: I've been optimistic on this before and it has not gone as expected. We launched v3 without wireguard support even though I first thought the two could be bundled.

And now the next major change is to extract all the configs out into a separate repo (https://github.com/haugene/docker-transmission-openvpn/pull/1744). But this is not entirely a separate concern. Most of the time spent maintaining this project has been related to updating and adding support for providers. By extracting it I hope we can focus more on the core functionality and let the configs be maintained more by the community and by any user that wants to run with his/her own configs.

It has also been a bit of a headache thinking about bringing in a whole new structure of configs for Wireguard when the old solution was so time consuming. Cleaning up the configs will hopefully prepare a better structure in the project and free up time to get started on Wireguard.

**Comment by derekcentrico** [comment]
@haugene copy all. I wish I was skilled to be of value. Alas I can only send you coffee.

**Comment by kevinoconnor7** [comment]
> It has also been a bit of a headache thinking about bringing in a whole new structure of configs for Wireguard when the old solution was so time consuming. 

Hopefully Wireguard will be easier! Most providers (in my experience) just give you the `wg0.conf` to download. Will likely be easier to just have people dump them into a volume. Then you don't need to be worried about dealing with all the various providers explicitly.

**Comment by mattstrayer** [comment]
Commenting purely to remove the stale tag. @haugene please let me know how I can best help with the wireguard work. Thank you!

**Comment by rufflepot** [comment]
Just adding that [OVPN ](https://www.ovpn.com/en/wireguard) is also supporting Wireguard since a little while back.

**Comment by usma0118** [comment]
@haugene had you thought about using [k8s-at-home](https://github.com/k8s-at-home/library-charts) as base base library (provides support for [winreguard and openvpn](https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common).

**Comment by MrEaoP** [comment]
I couldn't wait, and last night I gave it another shot - that is - I took the plunge and tried to get "Transmission + Torrent + Wireguard" running and sort of succeeded. 

The reason I wanted to try this again, was  that I suspected that my VPN provider for some reason screwed up their openvpn  service, - giving my torrents very, very slow speeds, so I wanted to try wireguard and se if there was any difference (and  switching to wireguard gave my back normal torrent speeds).

What I managed to do was get a Transmission container to use a Wireguard container network. Yay.
I can (only) access Transmission via my reverse proxy Ngnix container - but that's fine, I have a long and strong password.
I failed to get a Proxy container to use the same Wireguard's container network.
Instead I hade to settle with a "OpenVPN + proxy" container running by itself.

So to conclude, I ended up with "Transmission" + Wireguard" (2 containres) & "Proxy + OpenVPN" (1 container) solution. The proxy part is a bit slow (because I still think they screwed something up on their part - but I'm wrong on a daily basis so who knows...), but the proxy part was more of a bonus for me. This will do for the time being.

That said, a single container containing all would be nicer...and a lot less trouble getting to work,

**Comment by amosshapira** [comment]
> I couldn't wait, and last night I gave it another shot - that is - I took the plunge and tried to get "Transmission + Torrent + Wireguard" running and sort of succeeded.

Are there any bits of code/configuration you can share which can help progress this ticket? Perhaps push them to a fork an link from here?

Thanks.

**Comment by MrEaoP** [comment]
I don't mind sharing what little I have accomplished at all, I just don't know if this thread is the right place to write a little guide in. Seeing as it my approach doesn't involve "haugene/docker-transmission-openvpn" but instead three other containers.

I just don't want to "clutter" this thread with information that's not relevant to getting a "haugene/docker-transmission-wireguard".

I've never forked in my life, but maybe that is the right way to go - I'll look into it :)

**Comment by ksurl** [comment]
You could start a post in the discussion section.
