### ISSUE TITLE
[Improvement] Automatic bundle refresh

### ISSUE THREAD

**Issue by gpongelli** [haugene/docker-transmission-openvpn#1110]
**Is your feature request related to a problem? Please describe.**
This improvement is related to my pull request #1104 : try to find a way to automatically being able to download new bundle, sed content if needed, move the file, restart OpenVPN.

**Describe the solution you'd like**
I think about something like:

- having an "update.sh" file under each provider folder

- call the "provider/update.sh", if present, when something bad happen (tunnel down? try to check if new bundle is available; if so download it and try to use new bundle, maybe this will resolve the issue)

- this will automatically solve the connection issue and surely decrease the issue/PR here about new bundles

- last point: the provider/update.sh shall be executed also on container startup, to address the case of docker image with older certificate bundle

**Describe alternatives you've considered**
It's the way updateFreeVPN.sh should work, but managed for every folder that contains the update script.

**Additional context**
Please also refer to my PR, seems something is not working due to my lack of knowledge on how the setup/teardown cycle is done.

**Comment by gpongelli** [comment]
Just for further investigation, that I've noted on UpdateFreeVPN.sh, it's needed to have a connected interface to internet to do the upgrade (downloading new certificates) BEFORE opening the tunnel again (or for the first time).
Is this feasible ? If not, this improvement cannot be reached.

**Comment by haugene** [comment]
Totally agree on the ultimate goal here. I've kind of tried this before as well. There's a script at `/etc/openvpn/updateConfigs.sh` that will search the provider directories for "updateConfigs.sh" script and execute them. It was intended as a build step in the image to reduce the amount of Issues and PRs of invalid provider configs. Triggering the provider scripts on startup would be a natural next step.

Some providers do not have a public URL where their .ovpn files can be retrieved. I'm not sure exactly why, but users needs to be logged in to get them. So this will not work for all providers. Still it needs to be extracted from this repo if it is to be maintainable.

I've been working on a feature to provide OpenVPN config using a URL and then the image would download it. The idea is that all less popular, or less open providers could be supported by just uploading the config to dropbox and sharing it with a public URL.

Have a look at this branch, and compare it to `dev` so you don't get all the provider stuff that is diff against master. https://github.com/haugene/docker-transmission-openvpn/tree/feature/external-config

Basically I want to split the per-provider behaviour to a separate script for each provider.
If that script sets the CHOSEN_OPENVPN_CONFIG variable then it is assumed to be a path to a "ready-to-use" config file. If it doesn't set it, then the regular checks are done to find the config to use (looking at OPENVPN_CONFIG and finding file in provider directory).

This will continue to be relatively backward compatible for the time being. Then we can write scripts that fetch the bundles for the most used providers and then start to phase out the others and refer to the URL support for linking to your own Dropbox where you can put the file.

You can see from my branch that I'm trying to make a script for sed'ing the configs as needed. The plan is that it should be the same for all providers with a good default behaviour. But we should also support disabling it or part of it. That's why I'm thinking a variable that can take a pattern that describes what to do. Like "chmod 777 /some/folder". Each digit describes a feature.

Lots of text here. Let me know what you think 😄

**Comment by gpongelli** [comment]
> Totally agree on the ultimate goal here. I've kind of tried this before as well. There's a script at `/etc/openvpn/updateConfigs.sh` that will search the provider directories for "updateConfigs.sh" script and execute them. It was intended as a build step in the image to reduce the amount of Issues and PRs of invalid provider configs. Triggering the provider scripts on startup would be a natural next step.

I didn't know about that file, this should work.


> Some providers do not have a public URL where their .ovpn files can be retrieved. I'm not sure exactly why, but users needs to be logged in to get them. So this will not work for all providers. Still it needs to be extracted from this repo if it is to be maintainable.
> 
> I've been working on a feature to provide OpenVPN config using a URL and then the image would download it. The idea is that all less popular, or less open providers could be supported by just uploading the config to dropbox and sharing it with a public URL.

This can be a good idea to reduce PRs when the oven files are not freely available.


> Have a look at this branch, and compare it to `dev` so you don't get all the provider stuff that is diff against master. https://github.com/haugene/docker-transmission-openvpn/tree/feature/external-config
> 
> Basically I want to split the per-provider behaviour to a separate script for each provider.
> If that script sets the CHOSEN_OPENVPN_CONFIG variable then it is assumed to be a path to a "ready-to-use" config file. If it doesn't set it, then the regular checks are done to find the config to use (looking at OPENVPN_CONFIG and finding file in provider directory).
> 
> This will continue to be relatively backward compatible for the time being. Then we can write scripts that fetch the bundles for the most used providers and then start to phase out the others and refer to the URL support for linking to your own Dropbox where you can put the file.
> 
> You can see from my branch that I'm trying to make a script for sed'ing the configs as needed. The plan is that it should be the same for all providers with a good default behaviour. But we should also support disabling it or part of it. That's why I'm thinking a variable that can take a pattern that describes what to do. Like "chmod 777 /some/folder". Each digit describes a feature.
> 

I think that the first thing to be done is to move away from bash, using a programming language.
Then it will be possible to easily define an interface between the per-provider code and the following openvpn call without playing with env variables like in bash.

**Comment by haugene** [comment]
I'm a bit back and forth on the whole "moving away from bash" thing. I like it because of the benefits like a clearly defined interface as you say, and maybe clearer semantics and more tooling/built in functions.

Had a look at golang after you mentioned it, and it looks cool. But for now I'm leaning towards doing the structural change first and then evaluate a new language after.

I think the next version will not be completely backwards compatible anyways. So then I think it's time to update to 3.x version. I'll merge what I can to master, then make the dev-branch a 3.0-alpha version and hopefully we can get people to run it at test it for the different providers and close a lot of the "new provider" issues by referring to the URL-option.

**Comment by haugene** [comment]
Also thinking to ditch the ubuntu base image from version 3.0 and base it on Alpine only (plus the arm versions)
