### ISSUE TITLE
PIA Error

### ISSUE THREAD

**Issue by noumenon272** [haugene/docker-transmission-openvpn#1118]
I have all of the sudden started getting an error when trying to connect to PIA. Everything was working fine until last week. 

```
STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
Wait for tunnel to be fully initialized and PIA is ready to give us a port
Sat Apr  4 07:27:34 2020 Initialization Sequence Completed
Generating new client id for PIA
Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding
curl encountered an error looking up new port: 7
```

I have tried setting OPENVPN_CONFIG to multiple PIA hosts that support port forwarding, although prior to this error, I actually had that line commented out and was just not using port forwarding and everything worked fine.

I also tried rolling back to 2.10, but I'm still getting the same error.

any ideas?

**Comment by ilike2burnthing** [comment]
These are the ones you're using?
- CA Toronto
- CA Montreal
- CA Vancouver
- DE Frankfurt
- DE Berlin
- Czech Republic
- Spain
- Switzerland
- France
- Germany
- Romania
- Israel

https://www.privateinternetaccess.com/helpdesk/kb/articles/can-i-use-port-forwarding-without-using-the-pia-client

**Comment by ampularity** [comment]
Yes I am having the same issue as noumenon272 and I am using CA Montreal. Everything was working until around last week.

**Comment by dreondre** [comment]
Yes I'm getting the exact same error and I've tried at least Toronto, Montreal and Vancouver.

**Comment by acosmichippo** [comment]
yeah i noticed many of the servers that used to do port forwarding do not anymore.  Switzerland seems to work.

**Comment by matthewjocko** [comment]
I am having the same issue with PIA - issue started today

**Comment by ilike2burnthing** [comment]
From the link in dreondre's post:
```
When attempting to use port forwarding (on servers outside of Canada), if you receive
"Failure" message, please re-connect until the port does populate as intended. Should
you find that the issue persists, please submit a support ticket here:

https://www.privateinternetaccess.com/helpdesk/new-ticket
```

**Comment by miigotu** [comment]
If you download the PIA client on your phone, you can go to the region select screen and see which servers support port forwarding. CA servers no longer support port forwarding.

**Comment by shawn8888** [comment]
Same problem here. All PIA Canadian servers cannot Port forwarding any more. I just opened a ticket on PIA website. You should open a ticket as well so they know this is a key feature of their service.

**Comment by ilike2burnthing** [comment]
They're already working on it. Only open a ticket if you get an issue on a server outside of Canada.

**Comment by Muckoma** [comment]
Any location working for you guys? 

I am seeing this in my log. 

`[2020-04-17 01:23:49.343] Couldn't connect socket 24 to 2a00:23c5:b408:c700:6c31:ef21:1171:7e1c, port 55851 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:49.343] Couldn't connect socket 24 to 2a00:23c5:b408:c700:6c31:ef21:1171:7e1c, port 55851 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:50.381] Couldn't connect socket 24 to 2601:241:c203:9480:2d60:c13a:aa00:d554, port 38691 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:50.381] Couldn't connect socket 24 to 2601:241:c203:9480:2d60:c13a:aa00:d554, port 38691 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:50.381] Couldn't connect socket 24 to 2002:4d5c:5f07::4d5c:5f07, port 43933 (errno 99 - Cannot assign requested address) (net.c:290)
[2020-04-17 01:23:50.382] Couldn't connect socket 24 to 2002:4d5c:5f07::4d5c:5f07, port 43933 (errno 99 - Cannot assign requested address) (net.c:290)
`

**Comment by lhanson** [comment]
@Muckoma I don't think those errors are related; that seems to be an IPv6 issue which I'm also getting, but does not affect IPv4 connectivity. Search other issues here for examples. A possibly relevant distinction for those having trouble with PIA port forwarding is that this issue specifically seems to pertain to this error message:

`Port forwarding is already activated on this connection, has expired, or you are not connected to a PIA region that supports port forwarding`

Are you seeing that message in your docker logs? I'm now only seeing that from CA Toronto, which is a [known issue](https://www.privateinternetaccess.com/helpdesk/news/posts/april-14-2020-port-forwarding-outage). CA Montreal is working for me, I suppose I'll stick with that until the Toronto issue is resolved.

If you're *not* seeing that message in your docker logs but are still having problems with seeing the forwarded port being available (something I just resolved for myself today as well), here was my thought process in troubleshooting it: wondering whether the problem was with PIA not actually forwarding the port or whether Transmission wasn't being configured correctly, I logged into the docker container (`docker exec --interactive --tty transmission bash`) and followed the Transmission documentation's [advice on troubleshooting port forwarding](https://github.com/transmission/transmission/wiki/Why-is-my-port-closed%3F#port-check-website-is-down). Trying to use https://canyouseeme.org to check for open ports within the container, it became obvious that the container was not able to resolve DNS.

Adding `--dns 1.1.1.1 --dns 1.0.0.1` (Cloudflare DNS) to my `docker run` command allowed transmission's port check to succeed and the port now shows as open (Using the CA Toronto PIA server). Substitute whatever DNS server(s) you prefer. I'm not sure whether the forwarded port still actually works and it's just the Transmission UI that reports it as closed, but specifying DNS servers for the container made everything happy again for me.

**Comment by miigotu** [comment]
> If you download the PIA client on your phone, you can go to the region select screen and see which servers support port forwarding. CA servers no longer support port forwarding.

**Comment by lhanson** [comment]
>> If you download the PIA client on your phone, you can go to the region select screen and see which servers support port forwarding. CA servers no longer support port forwarding.

What are you basing this opinion on? I'm looking at the Android app right now, and all three CA servers are shown as available for port forwarding. I'm running a transmission container right now which is successfully using port forwarding a port from CA Montreal.

**Comment by tokyotexture** [comment]
I did put in a support ticket to PIA, and they confirmed they were having issues with port forwarding in Canada that they were working on. So it should be temporary, and they said they would put out an announcement once it was resolved. This was maybe 10-14 days ago though. I switched to European port forwarding end point for now, and honestly get speeds as fast as my internet (230Mbps), so I'll just keep it as is tbh.

**Comment by miigotu** [comment]
https://photos.app.goo.gl/jnLnj11MHZUuKvLBA

**Comment by dreondre** [comment]
This is working just fine for me using Montreal so I’m good with this.

**Comment by lhanson** [comment]
> https://photos.app.goo.gl/jnLnj11MHZUuKvLBA

Your screenshot shows that CA servers are listed as being available for port forwarding, just like I'm seeing in my app right now. I'm not sure what you're trying to get at.

**Comment by miigotu** [comment]
Because currently they are, but they weren't when this issue was happening.

**Comment by albatross1** [comment]
Still have same issue as well, tried all above suggestions. Still getting same error.
