### ISSUE TITLE
Different UIs show different values?

### ISSUE THREAD

**Issue by AbrahamGlasser** [haugene/docker-transmission-openvpn#1160]
Hi,

I switched between the original and the ["web control"](https://github.com/ronggang/transmission-web-control/) UIs, and I think there is a discrepancy between the various values shown for torrents.

[Here is a screenshot of the different UIs showing different values between them.](https://imgur.com/a/M8wF2Uk)

Particularly the **file sizes and peer statistics seem different** and misleading. For example, I saw 2000+ peers were connected in the web-control UI, while the original UI showed 24 peers connected. The downloading percentage between the different UIs seem fine, as does the download/upload speed.

I wasn't sure if this was a bug, hope it's helpful! Let me know if you need any more information! I am running this via Docker on a Synology NAS (DS218+).

**Comment by haugene** [comment]
It's an interesting discrepancy you've found - I agree with that :) But this project does not develop or maintain either the WebUI or the transmission-daemon where they both should get their data from.

You could try to communicate directly with the daemon yourself and figure out which one is correct. They might show different counts (connected/verified vs total) or something. I guess a better place for this question is the web control project: https://github.com/ronggang/transmission-web-control

Marking this as a "won't fix" because it's out of scope for this project. You're welcome to keep the issue open for a little while if someone else would take an interest and you could dig a bit. But this is not a bug, not here at least 😄

**Comment by AbrahamGlasser** [comment]
Elucidated here:

https://github.com/ronggang/transmission-web-control/issues/412
