### ISSUE TITLE
Add Port Forwarding flag on supported OPENVPN_PROVIDER page

### ISSUE THREAD

**Issue by shawn8888** [haugene/docker-transmission-openvpn#1168]
Thank you very much Mr. Haugene for your great work!

Forgive me if this is already asked or answered, I was wondering if you could add a port forwarding flag on the supported OPENVPN_PROVIDER page. [https://haugene.github.io/docker-transmission-openvpn/supported-providers/](url)

I have two VPN accounts, PIA, which supports port forwarding feature and VPNUNLIMITED, which does not. Port forwarding is an important feature for torrent downloading, and I would like to know which VPN providers support it and which don’t. It will help me to shop when my accounts expire. It will also help me to enable port forwarding if the VPN supports it!

If that’s too much work, do you know what are the major players out there having this feature, and supported by haugene/transmission?

Thanks!

**Comment by pkishino** [comment]
While I think this is a good idea, this changes a lot I have noticed, and it is also very dependent on location etc etc

**Comment by shawn8888** [comment]
The flag is true, if at least one of the location of the VPN provider supports port forwarding, AND  haugene / docker-transmission-openvpn supports it.
I believe haugene  knows which VPNs support it because he implemented this.

**Comment by pkishino** [comment]
Again, issue is that this does change frequently enough based on issues created here.  I’ve changed providers three times because they stopped supporting it etc. some of the configs here are over a year old and I’m sure there are plenty of outdated ones, but either they aren’t in use, people couldn’t be bothered to report it or something else.
This brings me to the point I want to make, while the supported providers thing is nice, it does create a lot of issues and maintenance work. 
It would be much simpler to get rid of all the providers and create a robust support mechanism that relies on the user to mount a volume with one or multiple configs and use that. It would clean up the issues a lot..
Back to your enhancement request. Anyone can submit a PR, so feel free to modify the documentation and submit a request.
Closing for now
