### ISSUE TITLE
expressvpn file missing?

### ISSUE THREAD

**Issue by bennyb0y** [haugene/docker-transmission-openvpn#1276]
**ExpressVPN**

**Where are the configs?**

It appears the configs are behind a download wall. I am having trouble finding them:
https://www.expressvpn.com/support/vpn-setup/manual-config-for-linux-with-openvpn/

Logs:
```
Setting OPENVPN credentials...,
adding route to local network 192.168.0.0/16 via 172.18.0.1 dev eth0,
Options error: In [CMD-LINE]:1: Error opening configuration file: /etc/openvpn/expressvpn/default.ovpn,
Use --help for more information.,
```

**Comment by bennyb0y** [comment]
I just confirmed with ExpressVPN the files are only available in the login area of their website. It might be worth removing or disabling expressvpn from the supported services. 

**From Expressvpn support:**
> 
> Yes, this for privacy and security purpose. The configuration files can only be downloaded when you're signed in to your account.
> 
> Since the URLs are linked to the account credentials page, that's the only page on where you can download the configuration files. Unfortunately, our website developers did not make the URLs available for free download. If you have an account, you can just simply sign in. Or if you have a friend who has an account, you can ask them to download the configuration files for you.

**Comment by Andy-Wiles-UK** [comment]
Did you manage to get it working using Express VPN? I have a subscription to astrill but the wiki for this doesn't really give clear instructions on what to do, perhaps a video on how to do it would help novice users.

**Comment by peroty** [comment]
I got this to work with ExpressVPN.
I logged into my account and went to this page: https://www.expressvpn.com/setup#manual
There's a separate username and password there. Grab those.
When I first start the container, I left the OPENVPN_CONFIG option blank as I saw recommended on one of the page of the documentation.
This will give you EVERY possible option for that value from the provider.
I chose a US entry at random and went with "my_expressvpn_usa_-_salt_lake_city_udp.ovpn"

I set my `OPENVPN_CONFIG` value as `my_expressvpn_usa_-_salt_lake_city_udp`. I removed the .ovpn file extension because if I didn't it didn't work and the message said to remove it.

Once I did that, I was able to start the container without issue.
