### ISSUE TITLE
Move env into separate file

### ISSUE THREAD

**Issue by pkishino** [haugene/docker-transmission-openvpn#129]
A suggestion to enhance this and simplify running:
Instead of passing in the various environmental variables on the command line, place them all in one file, perhaps if you switch vpns, one per provider. File looks like this
```
OPENVPN_PROVIDER=PROVIDER_NAME
OPENVPN_CONFIG=PROVIDER_CONFIG
OPENVPN_USERNAME=USERNAME
OPENVPN_PASSWORD=PASSWORD
LOCAL_NETWORK=0.0.0.0/24
no_proxy=*.local,169.254/16
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TRANSMISSION_ALT_SPEED_DOWN=50
TRANSMISSION_ALT_SPEED_ENABLED=false
TRANSMISSION_ALT_SPEED_TIME_BEGIN=540
.
.
.
```
then when you load docker, instead of having all the -e XXX you just need one parameter:
`--env-file filename`
this will read in all the env variables then.
Well, I guess you could compile the whole thing into one compose or such but this way makes it easy to switch between vpn providers by just having a separate file for each.
You could even externalise the transmission part and just have one and source it into each file..
anyway, just an idea

I was thinking this could be added to readme or create a template env-file and add.

**Comment by pkishino** [comment]
I'll look at creating a PR with this

**Comment by haugene** [comment]
Hey!

Yes, this can greatly reduce the number of arguments to the `docker run` command and adding a hint on how to use this in the README under tips and tricks and maybe also a template file showing how it's done is a good idea.

I do however have a strong feeling that a lot of users run the container on their NAS and then they rather want to configure all the env variables through the NAS web interface instead of having it as a file in the nas system. But that'll be up to them.

See what you end up with, a PR with some usage tricks is always great :smile:

**Comment by haugene** [comment]
Closing this after merge of #142
