### ISSUE TITLE
Configurable health check

### ISSUE THREAD

**Issue by Zenor27** [haugene/docker-transmission-openvpn#1329]
**Is your feature request related to a problem? Please describe.**

First of all, thank you for this project, it is really good !

However, I'm quite frustrated about the health check option. It is a really good option, but the way it's implemented is not very configurable.

For example if I want to run the health check every 10 minutes instead of every 5 minutes, I just can't...
Another example, if I want to disable health check for some reason,  I just can't...

**Describe the solution you'd like**

I would like a way to configure the health check option, for example with environment variables.

**Describe alternatives you've considered**

Nothing.

**Additional context**

Nothing.

Thanks a lot !

**Comment by pkishino** [comment]
Care to explain why you need to configure it? Or why you would want to disable it? 
You can freely modify the code and build your own version anytime

**Comment by haugene** [comment]
Off the top of my head I think it will be a bit more work to make it configurable by environment variables since it's a Docker feature and linked to the Dockerfile which is not runtime configured.

But you can override several features of it on startup. Not sure how you're running the container, but if it is with docker run you can use these options from [the reference](https://docs.docker.com/engine/reference/run/#healthcheck):
```
  --health-cmd            Command to run to check health
  --health-interval       Time between running the check
  --health-retries        Consecutive failures needed to report unhealthy
  --health-timeout        Maximum time to allow one check to run
  --health-start-period   Start period for the container to initialize before starting health-retries countdown
  --no-healthcheck        Disable any container-specified HEALTHCHECK
```

Adding `--health-interval=10m` sounds like what you want. These options are also available in docker-compose, [see reference](https://docs.docker.com/compose/compose-file/#healthcheck).

For a coding solution I guess we could have an environment variable saying something like "run every 10 min" and then run the actual health check script more frequent. Then we would have to code some logic in the health check that returns the "same result as last time" if 10 minutes haven't passed yet. In effect that would imitate a 10-min interval health check. But it's a bit clunky.

**Comment by Zenor27** [comment]
@pkishino I'm currently using traefik. Traefik do not create routes as long as the healthcheck is not verify, so I need to wait 5 minutes to access transmission...

@haugene I'm going to take a look at the docker-compose options, thanks a lot !

**Comment by haugene** [comment]
FYI. I've also changed the default from 5 min to 1 min in the dev branch now.
