### ISSUE TITLE
Cant connect to transmission, container is "starting".

### ISSUE THREAD

**Issue by terreboo** [haugene/docker-transmission-openvpn#1352]
Hello, the problem I'm having is that the container doesn't seem to start fully, it sits at "Initialization Sequence Completed" until I stop it. Im running the container in Debian buster which is all up to date. Docker version 19.03.12, using docker compose 2.3. I'll attach the docker start up log and my docker compose entry.

I have tried changing the version from latest to dev but it made no difference.

Thanks.

[Docker.log.txt](https://github.com/haugene/docker-transmission-openvpn/files/5177559/Docker.log.txt)
[Docker compose.txt](https://github.com/haugene/docker-transmission-openvpn/files/5177557/Docker.compose.txt)

**Comment by proudindiv** [comment]
I'm at the same place with the PIA VPN problem.  The last change to this repository was for New York and Seattle VPN servers.  I had been using the "US Silicon Valley" but after it failed looking at that last change I tried US Seattle".  It didn't work either.  I'm using the docker on my openmediavault server.  On my ubuntu 20.04 desktop machine, I'm not running transmission, but the PIA VPN app there works fine with "US Seattle" with the VPN IP 156.146.49.101 and whatever certificates are required.

I'm not a docker developer, but it sort of looks like we need to get docker-transmission-openvpn to rebuild the /config directory correctly.

Any help would be appreciated, thanks.

**Comment by RickyXwang** [comment]
Its' normal that the log sit at  Initialization Sequence Completed, because like it said it is Completed. The next line may be added in a later time.
Example:
STARTING TRANSMISSION
NO PORT UPDATER FOR THIS PROVIDER
Transmission startup script complete.
Wed Nov  4 10:07:50 2020 /sbin/ip route add ****
Wed Nov  4 10:07:50 2020 /sbin/ip route add ****
Wed Nov  4 10:07:50 2020 /sbin/ip route add ****
Wed Nov  4 10:07:50 2020 /sbin/ip route add ****
**Wed Nov  4 10:07:50 2020** Initialization Sequence Completed
**Wed Nov  4 11:07:41 2020** TLS: soft reset sec=0 bytes=8090652819/-1 pkts=9610951/0
Wed Nov  4 11:07:41 2020 VERIFY OK: depth=1, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=ExpressVPN CA, emailAddress=support@expressvpn.com
Wed Nov  4 11:07:41 2020 VERIFY OK: nsCertType=SERVER
