### ISSUE TITLE
3.0 not working on Synology DS718+ while 2.14 is

### ISSUE THREAD

**Issue by gevegest** [haugene/docker-transmission-openvpn#1476]
**Describe the problem**

3.0 version is crashing, while 2.14 is working fine. Please see attached Synology Docker config and UI logs for both 3.0 and 2.14 for details.

**Add your docker run command**

[transmission_config.txt](https://github.com/haugene/docker-transmission-openvpn/files/5505020/transmission_config.txt)
**Logs**

[transmission_3.0.pdf](https://github.com/haugene/docker-transmission-openvpn/files/5505035/transmission_3.0.pdf)
[transmission_2.14.pdf](https://github.com/haugene/docker-transmission-openvpn/files/5505038/transmission_2.14.pdf)

**Host system:**

Docker 18.09.8 on Synology DS718+

**Comment by haugene** [comment]
Hey. This seems to be crashing because you've listed `172.18.0.0/16` as LOCAL_NETWORK. That is the Docker network and will be added by default by OpenVPN.

Also. I would clean up a lot of the TRANSMISSION_ environment variables if you don't actually mean to override them. From version 3 you can just control your settings in the UI if you want. Except from a select handful (see Dockerfile).

Let me know how it goes.

**Comment by gevegest** [comment]
Hi, thanks for the quick help. The container is up and running now. However, i am also running into the #1445 issue like the others.

I will be looking forward to the fix to test. In the mean time i am back to 2.14.
