### ISSUE TITLE
OpenVPN Credentials Not Set after last update

### ISSUE THREAD

**Issue by rbrussell82** [haugene/docker-transmission-openvpn#1497]
After the last update, my container keeps exiting with the error:

```
Using OpenVPN provider: CUSTOM
No VPN configuration provided. Using default.
OpenVPN credentials not set. Exiting.
```

Before the last update (yesterday I think) my config was working fine.  I have it setup with a Custom provider even though I use ProtonVPN.

```
- ${USERDIR}/docker/is-04.protonvpn.com.udp.ovpn:/etc/openvpn/custom/default.ovpn
- OPENVPN_PROVIDER=CUSTOM
```

Within my OVPN file, I have:
`auth-user-pass /config/openvpn-credentials.txt`

The file still exists and has my credentials in it.

**Comment by haugene** [comment]
You have some sort of automation so it fetches and updates the image on each change. Need to narrow down where the error was introduced. The last release is the `3.1` tag, can you try running `3.0` or `2.14` and see if it works there, all else being equal?

If you could post your docker run command or docker-compose file and the complete logs that would be helpful too (there should be a revision printed at the top).

**Comment by haugene** [comment]
:point_up: Any updates, for the next guy? :smile: 
https://xkcd.com/979/

**Comment by rbrussell82** [comment]
> ☝️ Any updates, for the next guy? 😄
> https://xkcd.com/979/

Not really haha.  I tried different versions and it made no change.  Tried different combinations of my compose file.

In the end, I added these variables back and it worked:
```
OPENVPN_USERNAME=****
OPENVPN_PASSWORD=****
```

I had them specified in the openvpn-credentials.txt file instead of within the compose file, which was working before.

**Comment by mrtolkien** [comment]
Upping because I ran into the same issue. Dummy username and passwords fixed it.

Seems like it's a long-standing bug that still needs to get fixed.

**Comment by mmarsalko** [comment]
Just a heads-up, this is still a bug. I could only get Mullvad to connect by manually setting the credentials in the openvpn-credentials.txt file. Setting them in my docker-compose just wasn't working at all.

**Comment by haugene** [comment]
Hmm. The default behavior here might not be excellent 🤔 But the logic is like this:
1. Secrets will be used if they are present, otherwise:
2. If OPENVPN_USERNAME or OPENVPN_PASSWORD is changed from it's default `**None**` value then we assume that you want us to use the env vars as config and write them into the `openvpn-credentials.txt` file.
3. If the env vars are left untouched we use the file you've mounted, or fail if there is no file.

You're not providing a lot of details @mmarsalko, but using Mullvad you're supposed to set OPENVPN_USERNAME=mullvad-user and OPENVPN_PASSWORD=m, ref their [OpenVPN docs](https://mullvad.net/en/help/linux-openvpn-installation):
> In the password field, enter "m".

Did it not work for you with that setup?
