### ISSUE TITLE
Setting update

### ISSUE THREAD

**Issue by eephrati** [haugene/docker-transmission-openvpn#150]
Right now, in order to configure a setting like seeding ratio, you must do it on docker level. That means that when you declare your docker run, you have to add [-e "TRANSMISSION_RATIO_LIMIT_ENABLED=true"]. 

If you try to override that on the settings tab of transmission on your localhost, or even on the settings.json file, the container will override that and go back to the original settings you initially set it up to when you first wrote your container.

Is it possible to globally update the settings whenever it is changed from settings.json, or the settings tab from your localhost?

**Comment by haugene** [comment]
Managing the applications within a container, in this case Transmission, using environment variable is a pattern in containers and will be the default behaviour. For scripting purposes you want to be able to control the state of the application using only `docker run` with environment variables.

But if you're making dynamic changes to it on a regular basis I see that it might be a hassle that it resets every time the container restarts. We can include an option to not generate the settings.json from environment variables. Then all changes would have to be done manually in the json file while the container is stopped (transmission also overwrites the settings when shutting down).

The downside as of now is that we're setting the IPV4 bind address for Transmission based on which IP we've been assigned from the VPN connection. Here: https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/start.sh#L9
This is to prevent IP leaks. But the vpn route should be secure enough anyways, so it's not a very big issue.

**Comment by mimminito** [comment]
Is there a way of pulling in the updated DockerEnv file without removing the container and creating it again?

**Comment by haugene** [comment]
Don't know if you need to remove and create it, or if a stop/start would do the trick. The container reads and persists variables on startup. Question is if Docker will read the DockerEnv on start or just on create...

But there is no way to update an already running container, not from the container side and I think not from Docker environment variables either.

**Comment by haugene** [comment]
As of now the container bases all settings on environment variables. This is done to remove the need for manual steps in set up as well as binding transmission to the IP provided by the VPN provider to prevent IP leaks. If we want two-way binding from the settings used in the GUI one solution could be to check if the settings-file exists on startup and only update the bind IP if it does.

I'm closing this issue for now because the question posed has been answered. If persisting the settings between container restarts is a wanted feature, please raise a new issue with a description of the wanted functionality. I don't think I'll find the time to do it in the near future, but a good description could make it easier for someone else to make an implementation for it.
