### ISSUE TITLE
Firewall 

### ISSUE THREAD

**Issue by klusbert** [haugene/docker-transmission-openvpn#1512]
When ufw is enable the torrent speed is really slow and jumpy.

If I disable the ufw the speed is normal again. My question is:
Is it safe to disable ufw or is it used to act as a killswitch?

**Comment by clement-z** [comment]
### UFW

As it is set up by default, `ufw` only filters input connections, and allows outgoing connections. So when I run `docker exec -it transmission-openvpn ufw status verbose` on my machine I get:

```
root@host ~ # docker exec -it transmission-openvpn ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
8888                       ALLOW IN    Anywhere
9091                       ALLOW IN    172.18.0.1
9091                       ALLOW IN    127.0.0.1
55800                      DENY IN     Anywhere
40682                      ALLOW IN    Anywhere
```

### VPN running

What prevents outbound connections that do not go through the VPN[^1] is that the VPN provider will usually provide configuration files which define routes which take precedence over the default route. Therefore, internet traffic is automatically routed through the tunnel interface. Below is the route as set up automatically on my machine (using PIA). I reordered the routes so that they go from high priority to low priority.

```
root@host ~ # docker exec -it transmission-openvpn ip route
127.0.0.1 via 172.18.0.1 dev eth0
12.34.56.78 via 172.18.0.1 dev eth0
10.39.111.0/24 dev tun0 proto kernel scope link src 10.39.111.11
172.18.0.0/16 dev eth0 proto kernel scope link src 172.18.0.2
0.0.0.0/1 via 10.39.111.1 dev tun0
128.0.0.0/1 via 10.39.111.1 dev tun0
default via 172.18.0.1 dev eth0
```

`eth0` is the docker bridge, while `tun0` is the VPN tunnel.

- `127.0.0.1` is routed through `eth0` so that `127.0.0.1` and `localhost` access the docker host's `lo` device rather than the container's. This will be replaced by whatever you have set up as your `$LOCAL_NETWORK`.
- `12.34.56.78` is the VPN server I connect to, and it is routed through `eth0` as you would expect.
- `10.39.111.0.0/24` is the VPN bridge subnet and goes through `tun0`.
- `172.18.0.0/16` is this container's bridge subnet and goes through `eth0` for communication with clients that access the ports mapped to the docker host.
- `0.0.0.0/1` and `128.0.0.1/1` are two subnetworks which, together, form the entire IPv4 address space. They are routed through `tun0`, meaning that essentially all internet traffic not bound by other rules will use this interface. This is an openvpn "trick" that allows routing all traffic through the tunnel without removing the default route (look for `def1` in the relevant [openvpn manual section](https://build.openvpn.net/man/openvpn-2.5/openvpn.8.html#virtual-network-adapter-vpn-interface)).
- default via 172.18.0.1 dev eth0 is the default route, which is only used when the VPN `def1` route is not present.

Note that no host on the internet has an IPv4 withing the following blocks according to [rfc1918](https://tools.ietf.org/html/rfc1918):

- `10.0.0.0 - 10.255.255.255`  (`10/8` prefix)
- `172.16.0.0  - 172.31.255.255`  (`172.16/12` prefix)
- `192.168.0.0 - 192.168.255.255` (`192.168/16` prefix)

### VPN not running

When the VPN connection fails to connect or has failed, both transmission and the proxy (if enabled) are killed by the [tunnelDown.sh](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/tunnelDown.sh) script (through `openvpn`'s `--down` option (relevant [openvpn manual section](https://build.openvpn.net/man/openvpn-2.5/openvpn.8.html#script-order-of-execution)).

Therefore, there should not be any outbound traffic through `eth0` then, except for VPN reconnection attempts.

I am wondering though whether we should be using `--route-pre-down` instead of `--down`.

[^1]: unless the client accesses port `8888`, or `9091` from the local network)

**Comment by klusbert** [comment]
Thanks for the reply, helped me out!
