### ISSUE TITLE
It is not checked whether transmission actually exited

### ISSUE THREAD

**Issue by clement-z** [haugene/docker-transmission-openvpn#1513]
https://github.com/haugene/docker-transmission-openvpn/blob/93d0141d928ec661411e2c6f0e079aeff2c018dd/transmission/stop.sh#L11-L18

The `transmission/stop.sh` script does not actually check whether `transmission` has exited. This is probably a nitpick, but it would likely be better to safeguard it.

**Comment by RickyXwang** [comment]
Hi, I think `kill -9` (SIGKILL) always works except:
1. Zombie processes cannot be killed since they are already dead and waiting for their parent processes to reap them.
2. Processes that are in the blocked state will not die until they wake up again.
3. The init process is special: It does not get signals that it does not want to handle, and thus it can ignore SIGKILL.
4. An uninterruptibly sleeping process may not terminate (and free its resources) even when sent SIGKILL. This is one of the few cases in which a UNIX system may have to be rebooted to solve a temporary software problem.

SIGKILL is used as a last resort when terminating processes in most system shutdown procedures if it does not voluntarily exit in response to SIGTERM.

If SIGKILL did not work due to one of the above exceptions, I don't think re-sending the signal will do any better.

Please correct me if I am wrong.
https://en.wikipedia.org/wiki/Signal_(IPC)#SIGKILL
https://unix.stackexchange.com/questions/5642/what-if-kill-9-does-not-work

**Comment by RickyXwang** [comment]
Please Ignore my last comment as it basically agrees with your code change, Though Kill -9 was sent in the current code. It's the end of the day my mind is not clear.

**Comment by clement-z** [comment]
Cheers! If you look at the last commit in the PR, you'll see it's the end of the day for me too... :wink:

**Comment by haugene** [comment]
Closing this as #1530 was merged :+1:
