### ISSUE TITLE
Transmission-openvpn 2.14 not working anymore

### ISSUE THREAD

**Issue by SilentRipper** [haugene/docker-transmission-openvpn#1547]
Transmission-openvpn 2.14 not working anymore.
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
TLS Error: TLS handshake failed
SIGUSR1[soft,tls-error] received, process restarting

**Comment by superkrups20056** [comment]
2.14 not working for me either

**Comment by SilentRipper** [comment]
I'm running the 2.14 in rocker on a synology. It wouldn't auto reconnect anymore so I had to restart it manually and it would run for awhile then it just wouldn't start at all. I have the 3.00 docker container running on unraid with no problems.

**Comment by doodie** [comment]
i was having the same issue and after the 10th redeploy, it just started to work. it has also been a few hours between the 9th and 10th attempt at redeploying.

so maybe some sort of timeout helped?

**Comment by superkrups20056** [comment]
I have this same issue. Do you guys think this may be the reason why? Curl was recently disabled...

https://reddit.com/r/PrivateInternetAccess/comments/k0mulx/idea_for_how_to_get_forwarded_port_in_next_gen/

**Comment by doodie** [comment]
gave up on 2.14 and went with :latest. if you do this, make sure to rename the ovpn file to the new convention of using a _ and/or all lowercase.

**Comment by haugene** [comment]
@SilentRipper 2.14 is not working for what provider? If it's PIA it's not that strange as they've changed all their servers. See #1334 
The new PIA configs are only available on the 3.x releases and latest/dev images.

**Comment by steve-spiteri** [comment]
Just for some personal testing, I got 2.14 to launch with PIA by taking the ovpn and certs from latest and putting them in my container. I was just testing something so I can't say how to stable it is.

**Comment by superkrups20056** [comment]
@haugene @steve-spiteri  I moved to 3.2 as a result of this and it seems to work fine but two questions:
1) I am using 8 different PIA servers at random. Should I still set 

OPENVPN_OPTS | --inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
-- | --

2) It seems that parsing .torrent files that are already 100% downloaded, to seed, is _significantly_ slower in this version compared to 2.14. Do you guys see a significant change? Anything I can do to fix it? 

Thanks.

**Comment by haugene** [comment]
1. `--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping` is fine
2. First I'm hearing about it. Don't know why it happens or what you can do to fix it. Interested to hear if you figure it out.
3. It does something. But that depends on what you're comparing it to. If the alternative is to do nothing, then it will set the container to use the DNS you want rather than the one your host is using. If the alternative is to use --dns then the difference is that /etc/resolv.conf way of doing it will directly edit the DNS that is used. When using --dns you're directing Docker to use that DNS for that container. But the contents of /etc/resolv.conf will still be the Docker DNS server because it will still serve you docker internal networking addresses. So if you set resolv.conf yourself the container will not be able to resolve other containers.

**Comment by SilentRipper** [comment]
@haugene Yes PIA. I've tried the latest and the dev still not working. I gave up and just put the VPN on my Synology and installed transmission from community applications now I have to recheck over 7000 torrents.

**Comment by superkrups20056** [comment]
> @haugene @steve-spiteri I moved to 3.2 as a result of this and it seems to work fine but three questions:
> 
> 1. I am using 8 different PIA servers at random. Should I still set
> 
> OPENVPN_OPTS	--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
> 1. It seems that parsing .torrent files that are already 100% downloaded, to seed, is _significantly_ slower in this version compared to 2.14. Do you guys see a significant change? Anything I can do to fix it?
> 2. Does setting the DNS Server(s) in resolv.conf do anything anymore? It seems like it does, but just wanted to double check.
> 
> Thanks.

(2) has been happening since 3.0. I have 16 200 GB torrents and I am on day 4 of the rechecking phase. Only 4 of them are completely done. It's extremely slow. Part of the reason why I moved back to 2.14 was because of this issue.

(3) So if I understand this correctly, setting setting resolv.conf is fine as long as you don't use --dns in the docker compose file? Thanks.

**Comment by nickcraig** [comment]
Exact same issue with me using PIA

`Sun Nov 29 20:49:52 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

Sun Nov 29 20:49:52 2020 TLS Error: TLS handshake failed

Sun Nov 29 20:49:52 2020 SIGUSR1[soft,tls-error] received, process restarting`

I am new to this whole docker thing, anyone have a fix/solution?

**Comment by steve-spiteri** [comment]
> Exact same issue with me using PIA
> 
> `Sun Nov 29 20:49:52 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
> 
> Sun Nov 29 20:49:52 2020 TLS Error: TLS handshake failed
> 
> Sun Nov 29 20:49:52 2020 SIGUSR1[soft,tls-error] received, process restarting`
> 
> I am new to this whole docker thing, anyone have a fix/solution?

If you are still on 2.14 and PIA then you should pull the latest image. PIA moved to next gen servers so you need the latest .ovpn and certs from the new image. tl;dr - if PIA & 2.14, start with the lastest image.

**Comment by haugene** [comment]
I think I'll close this issue. It's been said before and I'll write it as a closing message as well:
**PIA has changed all it's server configs. This project is updated with the new ones so you should pull the latest version of the container and that should work**

If you have any issues other than that. Feel free to create a new issue :smile:
