### ISSUE TITLE
organizr can't talk to transmission

### ISSUE THREAD

**Issue by KevinDenis** [haugene/docker-transmission-openvpn#1571]
Issue has already been mentioned here: https://github.com/haugene/docker-transmission-openvpn/issues/689

I can access transmissionvpn web gui via my local ip address on my PC on the same network.

However my organizr docker running on the same NAS as transmission, can't access the transmission current downloads data using the same IP as I used in the remote connection / browser.

Organizr was working fine when I was using transmission-nonvpn.

**Comment by haugene** [comment]
You're probably running organizr in a different compose file? Then it is added to another docker network and it's denied access of the same reasons that you need to add LOCAL_NETWORK. This is described briefly in the docs, but there is a dedicated page coming to describe the container networking because it's a repeat question here.

If they are in the same docker-compose then you should be able to reach transmission using the service name, let me know if that is not the case. If it is in another network then you need to add that network to the LOCAL_NETWORK list. But make sure that you don't add too wide access, these networks are holes in the VPN to avoid the traffic from getting tunneled.

Docker networks are typically 172.17.x.y and 172.18.x.y etc. You have to find the network that organizr is on and add it. Local netowork list is comma separated.

**Comment by KevinDenis** [comment]
Indeed, organizr and transmission-openvpn are running in separate docker containers.
Finally, the root cause was linkly on the side of
