### ISSUE TITLE
Torrent not seeding

### ISSUE THREAD

**Issue by dmp1ce** [haugene/docker-transmission-openvpn#159]
I cannot download my newly created torrent if I seed using this project. I have tried with PIA and VPN.ht. How can I seed my torrent using a VPN?

If I instead seed on my local network, instead of a VPN, I can seed just fine where others can download.

How can I use this project to seed my newly created torrent?

**Comment by haugene** [comment]
Hmm. At least it is important with an open port so that you can stay visible. Using PIA should fix this for you. Does it set an open port for you using PIA? Can you provide logs?

Also I'm not sure how your trackerless-torrent works, but you probably need to include the IP you're getting through PIA somehow, right? Given that you are the first peer seeding the torrent, where will the second peer look for peers? Haven't really dug into the torrent magic, and trackerless is new to me :)

**Comment by dmp1ce** [comment]
I was able to get some torrents with trackers seeded, but the trackerless torrents are still a not seeding.

PIA did setup an open port correctly. Thank you for your work on PIA!

From my understanding, the bittorrent distributed hash table should be enough to find other peers with torrents using the same hash. I have been successful sharing a trackerless torrent when I'm not behind a VPN, but sometimes it takes hours. I also don't understand the torrent network well enough to know where the problem is. Maybe it is a problem with the way Transmission is implemented.

Anyway, I don't think there is anything that can be done with this project, so I'l go ahead and close. Thank you again.
