### ISSUE TITLE
Image tag 'latest-armhf' missing?

### ISSUE THREAD

**Issue by thijskaspers** [haugene/docker-transmission-openvpn#1591]
I can no longer pull the image using the `latest-armhf` tag. It's missing from the dockerhub.

The `docker-compose-armhf.yml` still points towards it, so this could throw people off. Could you push the latest tag again?

**Comment by haugene** [comment]
Aha, we still have the `docker-compose-armhf.yml` file. I've missed that.

Yes. I have deleted the latest-armhf tag because it will no longer be updated. As of version 3.1 the build now produces a multiarch manifest that has an amd64, armv7 and armv8 version. The correct image will be chosen based on the hardware you are running Docker on.

So change it for just `:latest` and it should work again. I will delete the `docker-compose-armhf.yml` from the repo.

**Comment by thijskaspers** [comment]
Ah thanks for the clarification haugene! Does this count for the `proxy` container as well? That one still has the `latest-armhf` tag I see.

**Comment by haugene** [comment]
It doesn't (yet). I saw that when I deleted it now. I'll give it a go now. They will become multi-arch as well.
It has been requested before in #1483 and I suggest we follow up there and close this for now?

**Comment by thijskaspers** [comment]
Thanks! Will do 👍
