### ISSUE TITLE
Post-Start Script fails to chmod another script file

### ISSUE THREAD

**Issue by ptrsmk** [haugene/docker-transmission-openvpn#1612]
**Before creating this issue I have:**
- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section
- [X] Tried to add as much relevant information to the issue as possible

**Describe the problem**
I have a script at /scripts/transmission-post-start.sh. It executes and is recorded in the log.  All that the script contains is a line to chmod another script file.  Unfortunately, chmod fails with a log recording "No such file or directory".

The idea is to get the post-start script to chmod the "torrent done" script, because the "torrent done" script isn't running.  I was following advice in another issue by creating the torrent done script to simply echo to a text file to verify it was being triggered.  It's not, and it was suggested that chmod-ing the torrent done script might resolve the issue.  That's what brought me to this point.

**Add your docker run command or docker-compose file**
![image](https://user-images.githubusercontent.com/6360014/102508276-34f70800-4053-11eb-9df7-e8a046b8937f.png)
![image](https://user-images.githubusercontent.com/6360014/102508486-6f60a500-4053-11eb-9aac-0e1f765a74fa.png)

**Logs**
Executing /scripts/transmission-post-start.sh
/bin/bash: chmod +x /scripts/transmission-post-stop.sh: No such file or directory
/scripts/transmission-post-start.sh returned 127

**Host system:**
Running Docker 18.09.0-0513 on a Synology DS218+.

**Comment by clement-z** [comment]
> I was following advice in another issue

Can you link to the other issue you referred to?

Otherwise:
* Please include the full log and docker configuration (including mounts)
* What are the contents and permissions of the `/scripts` folder? (run `ls -la /scripts` in the docker console)
* By default, `transmission-post-stop.sh`, if it exists, is executed after transmission shuts down. This is probably not what you want to name your script...
* Your `transmission-post-start.sh` is executable?... Why would you think you cannot do the same with your `torrent-done.sh` script (just `chmod +x` on the host ?)
