### ISSUE TITLE
curl: (60) SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by Hanyoro** [haugene/docker-transmission-openvpn#1738]
`Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.NoPnPH
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.`

My container restarted and now this is happening. I do not know how to fix it.

I don't understand why this container breaks every month.

**Comment by felix4643** [comment]
Not a problem that's caused by the Container. PIA let their SSL Certificate expire.

**Comment by Hanyoro** [comment]
Is there an ETA on this getting fixed on PIA's side? The VPN works everywhere else?

**Comment by Hanyoro** [comment]
You're right... not even their website works... https://www.privateinternetaccess.com/

**Comment by felix4643** [comment]
The docker image automatically downloads the latest openvpn configuration files from the PIA website on each restart. And since their SSL certificate expired CURL throws an error. If you want a temporary fix you could just setup a custom configuration like it's described [here](https://haugene.github.io/docker-transmission-openvpn/supported-providers/#using_a_custom_provider).
