### ISSUE TITLE
Watchdog that would restart container or openVPN if connection lost for certain period of time. 

### ISSUE THREAD

**Issue by amikot** [haugene/docker-transmission-openvpn#1747]
Every day I discover that container lost it's internet access.
`curl ifconfig.me` displays error, as ping to any address as well.
It's probably OpenVPN issue itself. I think so, because I had that problem also when was running OpenVPN on the router (not by docker). Every day gateway was discovered as not responding. 

I would suggest add watchdog option that in case of error would restart whole container. 

Alternatively it could be solution that I used on router - simple watchdog based on cron that in case of lost connection  was killing and relaunching OpenVPN client.

**Comment by haugene** [comment]
Up for discussing improvements. Any suggestion for implementation?

And you have read this? https://haugene.github.io/docker-transmission-openvpn/faq/#container_loses_connection_after_some_time

**Comment by reticle5** [comment]
The "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" always caused the container to stop (and then be restarted with my docker-compose configuration of restart=unless-stopped) under the Ubuntu image. I've never seen it work however since the move to the Alpine image. I've also been investigating this, but so far no joy, since every now and again the router my server is connected to will blip and the container will hang rather than restart.

**Comment by mustanggb** [comment]
I think the options are:

1. Pass config to OpenVPN - This is my current `OPENVPN_OPTS`, and still not reliable `--inactive 3600 --ping 10 --ping-exit 60 --remap-usr1 SIGTERM --reneg-sec 0 --pull-filter ignore ping --pull-filter ignore ifconfig-ipv6`.

2. Use autoheal - Does seem to do the job so far, but it would be nice not to have a rely on a separate container.

3. Replicate autoheal - Essentially something like autoheal built-in. The issue with this is autoheal works by monitoring the health status, which requires passing the docker socket into the container, probably not something we want to risk in this instance.

4. Replicate HEALTHCHECK with exit-on-unhealthy functionality - Rather than getting the health status from docker figure it out ourselves inside the container.

So assuming that (4) is the kind of route worth pursuing this is my suggestion for implementation:

- New `/etc/scripts/selfheal.sh` file.
- New environmental variables `SELFHEAL=true`, `SELFHEAL_INTERVAL=1m`, `SELFHEAL_TIMEOUT=30s`, `SELFHEAL_START_PERIOD=0s` and `SELFHEAL_RETRIES=3` that replicate the HEALTHCHECK options.
- Have the selfheal script run permanently in the background, using the provided variables emulate how HEALTHCHECK works and figure out the health status, if it becomes unhealthy I suspect we can't restart the container from within, so exit and rely on the restart policy to bring it back up.

@haugene (and anyone else): Thoughts?

**Comment by mustanggb** [comment]
Opened pull request #1805 to implement the above.

**Comment by pkishino** [comment]
fixed by #1805
