### ISSUE TITLE
Port forwarding not available for this region (PIA)

### ISSUE THREAD

**Issue by 3ex3** [haugene/docker-transmission-openvpn#177]
I get this message for all PIA regions except the default (Netherlands) when starting the container:

```
STARTING TRANSMISSION
STARTING PORT UPDATER
Transmission startup script complete.
Fri Dec 30 20:00:00 2016 Initialization Sequence Completed
Generating new client id for PIA
PIA returned an error: "error":"Port forwarding not available for this region"
```

This is the command I use to start the container:

```
docker run --privileged --name transmission -d --restart always --dns 8.8.8.8 --dns 8.8.4.4 -p 9091:9091 -v C:\Users\3ex3\Transmission:/data -e "OPENVPN_PROVIDER=PIA" -e "OPENVPN_CONFIG=US California" -e "OPENVPN_USERNAME=username" -e "OPENVPN_PASSWORD=password" -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" haugene/transmission-openvpn
```

Running with Docker for Windows/Hyper-V. Does anyone know what I'm doing wrong?

This may or may not be related, but I've also been getting a lot of these warnings lately:

```
Fri Dec 30 21:00:00 2016 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #74251 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```

**Comment by haugene** [comment]
Does it continue to print the same message for all subsequent calls to PIA? It should make a new attempt every hour. This sounds like a PIA issue, since it's working in one region and all. There is a thread for this on PIAs forums where a user has posted [something similar](https://www.privateinternetaccess.com/forum/discussion/comment/41405/#Comment_41405).

The container is also using the "up" script part of openvpn to initiate Transmission and port updating. As of now I don't have time to investigate this, but if someone's up for it that post is somewhere to start. Should also test if you're able to run the script manually inside the container and if that works any better. Remember to pass the local_ip argument (you can read it in the logs), ie `./updatePort.sh <local_ip>`.

The replay warnings are not related, [see here] for more info on what it might be. If you add `--mute-replay-warnings` to your OPENVPN_OPTS you'll stop them spamming your logs.

There was an update of the portUpdate script in relation with issue #167. You could try to pull the 1.14 tag of the image instead of latest. If it works then it could be introduced by script changes.

**Comment by haugene** [comment]
I'll close this now. Re-open if you have more info or if you hear anything from PIA.
