### ISSUE TITLE
Custom Download/Incomplete/Watch file paths

### ISSUE THREAD

**Issue by nobbylark** [haugene/docker-transmission-openvpn#1772]
## Before creating this issue I have:

- [X] Read through the pinned issues for related problems
- [X] Searched for [similar issues](https://github.com/haugene/docker-transmission-openvpn/issues)
- [X] [Read the documentation](https://haugene.github.io/docker-transmission-openvpn/). Especially the troubleshooting section and FAQ
- [X] Tried to add as much relevant information to the issue as possible
- [X] Verified I have tried using newest release as well

Hi

I'm new to docker, but i am trying to add custom file paths for downloads/incomplete/watch folders. I used the default file paths, but i was running in to sync issues with Synology Drive (which is key), so my theory is there may be some conflict with the /data file path and keeping them separate may resolve my syncing issues.

I have set the following Volumes up, thinking it would work, but it hasn't:

docker/transmission-openvpn/TransmissionVPN:/data
Torrents/Completed:/downloads
Torrents/Pending:/incomplete
Torrents/:watch

Enviornment:

TRANSMISSION_DOWNLOAD_DIR:/Torrents/Completed
TRANSMISSION_INCOMPLETE_DIR:/Torrents/Pending
TRANSMISSION_WATCH_DIR:/Torrents

I hope that is enough info, but let me know if you need anything else.

Many thanks
Jay

**Comment by haugene** [comment]
The file system inside the container is separate from the one on your host. So if you tell Transmission to use /Torrents/Completed you have to mount a host folder to that location in the container. What you've done is to mount your folder (which has that name) into /downloads in Transmission.

If these are your mounts:
```
docker/transmission-openvpn/TransmissionVPN:/data
Torrents/Completed:/downloads
Torrents/Pending:/incomplete
Torrents/:/watch (<- note I prefixed with /, it wasn't an absolute path before)
```
Then this has to be your environment:
```
TRANSMISSION_DOWNLOAD_DIR:/downloads
TRANSMISSION_INCOMPLETE_DIR:/incomplete
TRANSMISSION_WATCH_DIR:/watch
```

That's the principle here. But... I'm not sure how this will play out because you've mounted the Torrents/ root folder as /watch, but then you've mounted sub-folders of that (for example Torrents/Completed) to /downloads. 

It might work, I'm not sure. My head hurts a bit when I think about it :sweat_smile:  but I don't think it's pretty. Maybe keep them as siblings instead?

Mounts:
```
Torrents/Completed:/downloads
Torrents/Pending:/incomplete
Torrents/Watch/:/watch
```

Environment:
```
TRANSMISSION_DOWNLOAD_DIR:/downloads
TRANSMISSION_INCOMPLETE_DIR:/incomplete
TRANSMISSION_WATCH_DIR:/watch
```

**Comment by nobbylark** [comment]
Perfect. I tried the below and it worked:

Mounts:

```
Torrents/Completed:/downloads
Torrents/Pending:/incomplete
Torrents/:/watch
```

Environment:

```
TRANSMISSION_DOWNLOAD_DIR:/downloads
TRANSMISSION_INCOMPLETE_DIR:/incomplete
TRANSMISSION_WATCH_DIR:/watch
```

I'm still having problems with the folder syncing with Synology Drive. I have set them up correctly in the admin console and the folder has the correct sharing priveledges - not sure if you have come across this issue before?

**Comment by haugene** [comment]
Glad it worked :+1: 
Don't have a Synology and can't say that I've seen any issues on this. First time I'm hearing about Synology Drive.

I guess we can close this?

**Comment by nobbylark** [comment]
Yeah, no problem Haugene - close it out and I'll take my query to the Synology subreddit.

Thanks a lot for your help!
