### ISSUE TITLE
latest vs dev docker tag

### ISSUE THREAD

**Issue by ksurl** [haugene/docker-transmission-openvpn#1774]
### Is your feature request related to a problem? Please describe.

Using the latest tag unexpectedly uses the latest commit to master. Usually it means the latest stable release in the context of other projects (as shown in github releases)

### Describe the solution you'd like

change the build workflow to tag latest on stable releases and use a new tag for latest commit such as "dev" or "beta" or "master"

### Additional context

it is confusing when using an autoupdater like watchtower when the sha hash of the image does not match the hash of the latest release.

**Comment by haugene** [comment]
It is not a bad idea, latest is an inherently flawed tag in the Docker ecosystem because you have no guarantee that :latest on your machine is actually the latest of anything. If you pulled it a year ago, :latest is still a year old.

That being said I think there is a strong convention to tag the latest build of master as `latest` and I think there's an argument to be made that those who are familiar with docker will expect that. So maybe we should create a new tag called "release" or "stable" or something. Although there is nothing that guarantees that a tagged release is more stable than the latest build on master. We try to test code before we merge it, but it's the users that find the bugs and report them after the fact.

I'm up for a discussion on tag naming, and either way it should probably be listed briefly in the README.

About the hash of the image being the same as the git sha hash, that's just not possible I'm afraid. Docker hashes the images based on content. We do tag the images with sha release though, so you should be able to see it in watchtower I guess (never used it).

**Comment by ksurl** [comment]
sorry I meant comparing the docker image hash on docker hub to the local image when you compare for example 3.6 and latest if there are commits newer than 3.6. of course the git hash will be different since it's just text files not a monolithic docker image.

This is very low priority, so I am fine with leaving it as is. or using another tag for the 'released' versions.

**Comment by haugene** [comment]
Aha. I understand. You compare the sha of the image you have locally and don't see it in the list of tagged released docker hub images? And then it's just a build of the latest commit on master?

Anyways. Let's agree that it's low priority but again I don't think it's a bad idea. There's other stuff going on right now so I'll just leave this open for now. Maybe others will chime in with their opinion or maybe the stale bot will ping on this in 2 months.
Either way I think that a short description of tags could be good quite early in the docs and possibly even on the main page. There are many users of this image that are very new to Docker and I think that the understanding of the tags and the ability to backtrack versions to pinpoint bugs is not obvious to everyone. When someone has a problem and can say that it happened between 3.2 and 3.3 it helps us a lot. So versioning could be promoted :smile:

**Comment by planetrocky** [comment]
I think the idea of a "release" tag would be great; I've pulled "latest" a few times over the years and suddenly had a container that stops working for various reasons.
