### ISSUE TITLE
Transmission Worked Great Until Update

### ISSUE THREAD

**Issue by gdreelin** [haugene/docker-transmission-openvpn#1775]
Ok not sure what happen, Transmission was working great until the other day an update came out for UnRAID docker and now it is started but no access to WebUi now. It even shows down in Sonarr and Radarr now. I tried deleting it and reinstalling it but no joy there either. Still same thing with web access not showing.  This has been working flawlessly for months now and that update killed it.

**Comment by haugene** [comment]
First of all, you are completely ignoring the issue template that it is clearly stated that you should use. Secondly you're basically saying that it used to work and now it doesn't which doesn't really give us anything to work with - does it? And you even point to a culprit being an update for UnRAID docker package which is not managed here.

I'm not familiar with UnRAID, but I guess you can specify the version of the image to use. I suggest you work your way backwards from 3.6 (current release) down to 3.5, 3.4, etc until you find a version that works. That way you can help pinpoint when this error occurred. And you have to provide logs. Without it we don't know anything about what's going on.

**Comment by gdreelin** [comment]
Sorry new at the posting issues on here. I checked the logs after doing a reboot and nothing is showing up. 
Here are the settings on UnRAID and it shows it is pulling from your Github as installed docker from the app store. I am not sure if you can go back down there looks like no way to do that. Nothing has changed in the settings but update the came out like Sun or Mon night.  The first two images show the docker up and running but cannot reach the WebUI.

![Docker Page](https://user-images.githubusercontent.com/802649/111390639-6f3f6800-8689-11eb-9b34-8f3912247ec1.png)
![Page](https://user-images.githubusercontent.com/802649/111390638-6f3f6800-8689-11eb-9073-596916caedd5.png)

These are the settings

![Untitled](https://user-images.githubusercontent.com/802649/111390198-b842ec80-8688-11eb-9146-8a3f6e852c05.png)
![Untitled1](https://user-images.githubusercontent.com/802649/111390199-b842ec80-8688-11eb-919b-78bd0eb4d824.png)
![Untitled2](https://user-images.githubusercontent.com/802649/111390200-b8db8300-8688-11eb-8397-a0b291000f5e.png)
![Untitled3](https://user-images.githubusercontent.com/802649/111390201-b8db8300-8688-11eb-84d7-b730b3e81991.png)

**Comment by haugene** [comment]
Hmm. None of this is the logs, and you really should be able to see them somewhere. If you could get them that would be great, because it seems you're running on the :dev version and knowing what's wrong there could help me solve it. I did merge something in there about 24 hours ago.

If you change the `haugene/transmission-openvpn:dev` you've circled to `haugene/transmission-openvpn:3.6` that might solve the problem for now. But if it does I would be really happy if you would set it back to `dev` and try to find those logs.

You should at least be able to get them by ssh'ing into the host and doing `docker logs <container>` if you don't know the container name use `docker ps` to find it. Or `docker ps -a` if it has died.

**Comment by gdreelin** [comment]
Yeah I saw the :dev part and was curious about that. Not sure the person the developed the docker made a way to change it. I attached what comes up as the logs for it. I looked down into the file structure to see if I could find one there but found there is no container that has transmission in it like it did before. It is gone now. On UnRAID it would  put the contains into a folder called "appdata" but it is the only docker container I do not see. I am wondering if it did not reinstall the container right. 

[logfile.txt](https://github.com/haugene/docker-transmission-openvpn/files/6153108/logfile.txt)

**Comment by gdreelin** [comment]
Ah ha!! You were correct. I found where to replace the :dev with :3.6 and it loaded correctly with all the container. So back up and working again. Thanks for the second pair of eyes.

**Comment by pkishino** [comment]
I would really like to know @gdreelin how you, even as a first time poster, completely missed the issue template instructions ??
We are trying to make it as easy and clear for people to post issues and for us to fix..thats what the template is for.. we are also trying to get a bot working that will close all issues not following the template..
so please comment on WHY and HOW you missed the CLEAR instructions in the template on what to do and fill in.. I can't see how much clearer to write: USE THE TEMPLATE

**Comment by pkishino** [comment]
Sorry, but your platform is irrelevant to following the template.. the template clearly asks for what you have done, what things you have tried to do (e.g try other releases etc etc) which are all useful for us to help debug , you obviously have a configuration as you pasted the screenshots and you also posted some logging.
That you’re using unraid has nothing to do with above, you worked obviously mention it in the description and platform details but otherwise I clearly don’t see this as anything other than thinking that you are special and don’t need to use the template...
At least this has encouraged me to look more into getting the auto close bot working for issues like this
