### ISSUE TITLE
ModuleNotFoundError: No Module Named 'ufw'

### ISSUE THREAD

**Issue by fasteasyfree** [haugene/docker-transmission-openvpn#1807]
```
Starting container with revision: 416541016b9b30149d8fcb56abe2bc325db4904b
Creating TUN device /dev/net/tun
mknod: /dev/net/tun: File exists
Using OpenVPN provider: PIA
Provider PIA has a custom setup script, executing it
Downloading OpenVPN config bundle openvpn into temporary file /tmp/tmp.NnlLLH
Extract OpenVPN config bundle into PIA directory /etc/openvpn/pia
4 servers found in OPENVPN_CONFIG, netherlands chosen randomly
Starting OpenVPN using config netherlands.ovpn
Modifying /etc/openvpn/pia/netherlands.ovpn for best behaviour in this container
Setting OpenVPN credentials...
enabling firewall
Traceback (most recent call last):
  File "/usr/sbin/ufw", line 25, in <module>
    import ufw.frontend
ModuleNotFoundError: No module named 'ufw'
```

Recent issue, as Monday (12th) everything was fine.

**Comment by pkishino** [comment]
As you didn't follow the template annoyingly I have no idea which version you are running ...

**Comment by joe-eklund** [comment]
I ran into the same issue. Looks like the dev branch has fixed it and I am running dev until it gets pushed to master. @fasteasyfree try running the `dev` tag.

**Comment by fasteasyfree** [comment]
> I ran into the same issue. Looks like the dev branch has fixed it and I am running dev until it gets pushed to master. @fasteasyfree try running the `dev` tag.

Excellent, thank you joe.

**Comment by pkishino** [comment]
well, considering master is still running on alpine (and ufw is working on it, I'm still using this build on my main machine) and dev is running ubuntu.. it's a bit unclear here where ufw is missing.
The whole point of the issue templates is to make things easier and quicker for us to debug and provide info for others as well when they search. 
Recommending people to switch to dev tag isn't really a good idea as 
a) dev is just that, in development state and possibly unstable, causing potential unnecessary issues for users etc
b) is bad practice as a better first step would be a rollback to previous working version
c) makes it harder for us to fix as then, instead of helping out to find the issue, users will just ignore and move on..

sigh..

**Comment by pkishino** [comment]
as per
https://github.com/haugene/docker-transmission-openvpn/blob/master/Dockerfile
ufw is included
and below
https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh
is where it's used
and this is working just fine on master build of :latest

**Comment by pkishino** [comment]
please move any ufw discussion to #1816
