### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by be-stranger** [haugene/docker-transmission-openvpn#205]
Hello everyone,

I am a docker noob, when I run the following docker command on a mac, it running and reports a what looks like hash and then it quits to the terminal prompt, what am I doing wrong?

I can get other dockers to work, just not this one. 

docker run --privileged  -d \
-v /Users/home/torrents:/data  \
-v /etc/localtime:/etc/localtime:ro \
-e "OPENVPN_PROVIDER=PIA" \
-e "OPENVPN_CONFIG=AUTO” \
-e "OPENVPN_USERNAME=username” \
-e "OPENVPN_PASSWORD=password" \
-p 9091:9091 \
haugene/transmission-openvpn

I have also read that becuase I am on a mac I need an extra line to connect to the webgui, where do I add that?

**Comment by haugene** [comment]
It's supposed to just return a hash (the container id) and then run in the background. You can see if it's running by typing `docker ps`. If it's not running, check `docker ps -a` and then get the logs `docker logs <container name | id>` so that we can see what's wrong with it.

If you're running docker for mac you can follow the instructions in the readme as usual. If you're running boot2docker, docker is not running on your mac directly but in a VM. Because of this you need to access the webui on the VM IP instead. And if you want it accessible from outside your host you must configure port forwarding from your host to that VM.
