### ISSUE TITLE
new provider

### ISSUE THREAD

**Issue by jdbrouwer** [haugene/docker-transmission-openvpn#228]
hello, is it possible to add mullvad as a provider?

The config file contains everything that is required to setup the VPN. (including authentication).

see: https://mullvad.net

**Comment by haugene** [comment]
Hey.

If their .ovpn files contains authentication like AirVPN and ExpressVPN(see #60 and linked issues) then we can't add it to the repo because it would be tied to a specific user. You then need to follow the description for using a custom provider. It's in the readme.

Good luck. Feel free to reopen if you have more questions or if you have a link to ovpn-files I can add (given that they don't include your authentication)
