### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by nicomarti83** [haugene/docker-transmission-openvpn#242]
HI,
I had a container working like a charm, but I decided to update my qnap system to 4.3.3. Since I have an error message on startup.

> Sun Apr 30 20:41:07 2017 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)                                                             
Sun Apr 30 20:41:07 2017 Exiting due to fatal error

I tried to build a new container with or without env file but I had the same error each time

I use this command line to start the container without env file:
`docker run --privileged  -d -v /share/Download/:/data -v /etc/localtime:/etc/localtime:ro -e "OPENVPN_PROVIDER=xxxxx" -e "OPENVPN_CONFIG=xxxxx" -e "OPENVPN_USERNAME=xxxxx" -e "OPENVPN_PASSWORD=xxxxx" -p 9091:9091 haugene/transmission-openvpn`

and this one with the env file:
`docker run --privileged -d -v /share/Download/:/data -v /etc/localtime:/etc/localtime:ro --env-file /share/homes/xxx/docker-transmission.env -p 9091:9091 --name=transmission-openvpn haugene/transmission-openvpn`

pleaassssseeee help meeeeeee :(

**Comment by haugene** [comment]
The container is using the TUN/TAP device of the host, which it gets access to with the `--privileged` flag. Since it now says that there is no such device it has probably gotten lost during the update.

Setting up the TUN/TAP depends on your host, but it's somewhat described in the readme. Usually the simplest solution is to install (don't need to run) an OpenVPN package or similar which will set up the device for you.

**Comment by haugene** [comment]
Glad to hear it. Np :)

**Comment by ziomik** [comment]
Sorry if I reopen this closed topic, but I have the same problem but I don't solve by installing any VPN APP in my QNAP. Is someone kind enough to give me more details? Thank you
