### ISSUE TITLE
Auto building a new release isn't occurring (maybe I'm presumptive of the new configuration, new Transmission is out..)

### ISSUE THREAD

**Issue by derekcentrico** [haugene/docker-transmission-openvpn#2848]
### Is there a pinned issue for this?

- [X] I have read the pinned issues and could not find my issue

### Is there an existing or similar issue/discussion for this?

- [X] I have searched the existing issues
- [X] I have searched the existing discussions

### Is there any comment in the documentation for this?

- [X] I have read the documentation, especially the FAQ and Troubleshooting parts

### Is this related to a provider?

- [X] I have checked the provider repo for issues
- [X] My issue is NOT related to a provider

### Are you using the latest release?

- [X] I am using the latest release

### Have you tried using the dev branch latest?

- [X] I have tried using dev branch

### Docker run config used

N/A

### Current Behavior

Currently, the release has not been updated to include the latest Transmission (4.0.6).  I was going to open a PR to push an update to the latest tar.gz from the Transmission github release page.  The new code for this project appears to have a set of tasks that query for the latest Transmission and update accordingly.  https://github.com/transmission/transmission/releases/tag/4.0.6

### Expected Behavior

Based upon my understanding of the new workflows that I just skimmed it would make sense that something should be triggering a new release to build auto-magically with the latest Transmission since there is no longer a reliance on manually editing the tar.gz path and building from there.  https://github.com/haugene/docker-transmission-openvpn/blob/master/.github/workflows/check-transmission-releases.yml

### How have you tried to solve the problem?

N/A 

### Log output

N/A

### HW/SW Environment

```markdown
N/A
```

### Anything else?

Happy to help with PRs when I can.   Not sure how to be of value in this instance.

**Comment by ilike2burnthing** [comment]
The `Transmission Version Check` action only runs on dev branch, and if a new build is found then a commit is made to dev, which then _should_^ trigger the `Transmission Builds` action, again only on dev.

Any commits subsequent to that, on master or dev, will cause the `Image Builds` action to build a new image with our latest Transmission build, with a commit on the master branch going to the `edge` image, and dev going to `dev` (surprisingly).

---

^ _this is due to be updated in https://github.com/haugene/docker-transmission-openvpn/pull/2843 to work properly_

**Comment by derekcentrico** [comment]
Gotcha.  Closing this thread.  I just thought it would have promptly built and released a new build w/ latest Transmission.
