### ISSUE TITLE
Setting up SSL for the web UI

### ISSUE THREAD

**Issue by niXta1** [haugene/docker-transmission-openvpn#290]
Hi!

What's the best way to add certs and only allow SSL to the nginx proxy?

**Comment by niXta1** [comment]
I ended up with this nginx.conf:

`events {
  worker_connections 1024;
}

http {

  server {
    listen 8080 ssl http2;

      # SSL
      ssl on;
      ssl_certificate /etc/nginx/X.crt;
      ssl_certificate_key /etc/nginx/X.key;
	  server_name X.com;
      ssl_session_timeout 30m;

      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_prefer_server_ciphers on;
      ssl_ciphers AES256+EECDH:AES256+EDH:!aNULL;

    location / {
      proxy_pass http://transmission:9091;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      
      # HTTP 1.1 support
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}`

But it's not working perfectly, sometimes I get an 409 error:
`409: Conflict

Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: XXX`

**Comment by matthewmcpartland** [comment]
Hey there, SSL is something I've been looking to add because otherwise using the web ui could be quite the security leak.

I've been planning to follow this guide [https://blog.flo.cx/2014/03/adding-ssl-to-transmissions-web-interface/](url) so maybe looking there you might find some difference in the nginx.conf file that get it to work.

Is it possible you could explain how you set this up and modified the nginx.conf? I don't really know where to start since I don't normally use docker

**Comment by niXta1** [comment]
Sure, I'm trying to work out some kinks but it seems to not be SSL related.
I'm getting an X-Transmission-Session-Id: blabla error after some time. I'll get back to you when I got something stabile.

**Comment by haugene** [comment]
I've seen this before. Using the URL `.../transmission/web` will give a 409 while `.../transmission/web/` works fine.
