### ISSUE TITLE
Can I route other containers through the VPN?

### ISSUE THREAD

**Issue by DAMaas** [haugene/docker-transmission-openvpn#314]
Hey,

Is it possible to for example also route sabnzbd, jackett and maybe others through the vpn container so that the other containers are also protected by a vpn?

**Comment by haugene** [comment]
Yes, you can. It's a default feature of Docker using the  `--network` option as described [here](https://docs.docker.com/engine/reference/run/#network-settings).

Basically you can set `--network container:transmission` and all the traffic will go through your transmission container.

**Comment by cawith** [comment]
Very good.
BTW, why is jandrews377's commit 0877052 from June 23rd (the web proxy) not in the master?

**Comment by haugene** [comment]
Hmm. Various reasons. First of all it hasn't been completely integrated with the UFW feature so I was hoping to fix that first. Then I've kind of put this project aside for a while, so not much has happened in general.

Then there's the issue of if we want to add the web proxy into the container. There already exist web proxy containers, and using the container networking mode I described in the last post, you can still get the proxy behind VPN. Containers are "supposed to be" single purpose and adding more applications inside one image is not the container-way of doing things.

But! A proxy is a neat feature, we can make it an opt-in option, and it would probably be preferred by many instead of doing the linked-container-setup. I've now pushed a lot of changes to master, making room for tweaking on the firewall vs proxy on the dev branch - hopefully it's on master soon :)

**Comment by cawith** [comment]
Thank you very much for your in-depth answer!
As you said, it would be a neat feature, but I'll also be able to manage with linking the containers to yours.
Would still be cool to have the possibility, as it would make the setup of associated containers easier to understand (at least in my mind, but I'm still new to Docker).

Thanks anyway for your hard work! :)

**Comment by whisperdancer** [comment]
Yes, you can. It's a default feature of Docker using the --network option as described here.

Basically you can set --network container:transmission and all the traffic will go through your transmission container.

How can I accomplish this using docker-compose?

**Comment by pkishino** [comment]
check bottom, existing network
https://docs.docker.com/compose/networking/
