### ISSUE TITLE
Syntax error: newline expected

### ISSUE THREAD

**Issue by CoderKiwi** [haugene/docker-transmission-openvpn#339]
Hi,

I'm having an interesting error when first running the program through Docker on a Synology NAS running the latest DSM. I have gone through the proper steps outlined in the readme to configure for Synology (i.e. TUN.sh), and I've correctly entered credentials and such to connect to ExpressVPN. This has worked before on the server but I'm not sure what changed.

It appears to be some sort of syntax issue when running the startup scripts regarding the environment variables.

Logs:
![transmission](https://user-images.githubusercontent.com/33564041/32686346-4f88df76-c708-11e7-9a8c-63476ac5eb0a.png)

Environment variables:
![screen shot 2017-11-11 at 5 53 05 pm](https://user-images.githubusercontent.com/33564041/32686415-67bafcf4-c709-11e7-9507-285440123866.png)

Any ideas on this? Thanks

**Comment by CoderKiwi** [comment]
@haugene ?

**Comment by rcork** [comment]
I had this same problem. I think it's because in the default Environment Variables there are two that do not have a default value:

TRANSMISSION_PEER_CONGESTION_ALGORITHM= 
TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME= 

Synology wouldn't let me save the config with the missing variables so at first i just deleted them. I think that is what led to the Newline error and the fatal exit of the docker container. Instead i just put the dummy values in those two variables and then the config saves and the container starts up as usual.

**Comment by CoderKiwi** [comment]
Oh, of course! Thank you for the response. I got it working by setting things to false and deleting TRANSMISSION_WEB_HOME. Beforehand I was just deleting them all...

@haugene it may be a good idea to set default values for these environment variables to make it more robust to noobs like me. The other variables have default values but a few others don't.

**Comment by haugene** [comment]
I see. This works fine on a server install, but the NAS installations seem to have this issue #335.
Just worried that if I set "" as the value, it's going to be escaped and end up as "\"\"" somewhere, which is not what we want.

But we'll never know if we don't try. Adding default values now and we'll see if new issues arise :)

**Comment by rcork** [comment]
Or you could just set them to the default values. For congestion I think it's "cubic". For the script filename, it could be any filename since the enable flag is False.

**Comment by haugene** [comment]
I set them both to "" now, and it works fine here. But thanks for the input, will use those values if we get trouble :) New release (1.18) is building now and will be available soon. Would be nice if you could verify that it works.

**Comment by rcork** [comment]
Unfortunately it didn't help. Synology apparently feels that if you have an environment variable defined, its for a purpose and should be set to something. it can't be blank or "". So I had to put in a value for congestion, done script, PUID and PGID and I had to delete the web home variable. After that it works. For some strange reason, I couldn't just delete all of them because the next time you open up the configuration, Synology puts them back in since they are part of the docker image. So either they need to have an actual value, they need to be left out and added in as needed, or in the Synology NAS section of the instruction, reference the changes that are needed to get it to work.

**Comment by haugene** [comment]
We can set default values for most of them, but from the transmission documentation the congestion and done script has default value `""` and I think we should let that be and document necessary steps for Synology instead. I'm not using Synology so I wanted to check if the instructions still are relevant?

Is the description in the README the best way to do it or is it a simpler way to set it up without the manual steps? If we're updating it, we should make it right. Do you have any suggestions for a setup-text? Either submit it as a pull-request or post it here and I can add it.

**Comment by rcork** [comment]
I think the README would suffice for Synology specific changes needed. I'll writeup a Synology specific instruction and submit a pull request later this week.
