### ISSUE TITLE
Transmission with SlickVPN

### ISSUE THREAD

**Issue by Romijn** [haugene/docker-transmission-openvpn#341]
Hi,

First of all thanks for this docker package, I've been fiddling around with it for awhile now, I have Transmission running (Synology) with SlickVPN Netherlands, I can access the webpage, but for some reason it doesn't want to download. In the trackers I see:

Tier 1
http://tracker.trackerfix.com:80
Announce error: Could not connect to tracker - Today 04:13:39 PM

Okay so it won't connect.

Tier 2
udp://9.rarbg.me:2710
Last Announce: Today 04:13:44 PM (got 30 peers)

It does connect  to this one but still it's not downloading much.

Does this have anything to do with my router? Or is there something else I'm missing? Without VPN normal transmission is actually working, so it has to be VPN related.

**Comment by haugene** [comment]
Hmm. Not sure what's causing this, but I doubt it's your router. The traffic is tunneled with VPN through your router, so the router settings shouldn't change anything.

When it's a question of connectivity I always ask if you've set DNS servers in the container? Don't know how that's configured in Synology, but it's a default option to a docker container so I guess it's somewhere in an advanced settings section. The DNS settings are described in the README.

If you can connect to the tracker but the speed is slow, that might have to do with open ports etc. That is not something you can configure in your router, as I said, but is up to your VPN provider.

Try setting DNS servers and let me know how it goes.

**Comment by Romijn** [comment]
I contacted SlickVPN and they've forwarded an UDP port to me, seems to be working a bit bitter, speeds are still not fast but at least I'm getting downloads, only thing left is getting the transmission port working that remains closed.

**Comment by Romijn** [comment]
Additional question does this option work?

-e TRANSMISSION_DOWNLOAD_DIR=/volume1/Share/Download/torrent"

If i give this with creating the container?

**Comment by haugene** [comment]
Yes, that option works. My question is, do you want to save it to that path on the host or in the container? Have you read up on volume mounting? The paths inside the container can be mapped to paths outside the container. So if you want files to end up there on your host then you might as well do something like `-v /volume1/Share/Download/torrent:/data`.

You can save torrents where ever, but that path needs to be mounted in order to be visible on your host.

**Comment by Romijn** [comment]
Okay I'll have to test that because the file was actually downloaded but couldn't find it.

**Comment by haugene** [comment]
What platform are you running on? On the host, do `docker exec -it <container-name> bash` and then inside the container do `cd /volume1/Share/Download/torrent`. My guess is you'll find it there and that your problem is a mismatch between where you choose to store stuff and what paths you've actually mounted to your host.

**Comment by Romijn** [comment]
I'm running it on a Synology and you were 100% right it is inside the docker.

-v /volume1/Share/Download/torrent:/data

If I do this it means that everything will there right? My goal would be to only have the downloads there and not the actual Transmission directory.

Appreciate your time btw!

**Comment by haugene** [comment]
Did you figure it out?

**Comment by Romijn** [comment]
No not really specific for the download directory so moved everything to there.
