### ISSUE TITLE
Support for Usenetserver VPN

### ISSUE THREAD

**Issue by b3tts32** [haugene/docker-transmission-openvpn#35]
Can you please add support for usenetserver vpn? Thanks!

**Comment by haugene** [comment]
Haven't had time for this yet, but I'll have a look! Away for the weekend, but maybe I'll squeeze in a little coding on Sunday. 

I'll let you know when I've pushed it to the dev tag so you can verify that it works.

**Comment by haugene** [comment]
I have now pushed support for UsenetServerVPN to the dev branch. When I run it locally it looks to be alright, but I get AUTH_FAILED because I don't have an account and Transmission won't start until OpenVPN is up. So, if you could try to run the container with the dev tag and verify that it works then I'll merge it to the master branch.

Let me know how it goes...

**Comment by haugene** [comment]
@b3tts32 any progress?

**Comment by haugene** [comment]
Expecting it to work, merged to master and closing issue. Open new issue if there are bugs for this provider.
