### ISSUE TITLE
Systemd & Raspberry Pi

### ISSUE THREAD

**Issue by Yannovitch** [haugene/docker-transmission-openvpn#351]
Hello,

Apparently, when I create my transmission-openvpn service, my Raspberry Pi 3 doesn't recognize that it should pull the Dockerfile.armhf, and as such, give me "exec format error" errors.
How can I specify in the transmission-openvpn.service file that I want to use the Dockerfile.armhf, not the standard one ?
Or do you have a specific tag for Raspberry Pi ?
(By the way, could I recommand to specify that we should add the user we indicate in the service file to the docker group ?)

All the best, and thank you for your amazing work,

Y

**Comment by haugene** [comment]
Hi. There is no tag for Raspberry Pi because armhf images needs to be built on a device with that architecture (like the rpi3). The automated builds on Docker hub does not support this to my knowledge.

When building you need to specify the Dockerfile.armhf [using the `-f` option](https://docs.docker.com/engine/reference/commandline/build/#specify-a-dockerfile--f)

I don't understand the last part about adding the user to the docker group. Why is that needed? And are you talking about the host user or the one it's mapped to inside the container?

Hope this helps, good luck!

**Comment by foordy08** [comment]
Evening just came across this forum post as I've been trying to get Haugene's Transmission-OpenVPN docker image working on my Pi too. Did you ever manage to get this up and running? 

Struggling a little bit and have been getting the same error message you were getting when checking the Docker Logs. I know this was some time back now

**Comment by firecat53** [comment]
You have to build the Docker image yourself...you can't just pull it from the Docker Hub repository. For example:

    git checkout git@github.com:haugene/docker-transmission-openvpn.git
    cd docker-transmision-openvpn
    ## Edit DockerEnv if you want to hard code some of the variables into the image instead of passing them on the command line
    docker build -t transmission-openvpn -f Dockerfile.armhf

Now in your transmission-openvpn.service, just specify `transmission-openvpn` as the image name instead of `haugene/docker-transmission-openvpn`. Make sure to `systemctl daemon-reload` after editing the service file.

Hope that helps!

**Comment by maxou2600** [comment]
Hi,
I have an issue with the build (I am using an OrangePi with debian stretch)

`The command 'bin/sh -c apt-get update && ......' returned a non-zero code: 132`

Thanks !

**Comment by haugene** [comment]
Cleaning up old issues. There's been a lot happening in the armhf space, and an image is now available to pull from the docker hub. Closing this, but feel free to open a new one if there's still any issues.
