### ISSUE TITLE
Access webUI from "outside"

### ISSUE THREAD

**Issue by pierallard** [haugene/docker-transmission-openvpn#354]
Hi everyone and thanks @haugene for sharing this awesome repo.

The installation is very easy, and I succedded to put back my old "standard" transmission install.
`transmission` is installed on one of my servers "outside" (i.e. not in my local network).

I tried to access it with `-e "TRANSMISSION_RPC_WHITELIST=*.*.*.*" -e "TRANSMISSION_RPC_WHITELIST_ENABLED=1"`, or with large network intervals `-e "LOCAL_NETWORK=0.0.0.0/0"`.
A good point IMHO is than when I open http://myserver:9091/ on my browser, it redirects to http://myserver:9091/transmission/web/ before a ERR_CONNECTION_TIMED_OUT.

As network is not really my cup of tea, only this part of the README is not so obvious (sorry) and I'm not able to use it to open my webUI from "outside".

Does somebody have any tip ? Any logs to check ? Thanks !

**Comment by haugene** [comment]
Glad you enjoy the repo. There's a lot of ifs and buts on the network part. But before going into that, have you tried the proxy solution? See the part in the readme starting with "Alternatively you can reverse proxy the traffic through another container .. ."

If that doesn't work, we'll take it from there :)

**Comment by pierallard** [comment]
Hi and thanks for your quick answer!

Sorry even if I read 10 times this part, I think I read it too fast. Just running a new `haugene/transmission-openvpn-proxy` image works perfectly !

Feel free to close the ticket and sorry for my noob question.

**Comment by haugene** [comment]
Looking back through old issues and came across this. It must have slipped by me at the time, but setting LOCAL_NETWORK to 0.0.0.0/0 is a very bad idea. @pierallard, you need to change that.

The reason why it can be tricky to access the webUI is because the VPN tunnel is routing all traffic through the vpn server, making the clients on your network unable to get any response because all messages to them go to to the vpn server and nobody knows where 192.168.x.y is because it's not in the public IP space.

So the LOCAL_NETWORK option allows you to tell the container which IPs are on you local network, so it can send traffic there directly. It [adds a route](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/start.sh#L82) that bypasses the vpn server so that traffic can go there through the docker network interface.

You've basically told the container that the whole internet is your local network and traffic that goes there need not pass through the vpn. That's like disabling the whole thing.

So stop that. But if you've gone with the proxy version you might have done that already. The thing with the proxy is that it's also a container so it's automatically on the openvpn containers local network. That's why traffic can flow to it and it doesn't have a tunnel to restrict traffic. And stuff works.

I hope this has enlightened you somewhat on the networking part.
