### ISSUE TITLE
Feature request: Backup server

### ISSUE THREAD

**Issue by himred** [haugene/docker-transmission-openvpn#366]
Hello,

First of all thanks for this amazing container, I use it everyday.
Yesterday I got an issue, the VPN server of my provider went down.
Of course, the container did its work and lost connectivity.
To fix it, I had to manually change the settings to use another server from my VPN provider.

I would be very handy to have the ability to define a backup server.
So when the main server goes down, the backup server would be used.

Something like:

OPENVPN_CONFIG=mymainserver
OPENVPN_BACKUPCONFIG=server2

Regards,

Salim

**Comment by haugene** [comment]
Good thought, but... It will require some code and complexity and KISS is a good principle. Then you have the "fail fast" principle and the manual change isn't the end of the world.

The complexity would be that we then probably need to persist to file that the connection failed, so that it chooses a new connection on restart (given that you run with a restart flag). It's either that or adding more scripts to handle exits signals from the VPN and this complexity would increase the risk of errors that could affect the killswitch etc. I'm just not sure it's worth it. But if someone wants to give it a go and submit a PR I'd be interested if the solution is a clean one.

Any suggestions?

**Comment by pjvds** [comment]
We could accept multiple OPENVPN_CONFIG_* env vars being set in the container and pick just a random one on startup. This way, when one configuration fails, the container gets restarted till a random config that works is picked.

The configs could just be OPENVPN_CONFIG_1, OPENVPN_CONFIG_2, OPENVPN_CONFIG_3,... and so forth. This would keep the solution KISS and there will be no smartness other than random config picking.

Curious about your thoughts.

**Comment by himred** [comment]
I have an idea to implement the backup server feature, but before coding it and submitting a PR, I wanted to make sure it will be accepted.

I propose the following logic:

1. We add a new env variable OPENVPN_BACKUP_CONFIG which point to the backup server config
2. User will need to add a health check using the docker healtchcheck feature pointing to a custom script located in /scripts
3. The script will do the connectivity checks (ping something like 8.8.8.8 or anything the user wants)
4. If a failure is detected (maybe more than once) the script will touch a file in /scripts named .use_backup_config and kill openvpn
5. This will trigger via dumb-init a restart of the container
6. When the container will restart, openvpn/start.sh will look if .use_backup_config is present, if yes it will use the variable OPENVPN_BACKUP_CONFIG in place of OPENVPN_CONFIG

This will require:

1. To write the healtcheck script
2. Modify openvpn/start.sh to take care of the flag file .use_backup_config

If haugene is ok with this, I can take care of the code and submit a PR

Regards

**Comment by pjvds** [comment]
I would vote for random config selection rather than a stateful approach to keep everything as simple as possible.

**Comment by himred** [comment]
Yes, this is a good option too.
Haugene tell us what you think and I'll submit a PR

**Comment by pjvds** [comment]
@haugene 👆

**Comment by haugene** [comment]
Yeah. State or not, that's the question. For now I think we should start with a stateless approach and pick a server at random. You lose the ability to prioritise them, so there's no main and backup server in that sense. But I don't think that is the main issue here, it's just being able to recover at all.

After, if there are strong arguments for a prioritised and stateful approach we'll see then.

I do have one suggestion though. Instead of having OPENVPN_CONFIG_1, OPENVPN_CONFIG_2, and so on. I think we could just accept multiple configs in OPENVPN_CONFIG, separated by whitespace. This can be interpreted as an array in bash, and we can just pick one at random. If there's only one item in the array, it will always get picked. Thoughts?

**Comment by himred** [comment]
Ok, I'm on it.

**Comment by haugene** [comment]
This is merged to dev, will be on master soon. Closing
