### ISSUE TITLE
Can't access transmission web interface

### ISSUE THREAD

**Issue by MartinAyla** [haugene/docker-transmission-openvpn#38]
Hi

I really hope you can help, I just spend half a day trying to get this to work, but I can't.

transmission-openvpn seems to work fine and this is the last output from docker log:
```
Got new port 57505 from pia
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
Port is open: Yes
```

If I check the container IP with:
```
docker exec -it 399 /sbin/ifconfig
```
I get eth0: 172.17.0.2

Then I run the nginx container with -p 8888:8888 and in the nginx.conf I have:
```
proxy_pass http://172.17.0.2:9091
```

But I can't acces the web interface no matter what I try. I try to access it with:
```
http://172.17.0.2:8888/transmission/web/
```

Any ideas?

Thanks

**Comment by haugene** [comment]
Hmm. So you've started the transmission-openvpn container with -p 9091:9091 right? Then transmission will be available on your hosts port 9091 as well as the container ip:9091. This is done so that you can leave the nginx-config untouched even if you remove and create a new transmission-openvpn container (updates etc).

So your nginx.conf should point to your hosts IP:9091, eg 192.168.x.x:9091, then this will proxy the traffic from the docker IP space to your host networks IPs.

You say you're running the nginx with -p 8888:8888, then I assume you've also changed the example config to listen to port 8888? That is the "listen 8080;" statement for the server?

If you haven't, you could either do that or you could start it with -p 8888:8080, that will map your host:8888 to the container:8080 address. And once again you should be able to reach the nginx-server on your host-ip:8888, ie 192.168.x.x:8888.

There are many ways of doing this. The one I've described in the README binds container processes to your host ports and you should not need to know the IPs of the containers.

I hope this helps, and if you're still struggeling please post the full run command you use to start both containers (excluding usr/pass etc of course), and the full content from your nginx.conf

**Comment by MartinAyla** [comment]
Thanks a lot for the help, and sorry for the late reply.

I couldn't get it to work no matter what I did, until I tried running the container with the host IP:
-p my_host_IP:8888:8888 - then it works - the ports alone would not work.

I don't know if it's because I have two network cards with different IP spaces on the host, maybe?

**Comment by haugene** [comment]
Aha, yes that makes sense. Don't know what docker does when it's asked to bind the port to your local host if there are two IP spaces. Good to hear you got it working, and np :)
