### ISSUE TITLE
Synology cannot access /data

### ISSUE THREAD

**Issue by pr0clivity** [haugene/docker-transmission-openvpn#449]
I've followed the Readme under the Synology section and followed each step.  I get an issue after starting the docker.  Here's a clip from my startup script (except for my PIA creds):

> docker run \
    --cap-add=NET_ADMIN \
    --device=/dev/net/tun \
    -d \
    -v /volume1/docker-stuff/resolv.conf:/etc/resolv.conf \
    -v /volume1/docker-stuff/data/:/data \
    -e "OPENVPN_PROVIDER=PIA" \
    -e "OPENVPN_CONFIG=Netherlands" \
    -e "OPENVPN_USERNAME=FOO" \
    -e "OPENVPN_PASSWORD=BAR" \
    -e "LOCAL_NETWORK=192.168.0.0/24" \
    -e "OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60" \
    -e "PGID=100" \
    -e "PUID=1234" \
    -p 9091:9091 \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    --name "transmission-openvpn-syno" \
    haugene/transmission-openvpn:latest

I consistently get the same errors each time in the log:

> chown: cannot access /data/completed No such file or directory
chown: cannot access /data/incomplete No such file or directory
chown: cannot access /data/watch No such file or directory

I do have /volume1/docker-stuff and did a chown -R 1234.users on /volume1/docker-stuff/data

I've tried multiple places for "/data" in different paths under /volume1 (i.e. /volume1/foo), not creating the dir, creating and chown'ing the dir, setting the docker to run under "high privilege" with the same result each time.

I'm running DSM 6.1.5-15254 Update 1

I feel like I should be missing something simple, but since I've tried this with different paths I'm not sure what that could be.,

**Comment by haugene** [comment]
Ok. So this fails because the [userSetup.sh](https://github.com/haugene/docker-transmission-openvpn/blob/master/transmission/userSetup.sh#L14) script expects download directories to be present and tries to set the owner of these directories to the user you supplied.

You see it in your logs "no such file or directory". I think this would work if you ran as root, or if you created the folders in the dir you mount. So if you mount /volume1/foo, make sure that foo contains the directories `completed, incomplete and watch`

**Comment by pr0clivity** [comment]
thanks... I'll blame this misstep on my lack of sleep.  Thanks!
