### ISSUE TITLE
add TCP option for PIA VPN

### ISSUE THREAD

**Issue by Celoxocis** [haugene/docker-transmission-openvpn#456]
hi there,

I've dockerized my environment recently and started using your container. thanks, everything works fines!

there is however one option i can't seem to find. by default the connection to PIA is established using UDP. which is of course the preferred way.

however due to my isp using RFC 8157 (GRE tunnel bonding). UDP packets are send twice and also received on my end twice and therefore the throughput suffers. the openvpn log will be spammed with
"**packet error: bad packet ID (may be a replay)**"

the only workaround to have proper throughput was to change OpenVPN to connect using TCP. (connection oriented, (tcp ack))
which i can't seem to do using the container or any **-e** setting. would it be possible to add a switch to connect using the tcp protocol to pia? e.g. "-e TCP"?

**Comment by eugenioseveri** [comment]
Hi, I made a pull request which adds TCP support at profile level. To use this option you need to set _OPENVPN_CONFIG_ to the correct profile.
e.g. instead of " OPENVPN_CONFIG=Netherlands" you should use "OPENVPN_CONFIG=tcp/Netherlands".
If you set this variable from the command line you may need to escape the string: "OPENVPN_CONFIG=tcp\\/Netherlands".
I also included support for "strong" profiles, which use more secure algorithms. You can choose them from the "tcp-strong" folder (e.g.: "OPENVPN_CONFIG=tcp-strong/Netherlands").

**Comment by Celoxocis** [comment]
Thanks! That's exactly what was missing. Any chance your pull will be merged into the main branch?

**Comment by haugene** [comment]
Hey. Merged it to the dev branch now, so it will be available on the dev tag of the image.
Hopefully I'll get a new release out soon. Maybe before end of easter 🤞

**Comment by Celoxocis** [comment]
thanks i switched to the dev tag now and it works great. my throughput can reach my max wan speed now. (as tcp opevpn-vpn is a must for RFC 8157 (GRE tunnel bonding). ISP's)
