### ISSUE TITLE
Has anybody used this with AlgoVPN?

### ISSUE THREAD

**Issue by richardtheb** [haugene/docker-transmission-openvpn#460]
Hey, just wondering if anyone has used this docker container with AlgoVPN, an interesting VPN system that uses a cloud server as the VPN router? Details at https://github.com/trailofbits/algo

Might be an interesting one to include support for...

**Comment by haugene** [comment]
Haven't seen that before, cool piece of software!

As for using it with this container, it should not be an issue. You would have to use the custom provider approach described in the README as I guess every user would have his own IP to the server, certificates and so on.

When it comes to Algo for p2p the paranoid could argue that there is strength in numbers and that part of the anonymity you get from a VPN service is because there are thousands of users so it's hard to identify who is consuming what. If you set up your own VPN server, then inspecting your traffic would show a lot of encrypted traffic to your VPN server and if there are no other connections to the server then all the traffic originating from it is necessarily from your tunnel.

**Comment by haugene** [comment]
Closing this as it's not really an issue with the software. It's an interesting suggestion, but maybe better suited for the gitter chat room.
