### ISSUE TITLE
hub.docker.com Readme Issues

### ISSUE THREAD

**Issue by toddward** [haugene/docker-transmission-openvpn#464]
I noticed that on the https://hub.docker.com/r/haugene/transmission-openvpn/ there's a reference to the ability to provide a comma separated list to `OPENVPN_CONFIG`.  However, upon pulling `docker pull haugene/transmission-openvpn` and attempting to start the container with the comma separated list, the container defaults to another VPN (in this case uk50.nordvpn).  

I do see that you have this fixed in the `dev` branch.  Potentially the README are out of sync and needs to be updated on https://hub.docker.com/r/haugene/transmission-openvpn/.

**Comment by fizux** [comment]
I'm having a similar issue with using a comma separated list for the local_network variable as well.

**Comment by toddward** [comment]
@fizux using the `:dev` branch fixed my above issue and I'm using that until it's merged.  I do see another calling out start.sh for splitting local_network up correctly.

**Comment by haugene** [comment]
I've seen this before. Seems docker hub is grabbing the README from the last build. And since there are more changes on the dev branch, it's often the last build: https://hub.docker.com/r/haugene/transmission-openvpn/builds/

It's a bigger issue right now because there's actually a big difference between the branches. But this is not something I can fix, other than to manually trigger a master branch build after each change on the dev branch.

**Comment by fizux** [comment]
That makes perfect sense now. Thanks!
