### ISSUE TITLE
updatePort.sh

### ISSUE THREAD

**Issue by makloda** [haugene/docker-transmission-openvpn#49]
Looking at the shell script, it seems the port/IP is only periodically updated for the PIA VPN provider, but not for the other providers?

From "start.sh":

    if [ "$OPENVPN_PROVIDER" = "PIA" ]
    then
        echo "STARTING PORT UPDATER"
        exec /etc/transmission/periodicUpdates.sh &
    else
        echo "NO PORT UPDATER FOR THIS PROVIDER"
    fi
    
    echo "Transmission startup script complete."

 My (self-added) VPN provider PureVPN now produces "18:16:33
NO PORT UPDATER FOR THIS PROVIDER" in the logs.

Whats the best way to allow the updater to run for all providers? I could schedule to restart the docker container every couple hours but that's not very elegant.

**Comment by haugene** [comment]
Well, the updatePort.sh script is written especially for the PIA provider because they have a service where you can ask for a port and we then set this in Transmission. Ref: https://www.privateinternetaccess.com/forum/discussion/180/port-forwarding-without-the-application-advanced-users

If you want automatic port updates for your provider you must first write a script that gets a port designated from your provider and then does as the PIA-script by setting it in Transmission...

**Comment by makloda** [comment]
Hi Haugene.  I am using pureVPN and it works great ,however, sometimes my VPN provider loses connection so that causes transmission to stop all transfers (as it should). Currently I use a cron on the Synology host to simply restart the docker container every 4 hours which then restarts the whole image and connecst to VPN again. But it feels like killing an ant with a sledgehammer.  Is there a way to schedule automatic reconnection to the VPN inside the container in case the VPN connection is dropped?
