### ISSUE TITLE
How to install this container on raspberry pi?

### ISSUE THREAD

**Issue by tleung927** [haugene/docker-transmission-openvpn#496]
I am using OMV with this docker in my old PC without any problem. But in order to cut down the electric bill,  I bought a raspberry pi 3 model B to connect my security cam and torrent. 
I was install the docker using 

      docker run -d \
      --link <transmission-container>:transmission \
      -p 8080:8080 \
      haugene/transmission-openvpn-proxy 
on my old PC .

But I can't make it work on raspberry pi . I read the guide for ARM machine. it said " 2 additional Dockerfiles created. The Dockerfiles supported by the Raspberry PI are Dockerfile.armhf" But how to use this file?
Any help ?!?! thanks!!!!

**Comment by tleung927** [comment]
Thanks but i don't get what i need to put in <your image tag>? could you be more specific?

**Comment by vnnkl** [comment]
i have an odroid, which is also ARM like pi3.
you can change the tag:
`docker build --tag="odroid-transmission" --file="Dockerfile.armhf" .`

**Comment by whi4** [comment]
Hi,  I am really new at using docker and have been struggling to get this service working on my new bananapi (armhf).  I found someone had created an image for arm (ledokun/armhf-docker-transmission-openvpn)  but unfortunately it does not seem to work.  I kind of followed the instructions here to build my own image and strangely get the same error.  The Transmission website at ip:9091 seems to start (some headers and footers) but has a box  reporting it is unable to connect to server.    The icons on the top line do not work and the url reads "http://bpip:9091/transmission/web/#cancel"

I have done some digging and see that an environment variable called TRANSMISSION_WEB_UI exists, but is not defined in the dockerfile.  I have tried to define it as kettu (like in some notes here), but there is no change in the appearance of the web page.

I have had a closer look at the dockerfile used for armhf and suspect it may be for a different version because the tinyproxy is not installed, but environment variables for its configuration are included.

I also see some differences between the x64 and armhf dockerfiles near the top where stuff to do with transmission is called(?).  line 11 uses ppa prefixes and not in the arm version.  I am really lost here!


I am also not sure how to check if the openvpn part is working.  Is it possible to expose another port to view openvpn (I assume it presents some web page when it works)

This looks like a great service that is so close to working on my armhf.  I would really like to get it going but need some help, please.

Kind Regards,  Robert

**Comment by whi4** [comment]
I have been learning more about docker and have been looking around inside the container.  It is surprising that line 17 of the armhf dockerfile ( && mkdir /opt/transmission-ui/transmission-web-control \) does not actually work.  The directory does not exist in the image, but I can execute the command OK to create the directory.  I suppose that accounts for lack of functionality of the web page?

Any ideas how to overcome the problem?  I can execute line 16, but not line 18 from outside the container.

The openvpn seems to be working ok, the container has an external ip provided by the vpn (yay!)

Regards,  Robert

**Comment by haugene** [comment]
Not sure it will solve your problem, but i think all the mkdir commands should be "mkdir - p". That's how I like to script things at least. So the command doesn't fail if it exists etc

**Comment by whi4** [comment]
Hi,
The latest version of Dockerfile.armhf edited by Noodle05 on 21/6 seems to work fine on my bananapi .
Thanks to all concerned for your work!!

I am not sure how to use tinyproxy.  Do I need to use the -p switch to open a port?

Regards,  Robert

**Comment by whi4** [comment]
Hi,
The whole package works well now.  In case it helps someone, I found that:
1/  The Dockerfile.armhf did not expose 8888, like the normal Dockerfile did.
2/  The start.sh file in the tinyproxy directory pointed to the config file in /etc, but it is actually located in /etc/tinyproxy
3/  The Transmission webpage worked if I added "TRANSMISSION_WEB_UI=transmission-web-control" to the environment variables, both in the Dockerfile.armhf and the env file (if you use one - I do).

Thanks again to all those involved in making this great package.  It looks like a very powerful system.
Regards,  Robert

**Comment by haugene** [comment]
Hey Robert. Thanks for the update, glad that the armhf version works again.

As for your comments. You need to add the -p flag to expose the proxy port as you say. The EXPOSE 8888 that's missing in Dockerfile.armhf should be added but it has no big effect if you're not using dynamic port binding. If you specify -p 8888:8888 that will add the port to the exposed list.

For all the errors that you've found a fix we'll gladly take a pull-request :) Although it's weird that the default UI isn't working.

**Comment by haugene** [comment]
Update: #582 adds support for automatic builds on Docker Hub. New tag dev-armhf is [built and available](https://hub.docker.com/r/haugene/transmission-openvpn/tags/).

**Comment by haugene** [comment]
@tleung927 There is now an armhf tag available of the proxy image as well. Closing this.
