### ISSUE TITLE
Contributor request

### ISSUE THREAD

**Issue by coolboiime** [haugene/docker-transmission-openvpn#518]
@haugene Love this project so far, would love to be a contributor!

**Comment by haugene** [comment]
That's awesome! Added you as a collaborator now 👍 

Feel free closing issues and merging stuff to dev. I've tried to set up some restrictions for the master branch since merging there usually means creating new tags and builds on Docker hub etc. Not sure if it's ironclad, but then you know the intention behind it. We'll start there and see where it goes :)

**Comment by haugene** [comment]
Great, welcome aboard! 😄 
And thank you for wanting to contribute - much appreciated.
