### ISSUE TITLE
openvpn Stack deploy template? (for swarm use)

### ISSUE THREAD

**Issue by Shinoby1992** [haugene/docker-transmission-openvpn#523]
Hey i tried all out to somehow get it working on my star, i just cannot solve that problem.

Running it manually through 

`
docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d \ 

              --name vpn \
              --dns 8.8.4.4 \
              -e OPENVPN_PROVIDER=TORGUARD \
              -e OPENVPN_CONFIG=Netherlands \
              -e OPENVPN_USERNAME=blabla \
              -e OPENVPN_PASSWORD=blabla \
              -e OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60" \
              -e LOCAL_NETWORK=10.0.0.0/24 \
              -e WEBPROXY_ENABLED=true \
              -e ENABLE_UFW=true \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              --restart=always \
              haugene/transmission-openvpn
`

and then after it my container:

`docker run -d --net=container:vpn containerthatdoesrunthroughvpn`

it does work. But:

im running a swarm i want a stack deploy template that i can scale up and down (not for the openvpn) But how can i get that usable template (please seperated, means i already have a stack file for my "containerthatdoesrunthroughvpn" . Now i just want a stack template for the OpenVPN, but i can't get this solved.

**Comment by haugene** [comment]
Not sure that I can help, and you may have moved on. I've used swarm a bit, but haven't used the stack deploy feature. Where is the problem? You need to assign the container to a specific host, right? So you get the same volumes etc. Or is this a problem with the networking? Because of overlay network on the swarm?

If you have a specific issue at hand - I'll gladly try to help. But if not I think this issue has been open for quite long fishing for an answer and it doesn't seem that anyone has it. So I'll soon close it as being a bit "to the side" of the regular use cases for this image.

People google'ing the same might come across it anyways - so maybe in time :)

**Comment by Singwai** [comment]
I have different issue with docker swarm. 
``` --cap-add=NET_ADMIN```

I don't think this configuration is available on stack deploy.
