### ISSUE TITLE
Issue:  can't run more than 51 containers through VPN how to fix?

### ISSUE THREAD

**Issue by Shinoby1992** [haugene/docker-transmission-openvpn#537]
Running VPN code:

```
sudo docker run --cap-add=NET_ADMIN --device=/dev/net/tun -ti \
              --name vpn \
              --dns 8.8.4.4 \
              -e OPENVPN_PROVIDER=x \
              -e OPENVPN_CONFIG=x \
              -e OPENVPN_USERNAME= x \
              -e OPENVPN_PASSWORD=x  \
              -e OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60" \
              -e LOCAL_NETWORK=10.0.0.0/24 \
              -e WEBPROXY_ENABLED=true \
              -e ENABLE_UFW=true \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              --restart=always \
              haugene/transmission-openvpn
```

and the containers im running with: 

`sudo docker run -d --net=container:vpn mydockercontainer`

after 50 containers every container that runs through the vpn crashes directly starting chrome.
when i create a second vpn container naming it vpn2, and running the other containers through vpn2, with the same code posted above just changing it ti port -p 9092:9091  all container works.

But i don't want to have 2 vpn containers running, its getting count like 2 simultaneously connections.
is it possible to maximize the vpn container that i just need 1?
i think its a port issue, my error message:

 

>    driver = webdriver.Chrome(chrome_options=options),
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__,
>     desired_capabilities=desired_capabilities),
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__,
>     self.start_session(capabilities, browser_profile),
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 245, in start_session,
>     response = self.execute(Command.NEW_SESSION, parameters),
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute,
>     self.error_handler.check_response(response),
>   File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response,
>     raise exception_class(message, screen, stacktrace),
> selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist,
>   (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.13.0-1019-gcp x86_64)
> 
> 
> 
>

**Comment by Shinoby1992** [comment]
no one has a answer?
i can ecsactly running just 51 containers on each vpn container

**Comment by haugene** [comment]
No answer, but a couple of thoughts.

Since you can start 50 containers working through the one VPN container, that kind of seems to work. Also the container networking is not a feature of this container but of Docker itself. So I don't think this is an issue with this image.

Could it be a limitation with Docker? Maybe not, they're usually quite scalable. Then I see you're using it to run selenium web driver. What is the default port range where it picks it's ports from? Would also surprise me if that wasn't bigger than 51 ports - but who knows.

Can you run other containers with other services through the VPN? If you have the maximum number of selenium containers are you still able to start a proxy container or another webapp through the container networking? If that works then the problem is probably with selenium, if not it points more to the Docker networking part. Can you run more than 50 selenium sessions from the same container? If so, that also points to the networking rather than the apps themselves.

If you find that other VPN containers can handle more than the 51 connections, then it might have to do with our implementation here - but as I said - this is not something that we've made. It's a core feature of Docker networking.

**Comment by haugene** [comment]
You're right that it will use the network stack of the other container.

And though it seems unlikely that selenium is the problem, it does use a port if it's connecting to a remote server. I suppose that's what these selenium containers are doing?

Even if they don't bind to a listening port they do need to bind a port to receive results from their requests. This is done dynamically, but probably within some range. Again, it would be weird if that range is only 50 ports but still worth a shot.

Are you able to spin up multiple sessions in the same container? Trying 60 sessions within one container should provoke the same error, or at least it could. If you're running 100 containers on the same host then they would have a network stack each as long as you're not running container linked networking. So that would be different

**Comment by Shinoby1992** [comment]
have you a example run command of a image that i can test it? i just don't know what should i run and test out to find out the real issue? 😄 🙏

**Comment by haugene** [comment]
To check if it's the docker networking I propose a very simple container.
Run like this:
`docker run --rm -it --network container:<id|name> buildpack-deps:stretch bash -c "while true; do curl -sS http://ipinfo.io/ip; sleep 30s; done"`

If you create a VPN container and then try to spin up more than 50 of this you can see how that works. Each of the 50 containers will then curl ipinfo every 30 seconds on an infinite loop.

**Comment by Shinoby1992** [comment]
i runned 100 containers without problems, all are working. 
do you have a idea how to figure out a fix for me that i don't have to create a vpn container for each 50 container? i still can't figure out why and where the issue lays, because every docker container has its own firefox running
1 container running in itself -> 1 selenium that accessing 1 firefox from the container itself.
and ecsactly after 50 chrome does not start anymore mmh

**Comment by Shinoby1992** [comment]
i found out the issue is that running other containers through one with --net=container:
the container running through the host container(in this case host= vpn container) share their resources.
Xvfb has a maxclient value, that can be modified by xvfb-run --server-args maxclients=512 if this image is not running xvfb, then im not sure about how to change the max clients because running another container through this vpn container, i have to adjust that setting in the host container.

**Comment by haugene** [comment]
UFW_ALLOW_GW_NET is to allow it through the firewall, when using UFW. But that's for this container specifically. I've never tried anything like creating a network and passing all it's data through another container - so I won't say if it works or not. Docker is very flexible, but I think that's pushing it.
