### ISSUE TITLE
Feature Request: Option to Disable Setting Permissions

### ISSUE THREAD

**Issue by dcrdev** [haugene/docker-transmission-openvpn#546]
I would like to request the option to disable the startup script from setting permissions on the download directory. I have quite a decisive permissions set up utilising acls, every time the container restarts it overrides those permissions.

I'm having to go through quite a few hoops to maintain my permissions and even then the container is managing every now and then to still reset those permissions.

Thanks

**Comment by coolboiime** [comment]
Send the pull request along!

**Comment by dcrdev** [comment]
Any update on this one?

**Comment by dcrdev** [comment]
Is there only one person with approval status on this repo?

**Comment by haugene** [comment]
Hey guys. Nah, now there's two of us. But for the better part of the project it's only been me.
First let me say thank you for contributing @dcrdev. Awesome that you're helping out making the container more flexible to use. What can I say, the summer has just been too good this year to things have stopped on my part and more PRs have come in.

But! On to the matter at hand. I agree that the current global permission override is unfortunate. It makes life easier for many that just want their files to be accessible but is a bit invasive for those who like to manage it more closely. The UID/GID feature have gradually been improved and now it's probably messing with too much. So let's do something about that.

The question is what. Your suggestion will fix the issue, but I'm thinking that instead of assigning temp variables and then unsetting them if we don't want it to change we should rather do the chmod/chown in two rounds. So we would get something like:

```
    chown -R ${RUN_AS}:${RUN_AS} \
        /config \
        ${TRANSMISSION_HOME} 

    chmod -R go=rX,u=rwX \
        /config \
        ${TRANSMISSION_HOME} 

    if [ "$GLOBAL_APPLY_PERMISSIONS" = true ] ; then
        chown -R ${RUN_AS}:${RUN_AS}
              .... transmission dirs...
        chmod -R go=rX,u=rwX 
              .... transmission dirs...
    fi
```
And then update comments to explain what and why, as well as readme.
Thoughts? I'm also considering if this should be default on or off. Breaking changes should be avoided, but for future users this implicit permission change could be a bit surprising.

And even if we make it enabled or not by default, the env var needs to be added to the armhf and alpine dockerfiles as well.

**Comment by dcrdev** [comment]
Yes that's probably a bit more elegant -

In regards to having it as the default or not - can't really say, depends what the original motivation was I suppose i.e. were many users complaining about permissions? I myself manage permissions quite closely so this is quite invasive, but I don't mind setting an additional directive so long as there is one.

Probably leaning more towards the latter, where the current behaviour is the default and disabling it is an configurable directive.

If you're happy with the above approach, I can amend my pr tomorrow?

**Comment by haugene** [comment]
Sounds good! There was a bunch of permission issues, so making a good basic setup is probably a good approach for most users. Thanks! 😄

**Comment by dcrdev** [comment]
Right that's now done .

**Comment by haugene** [comment]
Great stuff. Merged it to dev now, will try to work through the pull requests and make a new merge to master and new release tag once that's done. Thanks again!

**Comment by haugene** [comment]
Well, this has been merged to master a while back. Closing.
