### ISSUE TITLE
Windscribe VPN Configs Need Update

### ISSUE THREAD

**Issue by kilo-WATT** [haugene/docker-transmission-openvpn#569]
For any Windscribe .ovpn file, I was getting warnings pertaining to the certification server and cipher. I edited two lines in the VPN configs to replace the text before the arrow with the text after the arrow.

ns-cert-type > remote-cert-tls

AES-256-CBC > AES-256-GCM

No errors after making these changes. A quick search and replace fixed this for me but has to be done every time after a rebuild.

**Comment by coolboiime** [comment]
Linking this issue with #554! Closing for now.

**Comment by haugene** [comment]
Hey @kilo-WATT 

I guess this is still an issue? I see that the Windscribe configs has not been changed since they were added in October 2016. Maybe we should do an update for all of them. Do you have a link to zip file with all the configs? We could do a search and replace as you say, but I guess that with these changes there is also a change in the server list.
