### ISSUE TITLE
Supported Provider Request: CyberGhost

### ISSUE THREAD

**Issue by xorinzor** [haugene/docker-transmission-openvpn#597]
I'd very much like CyberGhost to be added to the supported providers :)
I currently run a custom setup which does the same, but if I could replace all of it with just this single container that'd save me a lot of hassle (my setup still has the occassional breaks..)

**Comment by xorinzor** [comment]
I just created a custom config following:

https://github.com/haugene/docker-transmission-openvpn#using-a-custom-provider

And using this config file as example for how to edit my own config file: 
https://github.com/haugene/docker-transmission-openvpn/blob/da0efcdfd3155530beda897ee8ba8d8d51b2e2bc/openvpn/tunnelbear/Australia.ovpn

**Comment by haugene** [comment]
Great. The custom provider config is a good way to solve it and makes it easier to maintain the config file yourself. If you want to add support for CyberGhost it's a matter of adding all the files in a cyberghost folder and making the same edits as you probably did in your file.

I'd be happy toget a pull-request on that, or if you provide a link to all the configs then maybe someone else could add it. But you got it working, so that's the most important I guess :)

**Comment by xorinzor** [comment]
@haugene well unfortunately I worked on it a few hours yesterday thinking it was going to work.

But I'm still running into issues which I'm not sure about.

For example, first I get a few times some log lines about that I can't use "dhcp-option", though I don't even have those set in my ovpn config. 

As well as ipv6 errors (while my unraid server is configured IPv4 only).

After a while it finally seems to start with my custom ovpn config file, but it doesn't make much sense. Unfortunately I still get AUTH_FAILED even though I confirmed the credentials to be correct (no hidden characters, etc) and used the console of the docker container to make sure it could read it too (which it can).

So I'm a bit of at a loss right now

**Comment by haugene** [comment]
The ipv6 stuff, is it like this? https://github.com/haugene/docker-transmission-openvpn/issues/516

About the AUTH_FAILED, when you say you used the console of the container what did you do? Have you checked the contents of /config/openvpn-credentials.txt after starting the container? Should contain username and password.

Some providers have a separate username/password for openvpn connections, as opposed to the regular login and app use.

**Comment by xorinzor** [comment]
Getting closer step by step.

Managed to fix all the errors I was getting before, the only remaining error is AUTH_FAILED, which I'm still clueless about.

**Comment by xorinzor** [comment]
Okay, so I created a new docker container from repository "dperson/openvpn-client" and using the exact same configuration, that openvpn works without any issues.

Whereas this container seems very inconsistent regarding it's errors, as now I'm getting the error that no "/dev/net/tun" device exists, while I'm doing nothing different from the other container.

**Comment by haugene** [comment]
Allright. About the /dev/net/tun error I don't know. But the AUTH_FAILED is generally caused by wrong credentials or special characters in the password. The templating solution stumbles on those some times. Since it's working with the other client it seems that the credentials themselves are correct. You've double and triple checked the contents of /config/openvpn-credentials.txt right?

Because the openvpn server is saying that they're wrong and then they probably are. They're read directly from the config file so that's really the place to look. Could there be encoding or some other error going on? Grasping at straws here...

Don't know what else to do based on the information I have now. Maybe post your docker run command, contents of the config file and logs? I could try to reproduce it locally, but then you'd need to send me the username/passwd on a PM on Gitter for example.

**Comment by xorinzor** [comment]
I'm just gonna leave it as-is. I currently have a separate container for my vpn and applications and can manually route them via my vpn now (well, that, and that this just works).

I'm sure there's some configuration issues causing this and the other problems, but I've tried just about anything I could find and have limited experience when it comes to Docker, so when I tried it with this separate openvpn container and got it to work I just gave up on it.

As long as the other providers work I'm sure there's just something weird going on with my installation

**Comment by mrjackyliang** [comment]
Marking this on #554.

**Comment by firechipmunk** [comment]
Hi xorinzor

I’m trying to setup dperson/openvpn with cyberghost. However I’m having trouble getting a connection, logs shows a connection but times out after a minute. And does repeatedly.

Did you have to do anything special to cyberghost vpn working with dperson container. Thanks

**Comment by xorinzor** [comment]
I don't think I ever got it to work properly, eventually just gave up and set up my own proxy with separate containers on their own network.

Same idea, but having the services spread out over individual containers instead of all-in-one.

**Comment by Falconx1000** [comment]
@xorinzor @haugene 
I don't know if you got this issue figured but I was able to get it working by following the custom provider steps. 3 things I did have to do were 1) mount a folder with the ovpn and other certs and rename the ovpn file to default.ovpn 2) was edit the default.ovpn file to point to the ca, crt and key files using the full path inside the docker container and 3) I saved another file with the username and password. The last one was probably not required but I thought it was easier just to add the auth.txt path

**Comment by haugene** [comment]
Great @Falconx1000. Did you find the instructions in the README to be good and informative enough? I believe there are many that want to use a custom .ovpn config. So if you have any feedback or want to submit a PR making it even better - that's very welcomed.

**Comment by Falconx1000** [comment]
@haugene There are a couple of things I think might be explained better. I'll look into it and see about updating some notes. Honestly though I'm pretty new to actually using github (usually just download and run the software) so it may take me little while.
