### ISSUE TITLE
Docker Mac (18.06.1) newbie - Permission denied creating directory

### ISSUE THREAD

**Issue by zukato** [haugene/docker-transmission-openvpn#608]
Newbie here, so pardon me if my question is not relevant.

Here is the command I type:
`$docker run --cap-add=NET_ADMIN --device=/dev/net/tun -d -v /Volumes/my\ volume/haugene/:/data -v /Volumes/my\ volume/haugene/config.ovpn:/etc/openvpn/custom/default.ovpn --env-file /Volumes/my\ volume/haugene/DockerEnv --log-driver json-file --log-opt max-size=10m -p 9091:9091 haugene/transmission-openvpn`

But I get the following message:
`docker: Error response from daemon: error while creating mount source path '/Volumes/my volume/haugene': mkdir /Volumes/my volume: permission denied.`

/Volumes/my volume/haugene permissions are set to Read & write for everybody.

**Comment by haugene** [comment]
Seems it cannot find the directory you're trying to mount and then tries to create it, where it gets "permission denied"? Have you tried with another directory, preferably one without spaces in the name?

This is not an issue with this container - this is docker specific. Googling it gets several results where the issue is related to whitespace in folder names so I would avoid that.

**Comment by zukato** [comment]
Seems to have solved the problem! Thanks!
