### ISSUE TITLE
updatePPPort.sh: Permission denied

### ISSUE THREAD

**Issue by andre1974** [haugene/docker-transmission-openvpn#619]
Hello,

in my log is a line that says following.

STARTING TRANSMISSION
CONFIGURING PORT FORWARDING
Transmission startup script complete.
/etc/transmission/start.sh: 73: exec: /etc/transmission/updatePPPort.sh: Permission denied

When i exec into the container and give permissions to updatePPPort.sh it works.
But after restart all is as above.

I am using Perfect Privacy and need the function to set the port automaticaly.

What can i do?

**Comment by evsasha** [comment]
Hi, I have tested this and this is not working properly.
Because there is no permission to execute the file:
```
root@45541df62441:/#  ls -al /etc/transmission/updatePPPort.sh
-rw-r--r-- 1 root root 2098 Aug 15 14:37 /etc/transmission/updatePPPort.sh

root@45541df62441:/# exec /etc/transmission/updatePPPort.sh
bash: /etc/transmission/updatePPPort.sh: Permission denied
bash: exec: /etc/transmission/updatePPPort.sh: cannot execute: Permission denied
```
I think author of this commit has pushed the file with wrong permissions, and then after container start, permissions do not change anywhere else.

To fix the situation for all users you need to rewrite file with the correct attributes (open merge request).

As a temporary solution and only for you - use [**Custom pre/post scripts**](https://github.com/haugene/docker-transmission-openvpn#custom-prepost-scripts) script to set right permissions (i dont tested this).

**Comment by haugene** [comment]
Hey guys. You are correct, that file did not have execute permissions. Almost weird that hasn't come up earlier. Anyways, added the permissions now. Can you test using the dev tag?
Dev images are building now: https://hub.docker.com/r/haugene/transmission-openvpn/builds/

**Comment by evsasha** [comment]
I pulled dev image and tested script permission - all right:
```
# ls -al /etc/transmission/updatePPPort.sh
-rwxr-xr-x 1 root root 2098 Oct 18 19:16 /etc/transmission/updatePPPort.sh
# exec /etc/transmission/updatePPPort.sh
ipAddress to calculate port from
calculated port 100
transmission auth not required
localhost:9091/transmission/rpc/ responded: "success"
Checking port...
```
But i can't test "Perfect Privacy", i haven't account.

**Comment by andre1974** [comment]
If it works with permissions it will work with Perfect Privacy.
When i chmod it manually it works fine.

**Comment by haugene** [comment]
This is now merged to master and is in the latest release. Closing this
