### ISSUE TITLE
couchpotato+sickrage

### ISSUE THREAD

**Issue by jsorondo** [haugene/docker-transmission-openvpn#64]
I have openmediavault 2.3 running with couchpotato installed in the host and sickrage running in a docker container. I downloaded the transmission-openvpn container and I'm having a few issues that need some help with. I'm fairly new to docker so I might be overlooking some details. btw docker is running on the openmediavault host. 1st issue I encountered is that when I run the container port 9091 shows as filtered on both eth0 and eth1. port only shows open for localhost and the docker interface. For some reason if I use localhost instead of the IP of the docker instance (or maybe is because I'm connecting via LAN) it shows the frame of transmission but no content. Again all these are details. If I vpn into my openmediavault server transmission displays correctly. Now, my real problem is that couchpotato is snatching the torrents but they are not populating in transmission por some reason. In Sickrage (docker) it's able to send the torrents and download them but after the files are downloaded sickrage is supposed to move them over to the shows folder and it's apparently deleting them instead. Please advise.

**Comment by haugene** [comment]
You say you're running the container on port 9091 and it shows as filtered. Have you also set up the proxy described in the README? If you try to connect to the transmission webui on the openvpn-container port 9091 it will not respond unless you're on the Docker subnet. Because all other IP's are routed through the VPN tunnel.

So couchpotato is snatching torrents and placing the .torrent files in your transmission-home/watch, but transmission doesn't add them? But then you say that when Sickrage downloads a .torrent, transmission adds it and downloads it, but then Sickrage deletes it?

I don't know what's failing. But you need to be more specific as to this container. It seems like the WebUI is working and that it downloads. 
You need to check if couchpotato is actually placing files in the watch folder. And what sickrage is up to might be because of your volumes setup and paths in Docker. But it sounds like a sickrage issue...

**Comment by jsorondo** [comment]
Haugene, 

I haven't setup the proxy in the readme. Instead of accessing the transmission webui directly I was doing it from inside sickrage using the docker instance IP. This for some reason only works if I'm VPN into the server, otherwise it shows an empty transmission without displaying the torrents if that makes sense. Chouchpotato is snatching torrents but I think the transmission container is having difficulties reading that  folder. The issue with sickrage is that though it fetches the torrents and they are downloaded just fine to the incomplete folder when the downloads are complete instead of moving the files over to the TV folder is apparently deleting the content. This was working fine with the local transmission running on the server. Note that now both transmission are sickrage are containers. Before just sickrage was a container and transmission ran locally on the server. I'll try the reverse proxy and check a couple of other things later as I got the docker update and broke my system. If you have any other advise let me know. Thanks!

**Comment by haugene** [comment]
The webui trouble you're having is likely because of the ip you have when you load it. I think the proxy will solve that. 

Couchpotato is putting the torrents in the watch folder? Have you tried putting torrents there? 

As for sickrage you need to check the paths it's moving from or to. Also check permissions. If you haven't configured another user, transmission runs as root. Can sickrage move them? This is maybe an issue you should be asking them.

**Comment by jsorondo** [comment]
Proxy solved that. Couchpotato for some reason is not putting torrents into the watch folder. I tried to manually drop them and transmission starts all downloads. permissions are 777 so not sure what the problem is. Sickrage keeps deleting things after downloading them. I have setfacl on those folders so that plex, sickrage, couchpotato and transmission have rwx access. Can't find what's going wrong

**Comment by haugene** [comment]
Yup. Not sure what's going on there but it doesn't sound like an issue with this container. 

As I've said. I would recheck all my volumes and paths. Which host folders are mapped where and what their path is in the respective containers. 

Are you sure sickrage is deleting them? It might be moving them to a directory within the container. What is the diff and size of that container?

**Comment by jsorondo** [comment]
transmission-ovpn container mount:
        "Mounts": [
            {
                "Source": "/media/f2208f94-90a6-417b-8a4a-8f942eed6525/MYDATA",
                "Destination": "/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },

sickrage container mount:

"Mounts": [
            {
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            },
            {
                "Source": "/media/f2208f94-90a6-417b-8a4a-8f942eed6525",
                "Destination": "/media/DATA",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {

Both containers can see the content. Not sure where the problem lies. If I enable the local tranmission on the server(not the container) sickrage behaves just fine. It was working before setting up transmission on the container.

**Comment by haugene** [comment]
I'm just on my cell, so I can't test anything. But the source of the media mounts are not the same?

**Comment by jsorondo** [comment]
different folders. But all the content is inside MYDATA regardless.

**Comment by jsorondo** [comment]
haugene. If I would like to change the environment variables for transmission how would I do it? I'm not sure I understand how to make these changes. I think one of the variables is the reason things don't work properly.

**Comment by haugene** [comment]
Changing the transmission settings via environment variables is documented in the Readme. What are you trying to set?

**Comment by jsorondo** [comment]
I'm trying to manually set the incomplete, completed and watch folder paths.

**Comment by haugene** [comment]
As described [in the readme](https://github.com/haugene/docker-transmission-openvpn#transmission-configuration-options) you take the transmission-setting, prefix it with transmission and make it uppercase.

I tried locally and setting environment variable TRANSMISSION_INCOMPLETE_DIR to /whatever makes the settings.json correctly have "/whatever" as path. 

So you should be able to change this by doing the same with watch-dir and download-dir.

**Comment by bertybassett** [comment]
In sickrage are you using black hole or transmission? Black hole works and tranmission mode doesn't appear to because when sickrage say to transmission download to \full\link\Download transmission doesn't understand it only know data/Download. This is very similar to my problem

Try transmission mode but leave download folder blank but make sure one is set in environment settings of the docket container. That works because then there is no passing of a full link ( \full\link\Download) which transmission doesn't understand. 

Starting to think my only option is to put Sickbeard and CouchPotato into the docker too.

**Comment by jsorondo** [comment]
@bertybassett Thanks!! That solved my Sickrage problem. Downloads were being moved into the container to a path that was a reference from sickrage. Leaving the download folder blank solved the issue. Now regarding Couchpotato, how can I make it move the movies over to the library folder? Transmission is downloading the content but Couchpotato is not moving the downloaded content over to the Movies folder when completed. Please advise

**Comment by bertybassett** [comment]
That is a post processing feature of CouchPotato

**Comment by bertybassett** [comment]
However leaving the download load location blank in sickrage (Sickbeard) and CouchPotato is not a solution because the two programs will both download to the same location and clash when trying to move them. Look at my thread for a suggestion on possible fix. Going to try this fix over the weekend and report back.

**Comment by jsorondo** [comment]
@bertybassett Sickrage is working fine. It generates a warning in the logs saying the movies couldn't be processed but is post processing the shows fine. Can I get the link for your thread? Though my main concern was sickrage and is now fixed it would be nice to keep couchpotato automated like before. Thanks in advance

**Comment by haugene** [comment]
#67

**Comment by bertybassett** [comment]
@jsorondo are you using blank on both sick rage and couch potato?

**Comment by jsorondo** [comment]
@bertybassett yup. I have it blank on both. Only difference is couchpotato is using putting the torrents into the watch folder instead.

**Comment by bertybassett** [comment]
see post 64 for a full explanation.
