### ISSUE TITLE
Freevpn integration 

### ISSUE THREAD

**Issue by david-spaeth** [haugene/docker-transmission-openvpn#663]
hi

Can you plan integration of all freevpn configurations ? More info : https://freevpn.me
thanks

**Comment by david-spaeth** [comment]
Absolutely, All configuration file can be find here : https://freevpn.me/FreeVPN.me-OpenVPN-Bundle.zip

Thanks

**Comment by haugene** [comment]
Just added the configs. Running it locally gives me AUTH_FAILED which usually means that it's good to go as long as valid credentials are added.

It will be available on the dev tag shortly (although the hub has build slow lately).
Use OPENVPN_PROVIDER=FREEVPN and OPENVPN_CONFIG as one of the configs in [this list](https://github.com/haugene/docker-transmission-openvpn/tree/dev/openvpn/freevpn) (minus .ovpn at the end). Will default to be-TCP80.ovpn if no config is given.

You can see when the build is ready here: https://hub.docker.com/r/haugene/transmission-openvpn/builds/

**Comment by david-spaeth** [comment]
It works perfectly. The VPN password is public and can be find here: https://freevpn.[*]/accounts/

I see that ARM build failed.

Thanks a lot.

**Comment by haugene** [comment]
Allright, have to look at the ARM stuff later then. Closing this. Will be merged to master and the latest tag sometime before new years I guess :) Depends on how much time I get before the holidays.

**Comment by udayabsuryadevara** [comment]
How did you guys fixed this issue?need help with this? I am trying with this docker config, am i missing any thing? 

docker run --cap-add=NET_ADMIN --dns=8.8.8.8 --name=tr --device=/dev/net/tun -d \
              -v /home/mediafull/downloads/default.ovpn:/data/default.ovpn \
              -v /home/mediafull/downloads/openvpn-credentials.txt:/data/openvpn-credentials.txt \
              -e OPENVPN_PROVIDER=FREEVPN \
              -e OPENVPN_USERNAME=freevpn.me \
              -e OPENVPN_PASSWORD=***** \
		    -e OPENVPN_CONFIG=default \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.0.0/16 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn

default.ovpn:
client
proto tcp
remote server2.freevpn.me 443
connect-retry-max 3
connect-retry 3
resolv-retry 15
dev tun
auth-user-pass
persist-key
persist-tun
nobind
verb 2
key-direction 1
remote-cert-tls server
auth SHA256
cipher AES-256-CBC
route-method exe
route-delay 2
route 0.0.0.0 0.0.0.0
setenv opt block-outside-dns
script-security 2
<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
</key>
;comp-lzo
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
-----END OpenVPN Static key V1-----
</tls-auth>

**Comment by udayabsuryadevara** [comment]
Also tried with this `---
version: '2.1'
services:
    transmission-openvpn:
        volumes:
            - '/home/mediafull/downloads/:/data'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - PUID=0
            - PGID=0
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=FREEVPN
            - OPENVPN_CONFIG=default
            - OPENVPN_USERNAME=freevpn.me
            - OPENVPN_PASSWORD=****
            - DNS=8.8.8.8,8.8.4.4
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.0.0/16
            - OPENVPN_OPTS=--inactive 36000 --ping 100 --ping-exit 600 --tun-mtu 1500
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
        devices:
            - "/dev/net/tun"
        restart: always`

Errors: 
> Fri Jul 24 18:06:37 2020 Exiting due to fatal error
mknod: /dev/net/tun: File exists
Using OpenVPN provider: FREEVPN
unzip:  cannot find or open /tmp/freevpn.zip, /tmp/freevpn.zip.zip or /tmp/freevpn.zip.ZIP.
Starting OpenVPN using config default.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.0.0/16 via 172.17.0.1 dev eth0
Fri Jul 24 18:06:38 2020 Unrecognized option or missing or extra parameter(s) in /etc/openvpn/freevpn/default.ovpn:21: block-outside-dns (2.4.7)
Fri Jul 24 18:06:38 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Fri Jul 24 18:06:38 2020 library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
i Jul 24 18:06:38 2020 neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd - can't ask for 'Enter Auth Password:'.  If you used --daemon, you need to use --askpass to make passphrase-protected keys work, and you can not use --auth-nocache.
Fri Jul 24 18:06:38 2020 Exiting due to fatal error
mknod: /dev/net/tun: File exists
Using OpenVPN provider: FREEVPN
unzip:  cannot find or open /tmp/freevpn.zip, /tmp/freevpn.zip.zip or /tmp/freevpn.zip.ZIP.
Starting OpenVPN using config default.ovpn
