### ISSUE TITLE
Transmission Web Interface Unstable

### ISSUE THREAD

**Issue by edwardreed81** [haugene/docker-transmission-openvpn#693]
This image is working great for me except for one thing: the transmission web interface frequently stops responding and pops up a message about it being disconnected. Most of the time it'll start functioning again after 5 or 10 seconds, but sometimes I have to reload the page.

I am accessing the web UI through a HTTPS NGINX reverse proxy.

I'm having trouble diagnosing because nothing shows up in the logs. Is there a way to enable verbose logging of some sort?

**Comment by haugene** [comment]
I think I saw the same for a while. Was using nginx with a self signed certificate. Now I'm using Caddy which has automatic https with letsencrypt and haven't seen it since. If it has to do with certificate, proxy config or something completely different I don't know. Might not be the same issue either.

But I would guess it has to do with the proxy. So see the nginx image docs if there is some extra logging there. This container doesn't have a verbose feature yet. I proposed it a while back in #355 but have never got around to it. Transmission logs to it's own file, and if they have a debug option we could enable that. If you could find out what kind of Transmission logging you want enabled, and how it's done then we could add it to the image.
