### ISSUE TITLE
Referencing /etc/localtime

### ISSUE THREAD

**Issue by tlc** [haugene/docker-transmission-openvpn#713]
BTW, on an Ubuntu host (at least), /etc/localtime is a softlink to /usr/share/...

Volume mounting the softlink as suggested in the README doesn't work.

**Comment by h45rd** [comment]
Strange. Works for me on my Ubuntu host.

Could not find the expected behavior in a quick search of the Docker documentation. But in my case Docker does not replace the symlink itself within the container, but the actual file it is pointing to.

Just compared `md5sum` and /etc/localtime (container) = /etc/localtime (host), even though the softlink technically points to a different timezone.
As expected, `date` within the container has the same output as on the host.

Do you get any error output in the docker logs? Wrong time within the container?

**Comment by haugene** [comment]
@h45rd What do you think about just removing the localtime mount from the README?
It's just meant to sync the timestamps, and I think most users don't care. The ones that do will figure it out for themselves.

**Comment by tlc** [comment]
I thought I saw a timezone error in the logs.  I will reconfirm.

**Comment by tlc** [comment]
Apologies.  I must have misinterpreted the logs and was then fooled  by this link.

```
# ls -ls /etc/localtime
0 lrwxrwxrwx 1 root root 27 Jan 22 14:22 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
```

But the logs look good now and as @h45rd pointed out, the sum proves that it's the right file.

**Comment by h45rd** [comment]
Thanks for checking, @tlc

Don't think it hurts to suggest the localtime mount in the README, as long as it is not causing any actual issues.
Because I am almost certain that someone will complain about wrong timestamps once the suggestion is gone, even if it is just cosmetic :D

The more I think about it.. wrong timestamps could cause some real issues, too. E.g. with post-processing scripts running on the host, automation software, etc.

**Comment by haugene** [comment]
Good point, getting the issues about wrong timestamps in the container could probably be more noise. We'll leave it as it is.
