### ISSUE TITLE
Add support for surfshark vpn 

### ISSUE THREAD

**Issue by darklite80** [haugene/docker-transmission-openvpn#734]
Would like to have surfshark vpn support as well as maybe a easy way to point the container to a folder to import a custom vpn service by simply naming the folder custom_vpn or something of like.
 Link to p2p approved surfshark ovpn file for Netherlands server https://drive.google.com/file/d/1YyZKY8lXAu8sC9XQH60s9KB1dhngslHv/view?usp=drivesdk
Surfshark  ovpn config file https://drive.google.com/file/d/1mskPQsBDqrT1KWpeGKH3tTBGpm3CuncD/view?usp=drivesdk

**Comment by haugene** [comment]
You can use a custom provider by mounting a folder as you say.
https://github.com/haugene/docker-transmission-openvpn#using-a-custom-provider

Just mount it and use it directly. Usually the only thing you need to think about is that if there's an external ca.crt or something like that you need to change the reference so that it's /etc/openvpn/custom/myCa.crt. And also the username/password provided as environment variables are persisted to file and that needs to be passed to auth-user-pass like this for example: https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/pia/Austria.ovpn#L14

**Comment by haugene** [comment]
If you want it to be added as a supported provider then please provide a link to where the configs .zip file can be downloaded.

**Comment by darklite80** [comment]
The initial post #734 I put the link to google drive where I put the zip files

**Comment by haugene** [comment]
Ok. I read it like that was single ovpn files. But ok, if those are the zip files we've got something to work with. Is there a public link where they are downloaded from?

Been thinking more about the maintainability of all these providers. Maintaining this project is now less about core features and more about just updating config files. If they provide a fixed link for downloading then we can automate it so it stays up to date.

**Comment by darklite80** [comment]
You have to be a member to get to the files

**Comment by darklite80** [comment]
Going to pull the container later today and give it a try

**Comment by mrjackyliang** [comment]
Closing this and merging.
