### ISSUE TITLE
[dumb-init] /etc/openvpn/start.sh: Permission denied

### ISSUE THREAD

**Issue by tleung927** [haugene/docker-transmission-openvpn#735]
This is the second time i found out this problem. after i build the image and install on my raspberry pi , the log keep showing this error message " [dumb-init] /etc/openvpn/start.sh: Permission denied" . I fixed it by change the permission chmod +x for the error files. But this time i can't even find the start.sh in /etc/openvpn/ 

Any idea???

**Comment by tleung927** [comment]
Anyone? I had try to install openvpn from apt-get and manually put the start.sh file to /etc/openvpn and change the permission but still no luck. So frustrating ....

**Comment by haugene** [comment]
When opening an issue always try to describe how we can reproduce it. Since this is your own build on a raspberry that might not be so simple, but at least include the `docker run` command you used to start it. This will say a lot about the state of the container. People could be mounting an empty directory into /etc/openvpn/ for all I know, I've seen a lot. And also add the logs, not just the line that fails.

Have you tried with the pre-built images from Docker Hub instead? Could this be a problem with your build? I'm running this command with the dev-armhf tag (latest-armhf has not been built in a while due to #721) and I see the start.sh script and it has the executable bit set:

```
➜  ~ docker pull haugene/transmission-openvpn:dev-armhf
dev-armhf: Pulling from haugene/transmission-openvpn
Digest: sha256:4e7a0797df305cf1a520e7fe5d2e55e3b113842dfe7d07f8d4a40e2463d6e1b9
Status: Image is up to date for haugene/transmission-openvpn:dev-armhf

➜  ~ docker run --rm -it haugene/transmission-openvpn:dev-armhf bash -c "ls -la /etc/openvpn/ | grep start.sh"
-rwxr-xr-x 1 root root   6600 Mar 10 16:53 start.sh
```

**Comment by tleung927** [comment]
Thanks haugene!! Sorry i don't know we can use :dev-armhf instead of build the image by outself! everything works fine now. I guess i did something wrong on docker build .

**Comment by haugene** [comment]
No problem. Glad to hear it works!
For a while there was no prebuilt armhf image but it's been around for a while now. We had some troubles, and that is the issue I linked to, but it's resolved now on dev and will be on the latest tag soon. Not sure when I'll get around to merging it. Want to add a couple of more features and make a bigger release.

**Comment by tleung927** [comment]
Sound great !!! This is a awesome app, help us save tons of time to setup torrent box! Thanks a lot for your effort !
