### ISSUE TITLE
Mullvad config files need to be replaced

### ISSUE THREAD

**Issue by carjed** [haugene/docker-transmission-openvpn#748]
**Describe the problem**
Looks like the old Mullvad configuration files will no longer work and need to be replaced, per the blog post on 2019-03-22:
https://www.mullvad.net/en/blog/2019/3/22/suddenly-cant-connect-mullvad/

**Comment by p-eh** [comment]
Where they replaced, or did you find a way around it? In the same boat myself here.

**Comment by haugene** [comment]
I think he closed it again because of this line in the blog-post:
> Any files downloaded after 19 November 2018 are fine

And the configs in this container were updated 7th of January, so they should be fine. Have you pulled the lates image?

**Comment by carjed** [comment]
yep, exactly what @haugene said—pulling the latest image is what fixed it for me.

**Comment by p-eh** [comment]
I assumed it was a certificate issue, but shortly after realized that it was due to no having a password. Added just the letter `m` as the password parameter and it worked. Ran into some ipv6 issues too, but used the following as `extra parameters` in docker and it fixed it all. 

`--sysctl net.ipv6.conf.all.disable_ipv6=0`

**Comment by haugene** [comment]
@p-eh @carjed, just merged #751 which removes the old certificate from the ca.crt.
If one of you could pull the image again and verify it's working properly over the next couple of days that'd be great. Then Mullvad should be stable for a while going forward 😄

**Comment by carjed** [comment]
pulled latest image and everything seems to be working ok for me—thanks!
