### ISSUE TITLE
Version 2.7 has broken torguard

### ISSUE THREAD

**Issue by derekoharrow** [haugene/docker-transmission-openvpn#753]
My docker container recently updated to the :latest build (v2.7). This has stopped torguard from working.

I noticed that the .ovpn filenames changed, e.g. from Stockholm.Sweden to just Sweden. I updated the compose file to match that, but it still doesn't connect.

The container logs say:

```
Using OpenVPN provider: TORGUARD
Starting OpenVPN using config Sweden.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.24.0.1 dev eth0
Mon Mar 25 20:02:36 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Mar 25 20:02:36 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Mar 25 20:02:36 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Mar 25 20:02:36 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.153.2:1912
Mon Mar 25 20:02:36 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon Mar 25 20:02:36 2019 UDP link local: (not bound)
Mon Mar 25 20:02:36 2019 UDP link remote: [AF_INET]37.120.153.2:1912
Mon Mar 25 20:03:36 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting
Mon Mar 25 20:03:36 2019 SIGTERM[soft,ping-exit] received, process exiting
Using OpenVPN provider: TORGUARD
Starting OpenVPN using config Sweden.ovpn
Setting OPENVPN credentials...
adding route to local network 192.168.1.0/24 via 172.24.0.1 dev eth0
Mon Mar 25 20:03:39 2019 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Feb 19 2019
Mon Mar 25 20:03:39 2019 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Mar 25 20:03:39 2019 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Mar 25 20:03:39 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.153.2:1912
Mon Mar 25 20:03:39 2019 Socket Buffers: R=[212992->212992] S=[212992->212992]
Mon Mar 25 20:03:39 2019 UDP link local: (not bound)
Mon Mar 25 20:03:39 2019 UDP link remote: [AF_INET]37.120.153.2:1912
Mon Mar 25 20:04:40 2019 [UNDEF] Inactivity timeout (--ping-exit), exiting
Mon Mar 25 20:04:40 2019 SIGTERM[soft,ping-exit] received, process exiting
```

This is on Ubuntu running Docker 18.09.2

Reverting back to 2.6 has fixed the issue for now.

**Comment by haugene** [comment]
Hmm, this has been showing up for several providers. But haven't found the reason for it yet.
I'm using PIA and that works just fine. I downloaded the configs from Torguard again and compared it to what is in the image, and it is correct. Was tempting to thing that this was a config issue since we updated them in 2.7, but... Doesn't look like it.

Can you provide the docker run command you're using?
And how familiar are you with docker? You could do a `docker create --name something haugene/transmission-openvpn:2.6` and then `docker cp something:/etc/openvpn/torguard/ other-container:/etc/openvpn/torguard/` and that way move the 2.6 configs to the current image and run with that. Could also try it the other way around.

Maybe one of the other issues will point us in the direction of what's wrong as well.

**Comment by derekoharrow** [comment]
I found what the problem was.

In my docker-compose I had:

`OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1460 --remote 37.120.153.2 1912`

Your Torguard Sweden ovpn config file uses port 995 instead of 1912

By changing the above line to the following, it now works (removing the 1912 port number):

`OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --mssfix 1460 --remote 37.120.153.2`
