### ISSUE TITLE
Update Nordvpn

### ISSUE THREAD

**Issue by vincentcox** [haugene/docker-transmission-openvpn#764]
**Which provider?**
Nordvpn

**Where are the configs?**
https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/au359.nordvpn.com.udp1194.ovpn

Note the "ovpn_legacy" changed.

**Comment by Troubadoure** [comment]
In the latest version NordVPN no longer keeps all of the scripts in the container but instead downloads the latest ones on demand as needed. Either upgrade to the latest version set the new environment flag NORDVPN_COUNTRY=au and restart (however this won't use legacy servers) or if you want to stay on that particular server. login to your container and run the updateConfigs.sh script in /etc/openvpn/nordvpn. You may want to expose this location to your host though to stop it from being overwritten

**Comment by edgd1er** [comment]
This morning after image update, the container kept on restarting, as the scripts download a 404 file not found html page.

To fix, I had to
- set NORDVPN_PROTOCOL=tcp
- set NORDVPN_CATEGORY=P2P
- unset OPENVPN_CONFIG

My guess is that the protocol ws not set, and the script tried to dl something like: 
_https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/be82.nordvpn.com..ovpn_
instead of 
 https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/be82.nordvpn.com.tcp.ovpn

**Comment by Troubadoure** [comment]
It should auto-set both the Protocol and the Category if it's not set. In the logs there will be a line saying the url that it downloaded the config from. Could you try and find it and post it in here to see if what you're saying is correct?

**Comment by edgd1er** [comment]
when not set, category is guessed.
when not set, protocol is defined as default, when tcp or udp are the only values accepted.

Here the test:
what I did, 
- remove NORDVPN_CATEGORY, NORDVPN_PROTOCOL
- set OPENVPN_CONFIG=default

what to look for in the here under log
Downloading from: https://downloads.nordcdn.com/configs/files/ee14.nordvpn.com.**default**.ovpn

the log:
```
Using OpenVPN provider: NORDVPN
Setting NORDVPN_PROTOCOL to: DEFAULT
2019-03-30 15:33:42 Checking curl installation
2019-03-30 15:33:42 Removing existing configs
2019-03-30 15:33:42 Selecting the best server...
2019-03-30 15:33:42 Searching for country : estonia (68)
2019-03-30 15:33:42 Searching for group: legacy_p2p
2019-03-30 15:33:42 Best server : ee14.nordvpn.com
2019-03-30 15:33:42 Downloading config: default.ovpn
2019-03-30 15:33:42 Downloading from: https://downloads.nordcdn.com/configs/files/ee14.nordvpn.com.**default**.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    245      0 --:--:-- --:--:-- --:--:--   245
2019-03-30 15:33:42 Using OpenVPN CONFIG :: default
2019-03-30 15:33:42 Downloading config: default.ovpn
2019-03-30 15:33:42 Downloading from: https://downloads.nordcdn.com/configs/files/default.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    258      0 --:--:-- --:--:-- --:--:--   258
2019-03-30 15:33:46 Checking line endings
2019-03-30 15:33:46 Updating configs for docker-transmission-openvpn
Starting OpenVPN using config default.ovpn
Setting OPENVPN credentials...
/etc/openvpn/start.sh: line 94: /config/openvpn-credentials.txt: Read-only file system
/etc/openvpn/start.sh: line 95: /config/openvpn-credentials.txt: Read-only file system
chmod: changing permissions of '/config/openvpn-credentials.txt': Read-only file system
/etc/openvpn/start.sh: line 100: /config/transmission-credentials.txt: Read-only file system
/etc/openvpn/start.sh: line 101: /config/transmission-credentials.txt: Read-only file system
adding route to local network 192.168.53.0/24 via 172.17.0.1 dev eth0
Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.7)

````

**Comment by vincentcox** [comment]
I tested what @edgd1er said and it seems to work great now. @edgd1er, thank you for sharing your fix here.
@Troubadoure , Thank you for this great project.

**Comment by Troubadoure** [comment]
@edgd1er - Brilliant thanks for that can see where it's going wrong. Will see if I can get a fix out for it soon

@vincentcox Glad it's working, not my project though - credit due to @haugene

**Comment by edgd1er** [comment]
@Troubadoure thanks for your script, it will help us to have the best and up to date configs of NordVpn 👍

**Comment by jmrushing** [comment]
I think I'm having the same issue. It looks like 2 config files are being downloaded - default.ovpn and then the one I'm trying to set with OPENVPN_CONFIG. For whatever reason the "Supplied config xxx could not be found" so it uses the default instead. 

I think it could have something to do with the way I've (incorrectly?) formatted the OPENVPN_CONFIG.
For what it's worth, when I first tested this github project, I set nearly everything inside of an environment file per the README instructions here and it worked flawlessly. But within the last few days, I transitioned everything over to a docker-compose file per [these instructions](https://www.smarthomebeginner.com/docker-home-media-server-2018-basic/) and now it's behaving strangely. I think I may have made this transition during @Troubadoure 's commit from 3 days ago so maybe that's why I'm getting all mixed up.

So I guess my real question is: do I need to start using the environment variables for NORDVPN_ and forget OPENVPN_CONFIG? Or use both together? Also, should I specify each config file in a new OPENVPN_CONFIG variable instead of all one line like I currently am? 

Any help/advice would be greatly appreciated. I'm new on github so I apologize in advance for newbie mistakes.

Here's the line from my docker-compose:
`OPENVPN_CONFIG=ca192.nordvpn.com.tcp,ca192.nordvpn.com.udp,dk49.nordvpn.com.tcp,dk49.nordvpn.com.udp,fi36.nordvpn.com.tcp,fi36.nordvpn.com.udp
`
Here is the beginning of my docker log:

`
Using OpenVPN provider: NORDVPN
Setting NORDVPN_PROTOCOL to: UDP
2019-03-30 20:33:43 Checking curl installation
2019-03-30 20:33:43 Removing existing configs
2019-03-30 20:33:43 Selecting the best server...
2019-03-30 20:33:43 Searching for group: legacy_p2p
2019-03-30 20:33:43 Searching for technology: openvpn_udp
2019-03-30 20:33:43 Best server : us3319.nordvpn.com
2019-03-30 20:33:43 Downloading config: default.ovpn
2019-03-30 20:33:43 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/us3319.nordvpn.com.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2809  100  2809    0     0   4723      0 --:--:-- --:--:-- --:--:--  4728
2019-03-30 20:33:43 Using OpenVPN CONFIG :: ca192.nordvpn.com.tcp,ca192.nordvpn.com.udp,dk49.nordvpn.com.tcp,dk49.nordvpn.com.udp,fi36.nordvpn.com.tcp,fi36.nordvpn.com.udp
2019-03-30 20:33:43 Downloading config: ca192.nordvpn.com.tcp,ca192.nordvpn.com.udp,dk49.nordvpn.com.tcp,dk49.nordvpn.com.udp,fi36.nordvpn.com.tcp,fi36.nordvpn.com.udp.ovpn
2019-03-30 20:33:43 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/ca192.nordvpn.com.tcp,ca192.nordvpn.com.udp,dk49.nordvpn.com.tcp,dk49.nordvpn.com.udp,fi36.nordvpn.com.tcp,fi36.nordvpn.com.udp.ovpn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    246      0 --:--:-- --:--:-- --:--:--   246
2019-03-30 20:33:43 Checking line endings
2019-03-30 20:33:43 Updating configs for docker-transmission-openvpn
6 servers found in OPENVPN_CONFIG, dk49.nordvpn.com.tcp chosen randomly
Supplied config dk49.nordvpn.com.tcp.ovpn could not be found.
Using default OpenVPN gateway for provider nordvpn
Setting OPENVPN credentials...
`

**Comment by Troubadoure** [comment]
@jmrushing You can remove the OPENVPN_CONFIG variable and just set NORDVPN_COUNTRY= whichever country you choose. This will currently only accept one value so you'll have to choose just one country for the time being (similar with the OPENVPN_CONFIG if you're using NordVPN)

**Comment by jmrushing** [comment]
@Troubadoure Wow that was quick!
I noticed in previous comments there were mentions of NORDVPN_CATEGORY and NORDVPN_PROTOCOL
I haven't found any documentation on these variables or how to use them. Can these be used as well and are there more variables? I'd like to set this as specifically as possible if I can't keep using the servername.ovpn list format that I had been using.

**Comment by Troubadoure** [comment]
@jmrushing - You were lucky am currently sitting by my pc trying to fix an issue with my server. 
The documentation hasn't been updated for these. 
NORDVPN_CATEGORY sets the type of server to use. This is best left alone as it really just states to use a server that supports P2P. 
NORDVPN_PROTOCOL sets whether you want to use tcp or udp. Default is udp.
NORDVPN_COUNTRY takes the country code/name that you want the server to be in.

In my dockerfile I just set the NORDVPN_COUNTRY and leave the rest to default.

**Comment by jmrushing** [comment]
@Troubadoure  - Just tested those variables and that seems to work perfectly. Being able to control Country and Protocol is enough for now. Thanks for the help!

**Comment by sm0ke83** [comment]
@Troubadoure, noticed NORDVPN_PROTOCOL has to be set uppercase, otherwise it doest change to tcp. How is this for NORDVPN_CATEGORY? Tried both, log only mentions legacy_p2p. Also set NORDVPN_COUNTRY=nl, it then downloads 2 configs. Will try a few combinations later today (NORDVPN_COUNTRY, NORDVPN_PROTOCOL, NORDVPN_CATEGORY and OPENVPN_CONFIG=default set or removed).
Attached log is with NORDVPN_CATEGORY=p2p, NORDVPN_PROTOCOL=TCP and NORDVPN_COUNTRY=nl set, now the default uses onion again...

[Log-7.txt](https://github.com/haugene/docker-transmission-openvpn/files/3026507/Log-7.txt)

**Comment by rfenouil** [comment]
Just a quick comment here:

While I was experimenting with the script and NordVPN API, I figured that if you don't specify a country the API  will just ignore other filters you provide.

That can be a problem for the techology filter. Say you selected UDP but did not specify a country: the API will return any server from the 'recommended' country (based on your IP I guess). However there will be no guarantee that the returned server allows UDP connection...
It resulted in downloadind a 404 file because the corresponding configuration file does not exist.

Be sure to provide a value for COUNTRY if you want to use other filters...
I modified the script on my repo to use other filters (but I also modified most of the other scripts so it will not fit here), feel free to have a look for inspiration.

**Comment by jvanlangen** [comment]
Upon starting, the container will stop with the message "Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/nl510.nordvpn.com.tcp.ovpn:1: html (2.4.0)"

This is how I start it:
sudo docker run --cap-add=NET_ADMIN -d \
              -v ~/download/:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=NORDVPN \
              -e NORDVPN_COUNTRY=NL \
              -e OPENVPN_USERNAME=xxxxxxxxxx \
              -e OPENVPN_PASSWORD=xxxxxxxxxx \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=192.168.8.0/24 \
              --log-driver json-file \
              --log-opt max-size=10m \
              -p 9091:9091 \
              haugene/transmission-openvpn:dev-armhf

**Comment by outerepic** [comment]
I started getting this error message today on my Synology server running transmission in a docker container with NordVPN. Please see the logs below, this just started the other day when the docker container updated and was recreated. I have 

NORDVPN_PROTOCOL=tcp
NORDVPN_CATEGORY=P2P
NORDVPN_COUNTRY=US
and OPENVPN_CONFIG is commented out




Starting container with revision: 8cc1870cc039201e0e2f8b7684a9f4e96ae03ab9

Creating TUN device /dev/net/tun

mknod: /dev/net/tun: File exists

Using OpenVPN provider: NORDVPN

Running with VPN_CONFIG_SOURCE auto

Provider NORDVPN has a bundled setup script. Defaulting to internal config

Executing setup script for NORDVPN

2022-05-03 00:11:25 Checking curl installation

2022-05-03 00:11:25 Removing existing configs

2022-05-03 00:11:25 Selecting the best server...

parse error: Invalid numeric literal at line 1, column 7

2022-05-03 00:11:25 Searching for technology: openvpn_tcp

parse error: Invalid numeric literal at line 1, column 7

2022-05-03 00:11:25 Unable to find a server with the specified parameters, using any recommended server

parse error: Invalid numeric literal at line 1, column 7

2022-05-03 00:11:25 Best server : 

2022-05-03 00:11:25 Downloading config: default.ovpn

2022-05-03 00:11:25 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn

2022-05-03 00:11:25 Selecting the best server...

parse error: Invalid numeric literal at line 1, column 7

parse error: Invalid numeric literal at line 1, column 7

2022-05-03 00:11:25 Searching for technology: openvpn_tcp

parse error: Invalid numeric literal at line 1, column 7

2022-05-03 00:11:25 Unable to find a server with the specified parameters, using any recommended server

parse error: Invalid numeric literal at line 1, column 7

2022-05-03 00:11:25 Best server : 

2022-05-03 00:11:25 Downloading config: .ovpn

2022-05-03 00:11:25 Downloading from: https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/.tcp.ovpn

No VPN configuration provided. Using default.

Modifying /etc/openvpn/nordvpn/default.ovpn for best behaviour in this container

Modification: Point auth-user-pass option to the username/password file

Modification: Change ca certificate path

Modification: Change ping options

Modification: Update/set resolv-retry to 15 seconds

Modification: Change tls-crypt keyfile path

Modification: Set output verbosity to 3

Modification: Remap SIGUSR1 signal to SIGTERM, avoid OpenVPN restart loop

Setting OpenVPN credentials...

adding route to local network 192.168.0.0/24 via 172.17.0.1 dev eth0

Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.7)

Use --help for more information.

Starting container with revision: 8cc1870cc039201e0e2f8b7684a9f4e96ae03ab9

**Comment by edgd1er** [comment]
I'm sorry I won't have time to elaborate:
* try not to comment on a closed issue, create a new one.
* try with dev image as nordvpn scripts are more resilient and verbose about the error. developments for nordvpn scripts are not yet merged into master.
* there are few hints that indicate that the api didn't respond: best server is empty, download url is malformed, many parsing errors. root cause, because of an unknown error the container is restarting in a loop, hammering nordvpn api. For proctection, you have been blocked from the api, returning an html page: (Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/nordvpn/default.ovpn:1: html (2.4.7)). 

Fix:
stop the container for a while (few hours at least) and restart monitoring the logs. if ever you still have the html error, empty best server, parsing errors, stop for a few more hours. Most of the time, When I had that message, the next day it was ok.

**Comment by outerepic** [comment]
Thanks for your reply, sorry I am short on time as well and haven't been able to create a new issue. I tried to pull the dev branch and it just gives the following in the logs:

Starting container with revision: 795098d51b6e15cc2ac872335dd8e907580abba8

Creating TUN device /dev/net/tun

mknod: /dev/net/tun: File exists

Starting container with revision: 795098d51b6e15cc2ac872335dd8e907580abba8

Creating TUN device /dev/net/tun

mknod: /dev/net/tun: File exists

Starting container with revision: 795098d51b6e15cc2ac872335dd8e907580abba8

Creating TUN device /dev/net/tun



Here is my full compose file

transmission:
    container_name: transmission
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - /volume1/Media/Downloads/Incomplete:/Media/Downloads/Incomplete
      - /volume1/Media/Downloads/Completed:/Media/Downloads/Completed
      - /volume1/docker/transmission/resolv.conf:/etc/resolv.conf
      - /volume1/docker/transmission:/config
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      #   - OPENVPN_CONFIG=us9214.nordvpn.com.ovpn
      - OPENVPN_USERNAME=XXX
      - OPENVPN_PASSWORD=XXX
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_OPTS=--inactive 3600 --ping 20 --ping-exit 120
      - GLOBAL_APPLY_PERMISSIONS=true
      - TRANSMISSION_HOME=/config/transmission-home
      - TRANSMISSION_RPC_PORT=9091
      - TRANSMISSION_DOWNLOAD_DIR=/Media/Downloads/Completed
      - TRANSMISSION_INCOMPLETE_DIR=/Media/Downloads/Incomplete
      - TRANSMISSION_WATCH_DIR=/Media/Downloads/Watch
      - CREATE_TUN_DEVICE=true
      - ENABLE_UFW=false
      - UFW_ALLOW_GW_NET=false
      - UFW_EXTRA_PORTS=
      - UFW_DISABLE_IPTABLES_REJECT=false
      - PUID=1031
      - PGID=100
      - DROP_DEFAULT_ROUTE=
      - WEBPROXY_ENABLED=false
      - WEBPROXY_PORT=8888
      - WEBPROXY_USERNAME=
      - WEBPROXY_PASSWORD=
      - LOG_TO_STDOUT=false
      - HEALTH_CHECK_HOST=duckduckgo.com
      #   - REVISION=73ec516cc246972289c7b96ffa88c81e037fe364
      - TZ=XXX
      - NORDVPN_PROTOCOL=tcp
      - NORDVPN_CATEGORY=P2P
      - NORDVPN_COUNTRY=US
      - LOCAL_NETWORK=192.168.0.0/24
      #dns:
      # - 1.1.1.1
      #- 1.0.0.1
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    image: haugene/transmission-openvpn:dev
    hostname: transmission
    #privileged: true
    restart: unless-stopped
    network_mode: bridge

**Comment by edgd1er** [comment]
Have a look at https://haugene.github.io/docker-transmission-openvpn/config-options/ about CREATE_TUN_DEVICE=

**Comment by outerepic** [comment]
I've had this same setup for over a year now and it's never given me an issue for the TUN device before. Are you suggesting that I don't need both of the following parameters? I can set the create one to false and try that.

CREATE_TUN_DEVICE=true
devices:
- /dev/net/tun
