### ISSUE TITLE
Permission issues with transmission folder

### ISSUE THREAD

**Issue by mashical** [haugene/docker-transmission-openvpn#77]
Hi, I can run the docker container okay and connect and download torrents just fine while connected to the vpn.

My issue is that the transmission folder (mount to /home/transmission for me) is set to root for user:group, so every time transmission downloads something I have to sudo chown or chmod to delete it from the folder.

I've tried changing from running with --privileged to 
--cap_add=NET ADMIN --device /dev/net/tun 
As I thought that might help, but I still get the same file/folder permission issue. 

I've also tried editing the dockerfile and building a new image.  
RUN mkdir /data
RUN chown -R nobody:nogroup /data
VOLUME /data
But it doesn't make a difference

Do you have any suggestions for managing permissions issue?

**Comment by rolandb5** [comment]
Face the same issue, Sonarr of Couch cannot alter/read the file due to this reason

**Comment by haugene** [comment]
The Docker daemon is running as root and that's why the files created by the container is also owned by root. The solution is to create the files inside the container with a UID/GID that corresponds to the wanted user outside the container. As proposed in #89 

Closing this issue and will follow up in the other issue instead.
