### ISSUE TITLE
Connection timed out IVACY NAS Synology

### ISSUE THREAD

**Issue by bruvv** [haugene/docker-transmission-openvpn#798]
**Describe the problem**
When running it on my synology NAS, and all is perfectly setup acording to the readme and a youtube video I found. I get:

```
TCP: connect to [AF_INET]188.72.80.1:80 failed: Connection timed out
```
**Add your docker run command**
I am using the GUI from synology so no command.
![image](https://user-images.githubusercontent.com/3063928/56866379-b3afb500-69d8-11e9-9e37-e80e0628d636.png)
![image](https://user-images.githubusercontent.com/3063928/56866382-c1653a80-69d8-11e9-8ae9-472a24d75669.png)
![image](https://user-images.githubusercontent.com/3063928/56866385-c9bd7580-69d8-11e9-9bce-26542966a7ab.png)
![image](https://user-images.githubusercontent.com/3063928/56866388-d17d1a00-69d8-11e9-925c-72b46f7e1e7f.png)

**Logs**
```
WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
TCP/UDP: Preserving recently used remote address: [AF_INET]188.72.80.1:80
Attempting to establish TCP connection with [AF_INET]188.72.80.1:80 [nonblock]
TCP: connect to [AF_INET]188.72.80.1:80 failed: Connection timed out
```

**Host system:**
Synology NAS completely updated with everything. (latest DSM and docker from synology package center)

**Comment by incmve** [comment]
I have the same issue.
Try GermanyFrankfurtTCP instead of GermanyFrankfurtTCP

**Comment by bruvv** [comment]
Could there be something that is ivacy's problem ? I've checked their config files and they're the same as here.

**Comment by AndrewPetrides** [comment]
I am having a similar issue and am told by Ivacy that some information has changed on their end which is not reflected in the latest config files you can download from their website.

**Comment by ToneStrife** [comment]
Hi, 
I have Ivacy working with open VPN but i haven't been able to have Transmission port to be open. 
Any help?

**Comment by haugene** [comment]
@ToneStrife To get an open port in Transmission you would have to check if Ivacy supports this. Few providers do. Because you tunnel all your traffic over VPN there is no use in opening ports on your local router, as that is not your public IP anymore. This image provides automatic setup of port forwarding for "perfectprivacy" and "PIA" providers as they have scripts to get a port assigned. But you have to ask Ivacy about this, no one else can help there. It's their IP you want to open ports on.

As for the rest here. @bruvv, @incmve @AndrewPetrides. This is still an issue I guess?
I just downloaded ivacy configs and compared them to the ones in this project. Everything seems to be up to date. I might have gotten an old version, can someone verify? If the configs are up-to-date I'm tempted to say that this is an issue on the Ivacy side.

**Comment by incmve** [comment]
@haugene The files at Ivacy seem old.
Somehow my VPN to NetherlandsAmsterdamTCP works again.
NetherlandsAmsterdamUDP.ovpn does not.

It think Ivacy just needs to update those old config files.
