### ISSUE TITLE
Anonine Netherlands has changed

### ISSUE THREAD

**Issue by b0red** [haugene/docker-transmission-openvpn#836]
anonine.net

Probably all of them, since I keep getting error: 

`Thu Jun 13 00:19:11 2019 RESOLVE: Cannot resolve host address: nl.anonine.net:1195 (Temporary failure in name resolution)`
and I think they've changed port 1195 to 1194. But I think there is something else going on as well, I changed in my default anonine config (Netherlands-Amsterdam to port 1194) bu I still get the error mentioned before.

**Where are the configs?**
I cant get a download link, the site uses css and stuff.

**Comment by haugene** [comment]
Not sure if this is still an issue. It might be that they've changed ports or otherwise updated config,  but "failure in name resolution" sounds like a DNS issue - not connecting to a specific port.

As I can ping nl.anonine.net from my computer the DNS record is still there. Check the README and other issues relating to DNS. Usually setting the Google DNS servers for the container does the trick.

Closing this for now. Re-open if that doesn't solve it, and sorry for the late answer.
