### ISSUE TITLE
Completed files not moving into destination folder

### ISSUE THREAD

**Issue by Biosha** [haugene/docker-transmission-openvpn#837]
Since few weeks my torrents are not moved into their destination folder.

Curious thing : when I [check the location](https://gyazo.com/305bf93f31ca6e34fac02d7302d9b4fc) of the file in transmission it says the file is exactly where I want, but when I search there, the files isn't here but in [incompleted](https://gyazo.com/60e7c8ef79b43c85990c49f15faee314).

Do you have any idea why I got this issue ?

**Comment by haugene** [comment]
Well, setting the location in Transmission is just where you want the file(s) to end up. If they're in incomplete then I would guess it's because it's incomplete? But I guess since you're opening an issue that this is not the case - and the torrent is downloaded but still is in the incomplete folder.

In general. As long as the download locations you've set matches your volume mounts then it should work fine. Other issues with this then sounds to be more of an issue with Transmission?

**Comment by IamDan77** [comment]
Im having the same issue on a synology NAS. Suddenly stopped transfering completed torrents. They just sit in the incomplete folder  when finished.

**Comment by nsar1907** [comment]
I cant even set location for torrent files. How is this possible?

**Comment by matthewjporter** [comment]
Having the same issue in docker on ubuntu. Any update or ideas?

These are my mount points/volumes passed:
      - /mnt/nas/temp/torrents/incomplete:/data/incomplete
      - /mnt/nas/temp/torrents/completed:/data/completed
      - /mnt/nas/temp/torrents/watch:/data/watch

**Comment by haugene** [comment]
What have you tried to narrow this down?
Is it mounted on NFS shares? If so, can you try to mount it on a local disk instead and see if that works? Also can you try to just mount the /data instead of all the sub-folders?

I don't know what is causing this. I feel that this is either an issue with Docker or with Transmission and not something we control from this image.

**Comment by matthewjporter** [comment]
@haugene 

I would tend to agree and think its on the tranmission side.

Its a CIFS/SMB share on my nas its connecting to. I can access (read & write) to all folders from windows, mac and ubuntu via the share

The docker host (ubuntu) running this has multiple other connections to the NAS and can access fine

I will try running local and to change my mount points to a single path and feedback

Cheers

**Comment by pkishino** [comment]
@matthewjporter ay update on this or can we close this?

**Comment by fredericrous** [comment]
I'm experiencing the same issue. I mounted the volumes as follow in docker compose

```
        - /share/containers/transmission/config:/data/config
        - /share/containers/transmission/transmission-home:/data/transmission-home
        - /share/Media/downloads:/data/downloads
        - /share/Media/incomplete:/data/incomplete
        - /share/Media/completed:/data/completed
```

/share/Media is a symbolic link to /CACHEDEV3_DATA/media/

no issue if I mount directly /share/Media/transmission:/data
