### ISSUE TITLE
Mullvad IPv6 issue with Docker-Compose

### ISSUE THREAD

**Issue by saob-school** [haugene/docker-transmission-openvpn#847]
This is my first time using Ubuntu and docker, so I apologise if this request isn't the right place, or I'm just totally way off and no idea what I'm talking about! But any help would be appreciated.

I'm using Mullvad for my VPN, and had issues with IPv6. Was fixed using the previous issue replies by adding '--sysctl net.ipv6.conf.all.disable_ipv6=0' to the run command, The workaround is in the readme under Synology. 

I'm currently using docker-compose with a YAML file for all my other containers, but because the --sysctl command cannot be passed during build, I have to use the run command. 

I was wondering if there is any possible way to run the container from docker-compose? Can I turn off the IPv6 settings from the YAML file? Or, is there any other workaround to the configuration files to fix this issue? I'd like to use docker-compose instead of using the run command essentially.

### **EDIT: Solved**
As per @haugene last reply, you need to edit the .ovpn file you are using, remove the `tun-ipv6` line, and add the 3 `pull-filter` lines but adding a space before the final quote.

> Edit the ovpn file you're using:
> 
> `# vim mullvad_au-per_udp.ovpn`
> 
> Remove (or comment with #) the tun-ipv6 line. Then save and exit with :wq ... ...add lines to filter out IPv6 config that might be pushed on connect. Examples: https://forum.manjaro.org/t/openvpn-and-ipv6-with-systemd-networkd/46415/7
> 
> `pull-filter ignore "dhcp-option DNS6 "` _**(trailing space added)**_
> `pull-filter ignore "tun-ipv6 "` _**(trailing space added)**_
> `pull-filter ignore "ifconfig-ipv6 "` _**(trailing space added)**_
> 

I had to create the container in docker-compose, let it run and crash, and then kill the container.
I then replaced the config inside the container with the following command from the host:

`docker cp mullvad_au-per_udp.ovpn transmission-openvpn:/etc/openvpn/mullvad/`

Restarted the container and it worked perfectly, thanks again @haugene

**Comment by haugene** [comment]
Hey. You can definitely set the same sysctl option with the yaml file:
https://docs.docker.com/compose/compose-file/#sysctls

**Comment by saob-school** [comment]
Thank you so much for the reply!
I'm using v3.7, and docker-compose v1.24.1
I've tried adding the following to the YAML file:
```
sysctls:
   - net.ipv6.conf.all.disable_ipv6=0
```
But it seems to have no affect on the container. 
[Looked a bit deeper](https://github.com/moby/moby/issues/20569) and it seems `--ipv6` is a daemon-wide flag that I can't override.
So it seems it looks like it's a problem with docker-compose, so I'm exploring alternative solutions and will post back if I find one.

**Comment by haugene** [comment]
Also, instead of trying to enable IPv6 - would it be worth a shot to try to disable it from Mullvad?
I see that the [configs specify tun-ipv6](https://github.com/haugene/docker-transmission-openvpn/blob/master/openvpn/mullvad/mullvad_au-per_udp.ovpn#L32). It's either that, or they push more configs to the client when the connection is set up.

I realise that you're new to docker. But still, could you try modifying your config inside the container and then restarting it?
Basically exec into the container:
```
docker exec -it transmission-openvpn bash

```

Then install text editor (here vim):
```
apt update && apt install -y vim
```

Edit the ovpn file you're using:
```
# cd /etc/openvpn/mullvad/
# vim mullvad_au-per_udp.ovpn
```

Remove (or comment with #) the tun-ipv6 line. Then save and exit with `:wq`. Now restart the container and see if it works any better. If it still fails, you can try to add lines to filter out IPv6 config that might be pushed on connect. Examples: https://forum.manjaro.org/t/openvpn-and-ipv6-with-systemd-networkd/46415/7

```
pull-filter ignore "dhcp-option DNS6" 
pull-filter ignore "tun-ipv6" 
pull-filter ignore "ifconfig-ipv6"
```

If your container is in a restart-loop you might not be able to exec in and do this, as you'll be thrown out for each reboot. Another option is to create a copy of the .ovpn file locally and mount it in over the existing config, then you can modify it on the host.

**Comment by saob-school** [comment]
Thank you so much!!!

So my container was stuck in a restart-loop because of a fatal error, and I learnt I can't migrate/move the container I made with the run command to my YAML file.
But, your second solution worked!

I created the container with docker-compose, let it crash and then killed it, took a copy of the current .ovpn config I was using, commented out `tun-ipv6` line, tried again and it crashed. Then added the `pull-filter`commands, and boom! Working!!!!

Can't thank you enough, I had a gist of what was going on from lots of github and stackoverflow google results, but your filters in the ovpn were what finally worked for me, so thank you again, I appreciate the time you took!

**Comment by haugene** [comment]
You're welcome! Glad you got it working.
Maybe this should be added to the documentation as the preferred solution to all this ipv6 stuff

**Comment by banana-cabana** [comment]
This was working for me but after a reboot I know have the following error:

Starting container with revision: 60cc14c1339f34eeb94d68102db397a58fc04339
Creating TUN device /dev/net/tun
Using OpenVPN provider: MULLVAT
No VPN configuration provided. Using default.
Setting OpenVPN credentials...
Sat Jan 30 07:41:21 2021 WARNING: file '/config/mullvad_userpass.txt' is group or others accessible
Sat Jan 30 07:41:21 2021 OpenVPN 2.4.10 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan  4 2021
Sat Jan 30 07:41:21 2021 library versions: OpenSSL 1.1.1i  8 Dec 2020, LZO 2.10
Sat Jan 30 07:41:21 2021 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sat Jan 30 07:41:21 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]91.193.4.50:1194
Sat Jan 30 07:41:21 2021 Socket Buffers: R=[212992->425984] S=[212992->425984]
Sat Jan 30 07:41:21 2021 UDP link local: (not bound)
Sat Jan 30 07:41:21 2021 UDP link remote: [AF_INET]91.193.4.50:1194
Sat Jan 30 07:41:21 2021 TLS: Initial packet from [AF_INET]91.193.4.50:1194, sid=5c982a0e da3735cd
Sat Jan 30 07:41:21 2021 VERIFY OK: depth=2, C=SE, ST=Gotaland, L=Gothenburg, O=Amagicom AB, OU=Mullvad, CN=Mullvad Root CA v2, emailAddress=security@mullvad.net
Sat Jan 30 07:41:21 2021 VERIFY OK: depth=1, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=Mullvad Intermediate CA v3, emailAddress=security@mullvad.net
Sat Jan 30 07:41:21 2021 VERIFY KU OK
Sat Jan 30 07:41:21 2021 Validating certificate extended key usage
Sat Jan 30 07:41:21 2021 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Sat Jan 30 07:41:21 2021 VERIFY EKU OK
Sat Jan 30 07:41:21 2021 VERIFY OK: depth=0, C=SE, ST=Gotaland, O=Amagicom AB, OU=Mullvad, CN=ch-zrh-304.mullvad.net, emailAddress=security@mullvad.net
Sat Jan 30 07:41:22 2021 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1557', remote='link-mtu 1558'
Sat Jan 30 07:41:22 2021 WARNING: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
Sat Jan 30 07:41:22 2021 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_CHACHA20_POLY1305_SHA256, 4096 bit RSA
Sat Jan 30 07:41:22 2021 [ch-zrh-304.mullvad.net] Peer Connection Initiated with [AF_INET]91.193.4.50:1194
Sat Jan 30 07:41:23 2021 SENT CONTROL [ch-zrh-304.mullvad.net]: 'PUSH_REQUEST' (status=1)
Sat Jan 30 07:41:23 2021 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 10.8.0.1,redirect-gateway def1 bypass-dhcp,route-ipv6 0000::/2,route-ipv6 4000::/2,route-ipv6 8000::/2,route-ipv6 C000::/2,comp-lzo no,route-gateway 10.8.0.1,topology subnet,socket-flags TCP_NODELAY,ifconfig-ipv6 fdda:d0d0:cafe:1194::1006/64 fdda:d0d0:cafe:1194::,ifconfig 10.8.0.8 255.255.0.0,peer-id 6,cipher AES-256-GCM'
Sat Jan 30 07:41:23 2021 Pushed option removed by filter: 'ifconfig-ipv6 fdda:d0d0:cafe:1194::1006/64 fdda:d0d0:cafe:1194::'
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: compression parms modified
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: --socket-flags option modified
Sat Jan 30 07:41:23 2021 NOTE: setsockopt TCP_NODELAY=1 failed
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: --ifconfig/up options modified
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: route options modified
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: route-related options modified
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: peer-id set
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: adjusting link_mtu to 1624
Sat Jan 30 07:41:23 2021 OPTIONS IMPORT: data channel crypto options modified
Sat Jan 30 07:41:23 2021 Data Channel: using negotiated cipher 'AES-256-GCM'
Sat Jan 30 07:41:23 2021 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Jan 30 07:41:23 2021 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Sat Jan 30 07:41:23 2021 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:02
Sat Jan 30 07:41:23 2021 GDG6: remote_host_ipv6=n/a
Sat Jan 30 07:41:23 2021 ROUTE6: default_gateway=UNDEF
Sat Jan 30 07:41:23 2021 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Sat Jan 30 07:41:23 2021 OpenVPN ROUTE: failed to parse/resolve route for host/network: C000::/2
Sat Jan 30 07:41:23 2021 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Sat Jan 30 07:41:23 2021 OpenVPN ROUTE: failed to parse/resolve route for host/network: 8000::/2
Sat Jan 30 07:41:23 2021 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Sat Jan 30 07:41:23 2021 OpenVPN ROUTE: failed to parse/resolve route for host/network: 4000::/2
Sat Jan 30 07:41:23 2021 OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
Sat Jan 30 07:41:23 2021 OpenVPN ROUTE: failed to parse/resolve route for host/network: 0000::/2
Sat Jan 30 07:41:23 2021 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
Sat Jan 30 07:41:23 2021 Exiting due to fatal error

I'm using the latest mullvat conf files (mounted as /etc/openvpn/mullvat/default.ovpn) and changed it:

client
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
verb 3
remote-cert-tls server
ping 10
ping-restart 60
sndbuf 524288
rcvbuf 524288
cipher AES-256-CBC
tls-cipher TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA
proto udp
auth-user-pass /config/mullvad_userpass.txt
ca /config/mullvad_ca.crt
script-security 2
fast-io
remote-random
remote ch-zrh-004.mullvad.net 1194
remote ch-zrh-304.mullvad.net 1194
remote ch-zrh-002.mullvad.net 1194
remote ch-zrh-302.mullvad.net 1194
remote ch-zrh-301.mullvad.net 1194
remote ch-zrh-201.mullvad.net 1194
remote ch-zrh-001.mullvad.net 1194
remote ch-zrh-202.mullvad.net 1194
remote ch-zrh-305.mullvad.net 1194
remote ch-zrh-003.mullvad.net 1194
remote ch-zrh-303.mullvad.net 1194
pull-filter ignore "dhcp-option DNS6 "
pull-filter ignore "tun-ipv6 "
pull-filter ignore "ifconfig-ipv6 "
