### ISSUE TITLE
Issues installing on Raspberry Pi 4 (Raspbian Desktop)

### ISSUE THREAD

**Issue by andsoitgoes** [haugene/docker-transmission-openvpn#853]
Hi all,

I'm getting an error trying to run this as a docker container on my pi 4 running Raspbian Buster

The message I get is:

standard_init_linux.go:211: exec user process caused "exec format error"

After some googling it seems to be down to loading the incorrect processor version of the Pi, however looking at some other issues this isn't a problem, so I'm wondering if it has anything to do with the new build of the Pi and possibly the Raspbian Buster OS?\

I'd appreciate any help, thanks in advance!

**Comment by edgd1er** [comment]
Hi,

This error is due to to incompatible code being executed on your cpu. For instance, x86 code executed on a arm cpu. May be you didn t specified the tag when you pulled the image.

docker pull haugene/transmission-openvpn
Will pull the latest image for x86_64, it use a default tag being latest. 

For arm you need to specify the tag:
docker pull haugene/transmission-openvpn:latest-armhf


More information here http://haugene.github.io/docker-transmission-openvpn/run-on-arm/

**Comment by andsoitgoes** [comment]
Thank you SO MUCH! That did it!! Up and running like a dream now, cannot tell you how much I appreciate your reply, one little bit of code and that's all it took, you are officially my hero, thanks!
