### ISSUE TITLE
Driver failed programming external connectivity on endpoint transmission

### ISSUE THREAD

**Issue by langme** [haugene/docker-transmission-openvpn#959]
Hello
I have tried to install haugene/transmission-openvpn:latest-armhf on pi4.

`
sudo docker run 

          --cap-add=NET_ADMIN 
          --device=/dev/net/tun -ti 
          --name transmission 
          --sysctl net.ipv6.conf.all.disable_ipv6=0  
          -e OPENVPN_PROVIDER=FASTESTVPN 
          -e OPENVPN_CONFIG=Switzerland-UDP 
          -e OPENVPN_USERNAME=****@***** 
          -e OPENVPN_PASSWORD=******** 
          -e OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60" 
          -e LOCAL_NETWORK=10.0.0.0/24 
          -e WEBPROXY_ENABLED=false 
          -p 9091:9091 
          -e UFW_EXTRA_PORTS=5800 
          -p 5800:5800 
              haugene/transmission-openvpn:latest-armhf

`
The error is : 
`
Digest: sha256:57ea516658dcc161f720698eb37496ba01107b769e4827c252eefef99a588a6d
Status: Downloaded newer image for haugene/transmission-openvpn:latest-armhf
docker: Error response from daemon: driver failed programming external connectivity on endpoint transmission (127ea4d238e6a00a7e8fef782793062415bb5584bb11468e8b38da02c5f95b3c): Error starting userland proxy: listen tcp 0.0.0.0:9091: bind: address already in use.
ERRO[0046] error waiting for container: context canceled 
`
But before this, i killed PID linked to 9091.
Have you a solution ?

**Comment by haugene** [comment]
Well, my first thought is that it is as it says: address already in use. So you should triple-check that it actually is available.

Do you get the same error if you run:
`docker run --rm -it -p 9091:9091 ubuntu echo works` ?

Or if you change the port bind to for example: `-p 34000:9091`? It will then be available on port 34000 on your host.

Lastly, and that would be weird with that error message. But could it be that you're running on an arm64 system? in that case use image `haugene/transmission-openvpn:latest-arm64`

**Comment by langme** [comment]
> So you should triple-check that it actually is available.
I checked with 
`sudo netstat -antlp | grep 9091` no answer

> Do you get the same error if you run:
> `docker run --rm -it -p 9091:9091 ubuntu echo works` ?
it doesn't work 👎 

> Or if you change the port bind to for example: `-p 34000:9091`? 
it works 👍

**Comment by haugene** [comment]
Ok, great 😄  So case closed then?

**Comment by langme** [comment]
i just want to know what means xxxx in 'xxxx:9091'? i know it is a port host :) but which ?

**Comment by haugene** [comment]
When you're starting the container it will start with it's own network stack. So that means it will have it's own IP etc within the Docker network. Typically 172.17.x.y.

Inside the container Transmission will start on port 9091. And inside the container this is always OK because there are no other applications running there that binds that port. Then you can choose yourself which port to bind it to on your host.

The `-p xxxxx:9091` says to bind `your.host.address:xxxxx` to `docker.internal.address:9091`.
This way you can expose the WebUI on any port you want without changing anything in the configuration of Transmission.

Now. There is obviously something going on with your port 9091. It's not a bug with this container because you get the same error with ubuntu. So it has to do with your host or the Docker daemon.

But for now you can just choose any other non-used port (like 34000) and then you can access Transmission on `http://localhost:34000` or `http://your.server.ip:34000`
