### ISSUE TITLE
Add SSL certificate for the WEB UI

### ISSUE THREAD

**Issue by julien-vu** [haugene/docker-transmission-openvpn#961]
Hi, 

My issue:
I'm trying to access my Web UI but the browser reject the connection because there is no ssl certificate for the web ui

Is there anyway to add my certificate to the setup ?

My setup
Nas : synology with SSL certificate
Docker image was mount with the GUI

EDIT : image used : transmission-openvpn and -proxy

**Comment by haugene** [comment]
Since you're already using the proxy image you can mount your own config file and the keys in there.
I would refer you to nginx-forums on how to do this, but there's an example here you might start from #290.

Current config is at: `/etc/nginx/nginx.conf` so you can mount your new config in there and the certificates someplace else as long as you reference them from that config.

**Comment by julien-vu** [comment]
@haugene thanks ! it solved the issue.

For people using the transmission-openvpn-proxy image and synology

SOLUTION

- I have the DDNS configured,

- I exported the certificate (should have 3 files with PEM extension)

- As in the #290 issue, I've done the nginx.conf with cert.pem, key.pem

- Mounted the nginx.conf and PEM files at `/etc/nginx/`

Et voila, it does the tricks
