### ISSUE TITLE
Question: Multiple VPN profiles possible?

### ISSUE THREAD

**Issue by denbue** [haugene/docker-transmission-openvpn#964]
Hi,

when the selected VPN server goes down, the Docker container goes into a restart loop. Instead, it would be helpful to start connecting to an alternative server. Is there an option to set up alternative servers/locations?

Thanks!

**Comment by haugene** [comment]
I thought this was documented somewhere, but couldn't find it now. You can set a comma separated list in the `OPENVPN_CONFIG` variable. A random server will then be picked on startup among the ones you list.

Marking this as a follow-up on #362. The README has gotten a good brush-up since that issue was created but there's still room for improvement.

Hope that solves your problem.

**Comment by denbue** [comment]
It works well, the logs actually state that `3 servers found in OPENVPN_CONFIG, XXX-UDP chosen randomly`.

Thanks for the swift reply!
