### ISSUE TITLE
Add Timezone ENV var

### ISSUE THREAD

**Issue by acahir** [haugene/docker-transmission-openvpn#981]
Mounting /etc/timezone isn't possible on all hosts, such as on Synology NAS boxes

I know it's possible to create a startup script or create a new image based off this one (#104), but including a TZ ENV option would be a great addition.

**Comment by haugene** [comment]
Which version of the image are you running? I see that tzdata is included in the ubuntu based image, but not in alpine. Considering dropping support for one of them (probably ubuntu based one) as there are unfortunate differences...

Anyways, can you try the :latest tag and see if setting the TZ env variable works?

**Comment by phenomenomenom** [comment]
Any update on this enhancement? I am also running on Synology so cannot mount etc/timezone. I am attempting to use transmission alt-speeds to slow things down in the evenings.

All using :latest- I've added environment variable `TZ=Australia/Sydney`. Command `dpkg --list tzdata` from the container terminal shows the package is installed correctly. `date` returns "AEDT" which is correct. Log timestamps all appear to be correct.

I have the following environment variables set to slow things down from 17:30-23:00 every day.
```TRANSMISSION_ALT_SPEED_DOWN=750
TRANSMISSION_ALT_SPEED_TIME_BEGIN=1050
TRANSMISSION_ALT_SPEED_TIME_ENABLED=true
TRANSMISSION_ALT_SPEED_TIME_END=1380
TRANSMISSION_ALT_SPEED_UP=400
```
In the web-gui, all appears how it should:
![image](https://user-images.githubusercontent.com/59358618/77876958-bcb79f00-7297-11ea-9959-e591d613514c.png)

However, come the time to slow things down, nothing happens. Have I missed a setting somewhere?

One more note is that applying the flag:
`TRANSMISSION_ALT_SPEED_ENABLED=true`
does not cause transmission to start in alt-speed.

**Comment by tokyotexture** [comment]
TZ does not get picked up in latest-alpine.

**Comment by haugene** [comment]
Sorry about the delay, it was a simple fix after all. Added tzdata package to alpine image now.
Currently only on the dev branch, so you could use the :dev-alpine tag for now.

Will be pushed to master in a couple of days, and be included in the next release version as well as :latest tag then.

**Comment by phenomenomenom** [comment]
Legend! Thank you.

**Comment by acahir** [comment]
Sorry I never noticed you asked me a question, but thanks again for adding the enhancement!

**Comment by phenomenomenom** [comment]
I hate to be the harbinger of bad news, but alt-speed still doesn't seem to be working with `:dev-alpine`.

All settings and results are identical to my previous post. tzdata seems to be installed. `date` returns the correct time. Scheduling set from -e values is appearing in the transmission UI correctly. The `TRANSMISSION_ALT_SPEED_ENABLED=true` flag still has no effect. I can enable alt-speed manually from the web UI by clicking the rocket/snail button.

I am absolutely not a developer, so I don't know how much value my guess is work. But I'd guess the container timezone is now set and something isn't right with transmission.

**Comment by haugene** [comment]
Hmm. Tempting to point at Transmission of course, if the settings seems to be loaded and visible in the GUI. But since you're saying that the alt-speed can be enabled manually in the UI (and then I guess it's working) it could be interesting to see the settings.json file it generates after you set this.

Transmission doesn't write its settings to file before shutdown. But if you have mounted /data somewhere, then you see "transmission-home" inside there and it has the settings.json file.
What you could do is to start the container and copy this file somewhere. Then enable alt-speed, and stop the container. Now check the settings.json and see if there are any differences. Hopefully at least to the alt-speed option, but maybe there's something else.

If there are no changes, try to change some other option to verify that it is actually written. If not, we might kill the container too abruptly. Then you would have to exec into the container and stop transmission in a more polite manner, and then check the contents.

Since this issue is very much targeted on the tzdata and timezone stuff, I think I'll close it.
If you could create a new issue for the alt-speed, I think it would be cleaner for people looking for answers later.
